### ISSUE TITLE
Stalls at  Waiting for Kubernetes control plane

### ISSUE THREAD

**Issue by martindanko** [coreos/tectonic-forum#10]
### Tectonic Version 
tectonic-1.4.5

### Environment
AWS
eu-west-1 Region.

### Expected Behavior
Kubernetes control plane should start

### Actual Behavior
Kubernetes control plane doesn't seem to register in the installer

### Reproduction Steps

  1. follow installation up until Start Kubernetes
  2. wait as the installation doesn't continue beyond this point.

### Other Information

Having gone through the installation everything appears to work and everything appears to get provisioned correctly with Cloudformation except the **tectonic-tec** load balancer doesn't  produce a healthy 
**tectonic-kube-aws-controller** and the installation just stalls. I have attempted this twice with the same results.

**Comment by robszumski** [comment]
Did you run the commands that were output on the screen after the CloudFormation came up?

They will appear after that step completes. Similar to:

```
unzip assets.zip
scp assets <address of controller>
ssh core@<address of controller> bootkube-start
```

This bootstraps the initial control plane and will get your load balancers passing the health checks.

**Comment by martindanko** [comment]
Hi @robszumski,

I've just tried this again and this time, third time lucky, I eventually got the instructions on the page. The previous two times, after leaving it for over hours, the message explaining about scp'ing the assets never appeared.

Thanks for answering my question, it may be worth noting that is doesn't appear every-time and does stall.

**Comment by robszumski** [comment]
Typically this is due to DNS resolution. The installer waits for your Route 53 address to propagate to your laptop before continuing. If you have issues in the future, try using `dig` to see what your laptop sees.
