### ISSUE TITLE
Upgrade Cluster w/o Controllers

### ISSUE THREAD

**Issue by stevesloka** [coreos/tectonic-forum#100]
### Tectonic Version 

1.5.5-tectonic.2

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

Bare Metal

### Desc

When I deployed the cluster I didn't check to install the Operators, so I have two questions. 

1. Can I upgrade without them? If so how? The installer only allows me to make a new cluster. Does it somehow upgrade? 
2. Can I re-enable Operators on an existing cluster?

**Comment by mfburnett** [comment]
Hey @stevesloka! Thanks for your questions. You need Operators in order to apply Tectonic's self-driving upgrade process; without it, you'll need to do a manual migration to a new cluster. You cannot re-enable Operators on an existing cluster.

**Comment by stevesloka** [comment]
thanks @mfburnett, how then do you upgrade without the operators? The installer wants to do a new install each time. Are there any docs on that? If it's manual, that's fine, but what are all the versions of all the components that we should change version to version?

**Comment by robszumski** [comment]
@stevesloka The recommended way to use Operators. If you aren't using those, it's a boot new + nuke old method. It's not a simple as just updating the version string, as flags change, etc. This is where the Operator steps in to make this easy :)

**Comment by stevesloka** [comment]
Hey @robszumski thanks for following up! That's too bad that there's no way to come back. I guess I'm re-installing. I guess then why not install the operators by default? Maybe the new installer does now? 

Thanks!

**Comment by robszumski** [comment]
@stevesloka We're just being cautious while we test it out, but that's the goal. Hope to flip that switch soon!
