### ISSUE TITLE
Deleting tectonic-identity pod results in permanent failure to authenticate

### ISSUE THREAD

**Issue by elsonrodriguez** [coreos/tectonic-forum#103]
## Issue Report Template
While troubleshooting an inability to login with a new basic user account I deleted a tectonic-identity pod.

Upon deletion, the pod failed to start properly, locking me out of any further logins.

The logs in the pod were as follows:

```
error parse config file /etc/dex/config.yaml: error converting YAML to JSON: yaml: line 37: mapping values are not allowed in this context
```

### Tectonic Version 
1.5.5-tectonic.3
### Environment
AWS
### Expected Behavior
tectonic-identity should survive a reschedule

### Actual Behavior
Not surviving.
### Reproduction Steps

  1. `kubectl delete pod -l app=tectonic-identity -ntectonic-system`
  2.  Try to login to console

**Comment by abh** [comment]
Assuming you changed the configuration then it didn't survive because you misconfigured and then restarted it. It survived being killed fine, just not the restart after being misconfigured. :-)

I don't know if tectonic-identity will get confused running twice, but you could have set the deploy to have two replicas and then only when the new one was running correctly stop the old one.

**Comment by mfburnett** [comment]
Hey @elsonrodriguez thanks for filing this issue. I've let @IvanCherepov know, and he'll followup with you shortly. cc @ericchiang

**Comment by ericchiang** [comment]
@abh is correct. I don't know what tectonic-identity can do better if it detects a bad config.

In our docs we strongly recommend backing up your configmap and rolling your deployment so you can monitor failures like this and roll back if needed: https://coreos.com/tectonic/docs/1.5.6-tectonic.1/admin/user-management.html#identity-configuration

> I don't know if tectonic-identity will get confused running twice, but you could have set the deploy to have two replicas and then only when the new one was running correctly stop the old one.

tectonic-identity is stateless. You can run as many as you want.

**Comment by elsonrodriguez** [comment]
@ericchiang This was definitely user error of some sort, I removed the recent entry on the tectonic-identity configmap and this pod is now running again and I'm able to login.
