### ISSUE TITLE
Unable to successfully follow instructions to add static user.

### ISSUE THREAD

**Issue by elsonrodriguez** [coreos/tectonic-forum#104]
## Issue Report Template
Unable to follow instructions to add a Static user to Tectonic due to 404 and other issues.

https://coreos.com/tectonic/docs/latest/admin/user-management.html#add-static-user

The 404 happens while trying to install `bcrypt-tool` 

Additionally, the hash generated by a locally-built bcrypt-tool did not result in a working account. The default "cost" argument probably does not match what was used in my Tectonic install.

### Tectonic Version 
1.5.5-tectonic.3
### Environment
AWS

### Reproduction Steps

For the bcrypt download: 
 `wget https://github.com/coreos/bcrypt-tool/releases/download/v1.0.0/bcrypt-tool-v1.0.0-linux-amd64.tar.gz`

For the hash generation:
 ```
./bcrypt-tool 
Enter password: 
Re-enter password: 
```

**Comment by robszumski** [comment]
There seems to be a mis-match on the release tag (1.0.0) and the binary names (1.0.1). You can grab a correct link here: https://github.com/coreos/bcrypt-tool/releases/tag/v1.0.0

**Comment by robszumski** [comment]
I fixed the release binary names, sorry about that!

**Comment by elsonrodriguez** [comment]
@robszumski Should I open another issue for the hash issue?

**Comment by robszumski** [comment]
@elsonrodriguez Did you use the CoreOS bcrypt-tool or another one? I believe the tool has the right settings encoded into it.
