### ISSUE TITLE
/var/lib/matchbox/profiles/install-reboot.json permission denied

### ISSUE THREAD

**Issue by rothgar** [coreos/tectonic-forum#106]
### Tectonic Version 
1.5.6-tectonic.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
bare metal
### Expected Behavior
Final submit step in installer would work
### Actual Behavior
Could not submit the config
### Reproduction Steps

  1. Follow [documentation](https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html)
  2. install matchbox with rpm

### Other Information
Error from installer shows
```
ERRO[0552] &{rpc error: code = 2 desc = open /var/lib/matchbox/profiles/install-reboot.json: permission denied Error pushing cluster data to provisioner: rpc error: code = 2 desc = open /var/lib/matchbox/profiles/install-reboot.json: permission denied 400} 
```
I had to manually create /var/lib/matchbox/profiles (probably needs a separate ticket to fix)
```
$ ls -l /var/lib/matchbox
total 0
drwxr-xr-x. 3 root root 19 Apr 17 21:42 assets
drwxr-xr-x. 2 root root 32 Apr 17 21:55 profiles
```

![selection_047](https://cloud.githubusercontent.com/assets/371796/25115152/134a7030-23b9-11e7-99fa-836edc8eec4b.png)

**Comment by mfburnett** [comment]
Hey @rothgar, thanks for filing this issue. I've looped in @dghubble, and he should be able to get back to you shortly.

**Comment by dghubble** [comment]
The RPM [matchbox.service](https://github.com/coreos/matchbox/blob/master/contrib/systemd/matchbox.service#L6) or local binary [matchbox-local.service](https://github.com/coreos/matchbox/blob/master/contrib/systemd/matchbox-local.service) unit runs the service as user "matchbox" so a `chown` is mentioned in the install [docs](https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html#install).

```
sudo chown -R matchbox:matchbox /var/lib/matchbox
```

Its desired that the matchbox RPM create this directory. Tracking in https://github.com/coreos/matchbox/issues/481

**Comment by rothgar** [comment]
The rpm should probably do that for the use too. When installing via RPM I assumed the "Generic Install" steps didn't apply to me.

**Comment by robszumski** [comment]
Looks like this is being resolved upstream in Matchbox. Re-open if needed.
