### ISSUE TITLE
Tectonic Stuck at power on the nodes

### ISSUE THREAD

**Issue by Tectoniclover** [coreos/tectonic-forum#107]
## Issue Report Template
Tectonic stuck at power on the nodes (Bare Metal) one controller and two workers
### Tectonic Version 
1.5.5 and 1.5.6
### Environment
Physical Hardware ( three HP Proliant G7 Servers for controller and workers) (one provision / PXE Centos VM)
What hardware/cloud provider/hypervisor is being used with Tectonic?
Bare Metal ( HP Proliant DL360 G7)
### Reproduction Steps
I have configured provision(matchbox+PXE)  Centos VM 
![screenshot-8](https://cloud.githubusercontent.com/assets/27780530/25194201/4c9f72fa-2557-11e7-81d7-23a941b1010f.png)
node correctly as per official guide on coreos.com and my physical nodes (Controller and Workers - HP Proliant 360 G7) booting from CoreOS PXE Server (See attached image).
But still Tectonic Installer stuck at poweron the nodes. 

Here is the status of Matchbox:
 systemctl status matchbox.service 
● matchbox.service - CoreOS matchbox Server
   Loaded: loaded (/usr/lib/systemd/system/matchbox.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/matchbox.service.d
           └─override.conf
   Active: active (running) since Wed 2017-04-19 13:42:49 CEST; 22min ago
     Docs: https://github.com/coreos/matchbox
 Main PID: 2495 (matchbox)
   CGroup: /system.slice/matchbox.service
           └─2495 /usr/bin/matchbox -address=192.168.51.151:8080 -rpc-address=192.168.51.151:8081 -log-level=debug -data-path=/var/lib/matchbox -assets-path=/var/lib/matchbox/assets -cert-file /etc/matchbox/server.crt -key-file /etc/m...

Apr 19 13:52:02 provision.example.com matchbox[2495]: time="2017-04-19T13:52:02+02:00" level=info msg="HTTP GET /matchbox/coreos"
Apr 19 13:52:12 provision.example.com matchbox[2495]: time="2017-04-19T13:52:12+02:00" level=info msg="HTTP GET /matchbox/"
Apr 19 13:52:33 provision.example.com matchbox[2495]: time="2017-04-19T13:52:33+02:00" level=info msg="HTTP GET /matchbox/assest"
Apr 19 13:52:42 provision.example.com matchbox[2495]: time="2017-04-19T13:52:42+02:00" level=info msg="HTTP GET /matchbox/assest/"
Apr 19 13:54:05 provision.example.com matchbox[2495]: time="2017-04-19T13:54:05+02:00" level=info msg="HTTP GET /matchbox/assets/"
Apr 19 13:54:15 provision.example.com matchbox[2495]: time="2017-04-19T13:54:15+02:00" level=info msg="HTTP GET /matchbox/assets/coreos/"
Apr 19 13:54:23 provision.example.com matchbox[2495]: time="2017-04-19T13:54:23+02:00" level=info msg="HTTP GET /matchbox/assets/coreos/"
Apr 19 13:54:37 provision.example.com matchbox[2495]: time="2017-04-19T13:54:37+02:00" level=info msg="HTTP GET /matchbox/assets/coreos/1298.7.0/"
Apr 19 13:55:11 provision.example.com matchbox[2495]: time="2017-04-19T13:55:11+02:00" level=info msg="HTTP GET /matchbox/assets/coreos/1298.7.0/"
Apr 19 13:55:18 provision.example.com matchbox[2495]: time="2017-04-19T13:55:18+02:00" level=info msg="HTTP GET /assets/coreos/1298.7.0/"

# curl http://provision.example.com:8080
matchbox

# curl -L http://provision.example.com:8080/assets/coreos/1298.7.0/
<pre>
<a href="CoreOS_Image_Signing_Key.asc">CoreOS_Image_Signing_Key.asc</a>
<a href="coreos_production_image.bin.bz2">coreos_production_image.bin.bz2</a>
<a href="coreos_production_image.bin.bz2.sig">coreos_production_image.bin.bz2.sig</a>
<a href="coreos_production_pxe.vmlinuz">coreos_production_pxe.vmlinuz</a>
<a href="coreos_production_pxe.vmlinuz.sig">coreos_production_pxe.vmlinuz.sig</a>
<a href="coreos_production_pxe_image.cpio.gz">coreos_production_pxe_image.cpio.gz</a>
<a href="coreos_production_pxe_image.cpio.gz.sig">coreos_production_pxe_image.cpio.gz.sig</a>
</pre>

#openssl s_client -connect provision.example.com:8081 -CAfile /etc/matchbox/ca.crt -cert /etc/matchbox/client.crt -key /etc/matchbox/client.key
CONNECTED(00000003)
depth=1 CN = fake-ca
verify return:1
depth=0 CN = fake-server
verify return:1
---
Certificate chain
 0 s:/CN=fake-server
   i:/CN=fake-ca
---
Server certificate

DNS : 
dig provision.example.com 
;; ANSWER SECTION:
provision.example.com.    86400    IN    A    192.168.51.151
;; AUTHORITY SECTION:
example.com.        86400    IN    NS    provision.example.com.

dig controller.example.com
;; ANSWER SECTION:
controller.example.com.    86400    IN    A    192.168.51.157

;; AUTHORITY SECTION:
example.com.        86400    IN    NS    provision.example.com.

;; ADDITIONAL SECTION:
provision.example.com.    86400    IN    A    192.168.51.151

dig worker1.example.com  &  worker2.example.com
worker1.example.com.    86400    IN    A    192.168.51.159
worker2.example.com.    86400    IN    A    192.168.51.161
Fixed DHCP IP 

}
host controller {
  hardware ethernet e4:11:5b:d3:63:4c;
  fixed-address 192.168.51.157;
}

host worker1 {
  hardware ethernet e4:11:5b:d4:45:70;
  fixed-address 192.168.51.159;
}

host worker2 {
  hardware ethernet e4:11:5b:d6:44:40;
  fixed-address 192.168.51.161;

Do I need to have dns matchbox.example.com ? I have configured provision.example.com:8080 and provision.example.com:8081 instead of matchbox.example.com in matchbox endpoints in Tectonic installer i don't think so it does matters. Does it?
Do i need boot.ipxe ?? doesn't need it i believe as my nodes are booting from pxe server.  (see attached image) 
Nodes gets dhcp fixed IP and have internet working on it.   but still I don't see any status on controller and workers that Tectonic Installer downloading and installing container Linux on it or pushing to install Container Linux. 
Can you please guide me experts where I am wrong.

### Other Information
This excercise I have done on Xen Virtutalization too booting core pxe on Xen VM and same issue - Tectonic stuck at power on the nodes.
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

### Other Information
https://groups.google.com/forum/#!topic/coreos-user/4b3zn5iadCc 

Please let me know if you need more information/logs etc.

Thanks,
Amit

**Comment by dghubble** [comment]
You need to chainload PXE clients to iPXE and then delegate iPXE clients to matchbox.example.com:8080/boot.ipxe. This is described in [network-setup](https://coreos.com/tectonic/docs/latest/install/bare-metal/network-setup.html). Matchbox is configured by clients (such as Tectonic Installer) through the API you setup (shown via openssl verify) and it will match machines by MAC to the right iPXE config (and other configs later).

In your case, it sounds like you have an existing network boot setup for PXE clients so see the section "Configurable TFTP" to chainload to iPXE and matchbox in a menuentry or as the default.

**Comment by Tectoniclover** [comment]
Thanks Daltan,
Appreciated that helped me to install Controller and worker on my test vm(xen) , Now I am stuck at connect nodes.  After installation wasn't able to start bootkube service on controller.   Had to start manually.   ./bootkube-start  still not able to connect nodes.

Here is logs 👍 
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:31.001076    1401 pod_workers.go:184] Error syncing pod 8f609d0f-274f-11e7-8848-46856906fe
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:31.214344    1401 pod_workers.go:184] Error syncing pod 8f609b53-274f-11e7-8848-46856906fe
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.292683    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.292860    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.292866    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.293279    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.392900    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.393018    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.616440    1401 docker_manager.go:2519] checking backoff for container "kube-flannel" in
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:31.616558    1401 docker_manager.go:2533] Back-off 5m0s restarting failed container=kube-f
Apr 22 14:10:31 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:31.616588    1401 pod_workers.go:184] Error syncing pod 2872fb99-2761-11e7-9da9-46856906fe
Apr 22 14:10:32 testcontroller.example.com kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Apr 22 14:10:32 testcontroller.example.com kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Apr 22 14:10:32 testcontroller.example.com kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.480804    1401 cni.go:255] Error adding network: open /run/flannel/subnet.env: no such
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.481415    1401 cni.go:209] Error while adding to cni network: open /run/flannel/subnet.
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.487711    1401 docker_manager.go:2196] Failed to setup network for pod "kube-dns-218566
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.495088    1401 cni.go:255] Error adding network: open /run/flannel/subnet.env: no such
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.495146    1401 cni.go:209] Error while adding to cni network: open /run/flannel/subnet.
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.495182    1401 docker_manager.go:2196] Failed to setup network for pod "kube-controller
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.503586    1401 cni.go:255] Error adding network: open /run/flannel/subnet.env: no such
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.503640    1401 cni.go:209] Error while adding to cni network: open /run/flannel/subnet.
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.503696    1401 docker_manager.go:2196] Failed to setup network for pod "kube-scheduler-
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.526860    1401 docker_manager.go:372] NetworkPlugin cni failed on the status hook for p
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]:  with error: exit status 1
Apr 22 14:10:32 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:32.598381    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:32.859461    1401 pod_workers.go:184] Error syncing pod 8f609c78-274f-11e7-8848-46856906fe
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:33.049619    1401 pod_workers.go:184] Error syncing pod 8f60a29b-274f-11e7-8848-46856906fe
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:33.077241    1401 pod_workers.go:184] Error syncing pod 8f609b53-274f-11e7-8848-46856906fe
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:33.133680    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:33.133711    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: I0422 14:10:33.133740    1401 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kuber
Apr 22 14:10:33 testcontroller.example.com kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:33.627478    1401 cni.go:255] Error adding network: open /run/flannel/subnet.env: no such
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:33.627538    1401 cni.go:209] Error while adding to cni network: open /run/flannel/subnet.
Apr 22 14:10:33 testcontroller.example.com kubelet-wrapper[1401]: E0422 14:10:33.627580    1401 docker_manager.go:2196] Failed to setup network for pod "kube-scheduler-
Apr 22 14:10:33 testcontroller.example.com kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)

**Comment by amit2277** [comment]
close this issue , Resolved - Reinstalled OS again

**Comment by mfburnett** [comment]
@Tectoniclover are you okay with closing this issue? Did you get the issue resolved?

**Comment by Tectoniclover** [comment]
Hi Mackenzie,Yes please close this issue :)Thanks,Amit                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Mackenzie BurnettSent: Monday 24 April 2017 23:11To: coreos/tectonic-forumReply To: coreos/tectonic-forumCc: Tectoniclover; MentionSubject: Re: [coreos/tectonic-forum] Tectonic Stuck at power on the nodes (#107)@Tectoniclover are you okay with closing this issue? Did you get the issue resolved?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/coreos/tectonic-forum","title":"coreos/tectonic-forum","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/coreos/tectonic-forum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mfburnett in #107: @Tectoniclover are you okay with closing this issue? Did you get the issue resolved?"}],"action":{"name":"View Issue","url":"https://github.com/coreos/tectonic-forum/issues/107#issuecomment-296764669"}}}
