### ISSUE TITLE
No config.json available to upload for Tectonic Installer

### ISSUE THREAD

**Issue by khanattlab** [coreos/tectonic-forum#108]
### Tectonic Version 
1.5.6
### Environment
Bare-Metal
What hardware/cloud provider/hypervisor is being used with Tectonic?
Dell Poweredge
### Expected Behavior
config.json available in my account
### Actual Behavior
No config.json available. Only Kuberenetes secrete yaml file which Tectonic installer will not accept
### Reproduction Steps

  1. ...Create matchbox provisioning node and start Tectonic installer
  2. ...Load CoreOS license an config.json. No config.json available to download.

### Other Information
This could be because I had a CoreOS Tectonic Starter license last year but added the Tectonic 10 node license and dont have access to the json file to upload.
## Feature Request
NA
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
NA
### Desired Feature
NA

### Other Information
NA

**Comment by robszumski** [comment]
@khanattlab Do you see the `dockercfg` tab? This is the one you need to use:

![image](https://cloud.githubusercontent.com/assets/755540/25348510/577ffc6a-28d3-11e7-97e9-3a832d81898a.png)

We are working on removing the Kubernetes specific secret, as we don't end up requiring that version in the installer. I understand its name is confusing. 

Let me know if that pull secret works for you.

**Comment by khanattlab** [comment]
Thanks - the dockercfg does work. I kept trying the Kubernetes Secret. thank you

**Comment by robszumski** [comment]
Sorry for the confusion, glad it worked for you!
