### ISSUE TITLE
tectonic release tarball includes ./ entry

### ISSUE THREAD

**Issue by dannysauer** [coreos/tectonic-forum#109]
### Tectonic Version 
tectonic-1.5.6-tectonic.1.tar.gz

### Environment
generic Linux (bare-metal install, per https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html)

What hardware/cloud provider/hypervisor is being used with Tectonic?
N/A

### Expected Behavior
extracting tarball shouldn't change permissions of current directory

### Actual Behavior
extracting tarball with default options results in current directory permissions being changed to 0755, which is a problem when the extracting user has write permission to the current directory.  Like if it's extracted in a user's previously-restrictive home directory or if someone writes some root-executed automation which extracts the file in /tmp, leading to no one being able to write to /tmp (whoops).

### Reproduction Steps

  1. download tarball
  2. `mkdir ./somedir && chmod 0700 ./somedir && cd ./somedir`
  2. extract downloaded tarball using "tar xzvf ..." per instructions
  3. `ls -ld ../somedir` and notice that permissions are no longer 0700.

## Feature Request
Ideally, don't include "./" when creating the tar file; create it with `tar cvf $OUT ./tectonic` instead of `tar -cvf $OUT .`, or similar.

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by robszumski** [comment]
Thanks for reporting this @dannysauer, definitely not intended. We'll get it fixed up.

**Comment by sym3tri** [comment]
@robszumski can you move to the installer issues?

**Comment by robszumski** [comment]
Moved to https://github.com/coreos/tectonic-installer/issues/373. @dannysauer feel free to subscribe there if you want updates.
