### ISSUE TITLE
Can't resume setting up process when internet connection is disconnected while setting up

### ISSUE THREAD

**Issue by ryuheechul** [coreos/tectonic-forum#11]
### Tectonic Version 
1.4.5
### Environment
Mac/Chrome
What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS
### Expected Behavior
go back to setting up 
### Actual Behavior
Can't go back to where I was
### Reproduction Steps

  1. Do installation process
  2. disconnect internet and reconnect internet or refresh page

### Other Information
Please make it possible going back to where I was so that I can finish setting up without deleting everything in AWS whenever stuck in setting process.
There is going to Where I was button but it just doesn't work.

**Comment by sym3tri** [comment]
Hi @ryuheechul,

Thanks for the feedback. We have some improvements planned that should alleviate most of this. 

For now the recommended approach is to fully delete the stack formation that was created and start over. If you clicked the "save progress" link on the top right you can upload the state of your previous install attempt, so you don't have to fill in everything again.

**Comment by ryuheechul** [comment]
Hi @sym3tri,

Thanks, I actually already did what you said to continue setting up and managed to run Tectonic successfully.
Great to hear about improvements coming.
Thanks for the good work. 👍
