### ISSUE TITLE
Identity server seems to have crashed. How to restart it?

### ISSUE THREAD

**Issue by nithin-bose** [coreos/tectonic-forum#113]
Tectonic identity server seems to have crashed. 

The tectonic dashboard is not loading and all ``kubectl`` commands return the following error:
``Error: could not get kubernetes client: error fetching provider config: Get https://<server-url>/identity/.well-known/openid-configuration: EOF``

However all the deployed services and the cluster itself is up and seems to be working fine. How can i restart the identity server?

**Comment by sym3tri** [comment]
You can bypass Tectonic Identity with kubectl by using the TLS client cert in your assets.zip. See docs for details: https://coreos.com/tectonic/docs/latest/admin/assets-zip.html

Then you should be able to get the logs from the identity pod to get more information.

**Comment by nithin-bose** [comment]
@sym3tri tried that but i am getting a ``Unable to connect to the server: EOF``

**Comment by sym3tri** [comment]
Then it seems your API is not available. Assuming you're on AWS you may want to check your load balancers and ensure the health checks are ok. Make sure DNS of the API server ELB resolves etc

**Comment by nithin-bose** [comment]
Yes its on aws. The instance status is out of service

**Comment by nithin-bose** [comment]
The logs keeps showing ``pam_tally2(sshd:auth): Tally overflowed for user root``.

**Comment by nithin-bose** [comment]
Well it went from there to orphaned pods, scheduler pod going down, node connection errors ultimately the cluster and the deployed apps going down completely. Just reinstalled the cluster again. By the way this is the second time this is happening to me.

**Comment by sym3tri** [comment]
@nithin-bose sorry to hear that. What are the specs of the instances you're running, and how many master/worker nodes are you running? It's possible your cluster doesn't have enough resources to run the full control plane.

What version of Container Linux are you using? I'd recommend `stable`.

If the ELBs say "out of service" the next step would be to SSH into the nodes and check the logs for the `bootkube-start` unit to make sure it completed successfully.

**Comment by nithin-bose** [comment]
@sym3tri This was a running cluster when the issue occurred all of a sudden. I was using a t2.large as master and 3 t2.medium as workers. 

I was using the ``stable`` channel if that's what you mean.

**Comment by robszumski** [comment]
If this happens to you again, can you see if you are running out of storage?

**Comment by statik** [comment]
I'm running into the same symptoms as well, both ELBs showed the master as being out of service. I restarted the instance and the load balancer for port 10255 showed the instance as coming back in service, but the one for port 32000 is still showing as out of service. I can ssh into the instance and confirm that there is plenty of storage available. Any tips on how to try restarting the identity/web console pod or identify why it's not running?

**Comment by statik** [comment]
It looks like on may 5th the autoscaling group for AutoScaleController terminated an instance and started a new one. The ASG was set to a size of 1. Is there a way to recover at this point or do I need to rebuild the cluster?

**Comment by robszumski** [comment]
@statik You have a two options:

 - re-run bootkube
 - re-install the cluster

Basically what probably happened is that your API server went away when the autoscaler killed the node, and then when the new one came up it didn't have another API server to reschedule the other API server. This recovery would have worked automatically if you were running an HA control plane.

**Comment by statik** [comment]
@robszumski thank you! I'm going to rebuild, and not make that mistake again :) Telling all my friends to buy Tectonic as well

**Comment by robszumski** [comment]
Sounds good!

**Comment by JoshuaKolden** [comment]
I'm having this same problem.

The auto scaling group logs say that an instance was restarted:

```
Description:DescriptionTerminating EC2 instance: i-08a64...
--
Cause:CauseAt 2017-09-25T16:44:05Z an instance was taken out of service in response to a EC2 instance status checks failure.
```

Mind you this is all setup by tectonic.  I have nearly nothing to do with the configuration, so I'm very confused how tectonic is building the cluster that can be incapacitated so easily. I would hazard that no one whats this as their configuration, so it probably shouldn't be the default. 

@robszumski You mention something about an HA control plane, what are you referring to? Is there a reason why tectonic is not delivering a complete cluster?

I guess I just have to rebuild the cluster, but I can't be doing that every time AWS does an instance shuffle. So I'd appreciate any insights on a permanent fix.

**Comment by robszumski** [comment]
@JoshuaKolden The HA control plane is configured when you set the master count to anything other than 1. 3 is a good number. This is configurable to keep down the cost for smaller clusters.

**Comment by 1k2k** [comment]
@robszumski  thank you, would you kindly help me with this #297
