### ISSUE TITLE
How to upgrade an existing cluster?

### ISSUE THREAD

**Issue by rhenretta** [coreos/tectonic-forum#114]
### Tectonic Version 
1.5.6 / 1.5.7

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
Be able to upgrade cluster without recreating

### Actual Behavior
Had to destroy and rebuild cluster

### Reproduction Steps

  1. Set up cluster using tectonic installer for AWS
  2. Deploy

### Other Information
According to [this page](https://coreos.com/tectonic/docs/latest/admin/upgrade.html) I should see a Browse Cluster page and be able to check for updates.  I don't have this page.  It does mention that the automatic update feature must be enabled during installation, but I don't see the option.  I also can't find any documentation for doing a manual update, and had to resort to deleting the cluster and recreating to upgrade to 1.5.7.  This will force downtime when upgrading in production.

**Comment by robszumski** [comment]
@rhenretta Tectonic's automatic updates are still experimental, so the "enable experimental operators" checkbox needs to be selected during installation to enable them.

**Comment by rhenretta** [comment]
Where is the option?  I ran through the installation a couple times and never saw it.  Also, without it enabled, is there a suggested way to upgrade the cluster without fully replacing it?

**Comment by robszumski** [comment]
You should see it on the Cluster Info page:
![image](https://cloud.githubusercontent.com/assets/755540/25814341/05712d4a-33d2-11e7-8f58-7407ecbfc66e.png)

Using the operators is the recommended way to upgrade your cluster without replacing it.

**Comment by rhenretta** [comment]
gotcha, thanks.

**Comment by kersten** [comment]
@robszumski  Is it possible to enable this feature on a already running cluster?

**Comment by reignblack** [comment]
I too am also interested in the documentation for doing a manual update?

I have experimental features installed, currently I'm on 1.5.5.3 but it does not detect any newer versions, is this because update is only on the channel 1.5?

**Comment by robszumski** [comment]
@kersten No, it is not currently possible to install the operator on an existing cluster.

@reignblack If you are running `1.5.2-tectonic.2` you should be able to update to `1.5.7-tectonic.1`, which is the latest in the 1.5.x series of updates.

**Comment by kersten** [comment]
@robszumski did I get the newsletter yesterday right that auto upgrade won't install 1.6 channel if I'm on 1.5?

That would be really annoying.

**Comment by robszumski** [comment]
@kersten Yes, that is correct. We're tackling the issue methodically and working up to moving between major releases. For example, 1.5 to 1.6 changed from etcd v2 to v3 and the container execution to CRI. These types of drastic changes are difficult to get correct, but we're working on it.

**Comment by kersten** [comment]
@robszumski "we're working on it" sounds like that we get the update from 1.5 to 1.6 someday?

**Comment by robszumski** [comment]
@kersten Not for 1.5 to 1.6, but possibly for 1.6 to 1.7.

**Comment by kersten** [comment]
ok, that is very sad ...

**Comment by Szpadel** [comment]
It doesn't need to be fully automated upgrade, manual instruction would be enough for most of the users.
"Start again from scratch" isn't really enterprise solution.

**Comment by kersten** [comment]
@Szpadel "Start again from scratch" --- aboslutly

**Comment by abourget** [comment]
There used to be instructions somewhere about the order in which we need to update the `api-server`, then `kube-proxy`, etc... where's that ? I'm looking to upgrade from 1.5.5 to 1.5.7

**Comment by abourget** [comment]
Oh got it: https://github.com/kubernetes-incubator/bootkube/blob/master/Documentation/upgrading.md

**Comment by kersten** [comment]
Hi @robszumski,

some news about manual upgrading cluster from 1.5.x to 1.6? I don't want to restart with a whole new cluster.

**Comment by robszumski** [comment]
@kersten We are not pursuing 1.5 to 1.6 due to the complexity of swapping major API versions of etcd and major changes made to CNI.

We are still exploring how to do this for 1.6 to 1.7 based on how the 1.7 alpha/betas are progressing.

**Comment by robszumski** [comment]
Update: upgrading from 1.6.x to 1.7.x (and soon 1.8.x) is now supported across all platforms!

**Comment by kubebc** [comment]
I got an error upgrading from 1.7.1-tectonic.2 to 1.7.5-tectonic.1, any tips? Thanks!
![image](https://user-images.githubusercontent.com/32644310/31818865-8737cd6c-b5cc-11e7-8510-39220753a5b5.png)

**Comment by squat** [comment]
@kubebc can you start a new issue? This will probably require some digging and it's best to keep this resolved issue tidy.

**Comment by rushins** [comment]
@robszumski : Can you provide some steps or documentation of upgrade (ex: 1.7 to 1.8)  using tectonic console. ?  to me i just need to see if one click upgrade is true or not ? or i need to update some files prior to using running cluster tectonic console upgrade button ?

**Comment by robszumski** [comment]
Please make a new issue, but no, you don't have to do anything, it should work just fine.

**Comment by rushins** [comment]
Hi @robszumski : i think you need to give a fair answers.  For this request, you said "it should work just fine" but in real it doesnt work that simple as you said. Fist of all i need to check with you once thing. Have you tried in your LAB before answering to this question. 

To me it doesn't work from Tectonic Console -->  Cluster Settings --> Check for Updates ? results "up to date" but nothing goes beyond .

I am really sorry to write that such statements but please provide some proactive answers rather given ping-pong answers.

**Comment by rushins** [comment]
Did  anyone tried doing the tectonic console method for upgrade to 1.8 ,  i did manual upgrade and it worked but not from tectonic console "Tectonic Console --> Cluster Settings --> Check for Updates ? results "up to date" but nothing goes beyond .

@robszumski : do you have any info on my question.

**Comment by robszumski** [comment]
@rushins The 1.8 update will not be available until early next week. You can always check https://coreos.com/tectonic/releases/ for the available versions. Note that you'll need to be on `1.7.9-tectonic.3` before upgrading to `1.8.4-tectonic.1`. Check back next week!
