### ISSUE TITLE
SSL Certificate requires SAN for tectonic console

### ISSUE THREAD

**Issue by reignblack** [coreos/tectonic-forum#118]
### Tectonic Version
1.5.5.3 

### Environment

BareMetal

### Expected Behavior
Secure access to tectonic console

### Actual Behavior
Recently updated my google chrome browser to version 58. As a-part of this this update common name support has been removed. See https://www.thesslstore.com/blog/security-changes-in-chrome-58/

When trying to access the tectonic console, you will be blocked with The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address. NET::ERR_CERT_COMMON_NAME_INVALID

  1. Opening tectonic console in chrome 57, certificate valid and secure
  2. Updated to chrome 58
  3. Opening tectonic console in chrome 58, certificate is invalid

### Other Information
tectonic installation is configured to with my CA and not self-signed

## Feature Request
The SSL certificate that is generated for the console requires a SAN.

**Comment by colhom** [comment]
@reignblack good catch here!

I would recommend regenerating a new TLS certificate with a SAN and a randomly-generated common name.

To swap the new certificate in, you'll modify the `tectonic-tls-secret` secret. The ingress controller expects to find the TLS cert/key in this secret. One way you can do this is:

`EDITOR=your-favorite-editor kubectl -n tectonic-system edit tectonic-tls-secret`

Replace the contents certificate file with the new one. ( If you used a new private key, remember to replace that as well).

Now, you will need to have the ingress daemonset re-create all pods, so the new secret values propagate to the pods.

For Kubernetes v1.5, the way to do this is to simply delete all the existing daemonset pods.

```
kubectl -n tectonic-system delete pods  \
-l app=tectonic-lb \
-l component=ingress-controller \
-l type=nginx
```

Then, watch the new ingress pods appear and become ready, and you should have the tectonic console served with you new TLS certificate.

**Comment by robszumski** [comment]
Opened https://github.com/coreos/tectonic-installer/issues/656 to get this handled more gracefully in the Tectonic installer.

**Comment by robszumski** [comment]
Looks like this is fixed in the newer version of Tectonic. Test it out and let me know if it works for you. Plus, you get Kubernetes 1.6 :)

Relevant code: https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/crypto.tf#L22-L35
