### ISSUE TITLE
Installing tectonic for AWS - Not completing

### ISSUE THREAD

**Issue by tnkumar** [coreos/tectonic-forum#12]
### Tectonic Version 
tectonic 1.4.5

### Environment
Windows 7 Enterprise
Intel i5, 8 GB RAM, 64-bit

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9000263/21442762/99bd8d0a-c865-11e6-8534-2460e4dccb9b.png)
![image](https://cloud.githubusercontent.com/assets/9000263/21442781/c085d29e-c865-11e6-8221-3755988e3657.png)

### Reproduction Steps

  1. ...
  2. ...

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by mfburnett** [comment]
Hi @tnkumar, thanks for filing this issue! To help you troubleshoot, have you checked to make sure that you have the correct [privileges for your AWS credentials](https://tectonic.com/enterprise/docs/latest/install/aws/requirements.html)?

**Comment by tnkumar** [comment]
Yes @mfburnett . I am the root administrator for the AWS account. Any other suggestions?

**Comment by webner** [comment]
I had the same problem with the aws region eu-west-2. It seems that the regions are hard coded in kubernetes and [london will be added with version 1.5](https://github.com/kubernetes/kubernetes/pull/38746).

**Comment by naphthalene** [comment]
I ran into this problem, see #19 

You should be able to just scp the assets zip, explode it and run bootkube start. It appears to be waiting for the apiserver to start, but that's done by bootkube.

**Comment by dghubble** [comment]
It is not actually waiting for the Kubernetes control plane, it waits for the Kubelet to be running, as resolved behind the ELB. The messaging was wrong. You can connect to your EC2 instances and verify the kubelet service is running. If that's ok, check the ELB or local network restrictions. Skipping over the validation can mask other issues.

**Comment by Nourid5** [comment]
Hi ... I am trying to install tectonic on bare metal, however I don't know how and where to run the matchboxes and get the informations for the "matchbox address" panel. Thanks

**Comment by dghubble** [comment]
@Nourid5 this issue is about AWS. Please open a separate issue.

**Comment by mfburnett** [comment]
Hi @tnkumar, @naphthalene, and @webner - we recently released Tectonic v1.5.4-tectonic.1, which makes a bunch of improvements over Tectonic 1.4.5, including removing the scp step and adding HA by default for AWS (and bare metal). You can give it a try here to see if this resolves some of the issues you were having: https://coreos.com/tectonic/releases/

**Comment by mfburnett** [comment]
Going to close this issue due to inactivity. We recently released Tectonic v1.6.2-tectonic.1 with a ton of improvements - would recommend you all check it out! Feel free to open back up this issue with any comments or additional questions.
