### ISSUE TITLE
Tectonic On Baremetal

### ISSUE THREAD

**Issue by Selva03** [coreos/tectonic-forum#121]
### Tectonic Version 
1.6.2-tectonic.1

### Environment
baremetal/virtualbox VMs

### Expected Behavior
Trying to pxe boot controller node and provisioner node. But log file throw this error null_resource.kubeconfig.0: Still creating... (17m3s elapsed)

### Actual Behavior
Using docker image of coreos/dnsmasq for pxe booting controller and Worker node.
### Reproduction Steps

  1. Setup CentOS7 VM(Provisioner Node) and configured matchbox using docker image. 
  2. Downloaded CoreOS setup in provisioner node
  3. Network setting for pxe booting done by using docker image of coreos/dnsmasq(Run DHCP, TFTP, and DNS on the host's network and firewall is disabled). It is running in provisioner node.
  4. Started the tectonic installer from local desktop and waited for the installer to install kubernetes and tectonic console. Enabled network booting option in Controller and worker node and both node running in bridged adaptor mode.  
  5. Attached the  Terraform log for reference. 

### Other Information
Tectonic log file, pxe error screens and dnsmasq log
[log.txt](https://github.com/coreos/tectonic-forum/files/1001862/log.txt)

![pxeboot](https://cloud.githubusercontent.com/assets/26217276/26070604/d3be3e22-39c2-11e7-8410-532f7e600b29.png)
![worker_pxe](https://cloud.githubusercontent.com/assets/26217276/26070651/f7ffb0cc-39c2-11e7-85d2-b67e8acb2f34.png)

[dnsmasq-dhcp_log.txt](https://github.com/coreos/tectonic-forum/files/1001884/dnsmasq-dhcp_log.txt)

**Comment by robszumski** [comment]
@Quentin-M Can you take a look at this?

**Comment by Quentin-M** [comment]
Hey.

@dghubble is the one who hacked together the [CentOS provisioner VM](https://github.com/coreos/tectonic-installer/blob/4b732ffb2c2e9401610fd97c96d30acf75ebc336/Documentation/hack/centos-workers.md). This being said, it looks like your VMs cannot reach the network, so it'd definitely be a iPXE/DHCP setup issue. VirtualBox comes with an embedded DHCP server, can you make sure it is not enabled?

**Comment by dghubble** [comment]
@Quentin-M They setup a CentOS provisioner node to run matchbox and PXE services, which is perfectly well supported and reasonable. This isn't about experimetnal CentOS workers.

Yes, it looks like your Virtualbox network is not setup to reach your PXE-enabled DHCP server ala dnsmasq. You can journal the dnsmasq logs and see its not receiving requests.

**Comment by Selva03** [comment]
@Quentin-M @dghubble,
I am using bridged mode and disabled the DHCP server.

**Comment by Quentin-M** [comment]
Things are looking a little better now!

Could you please verify, using your browser, the content of
- http://matchbox.example.com:8080/boot.ipxe
- http://matchbox.example.com:8080/ipxe?uuid=fc779ad7-0c01-4c1f-a570-b501bf90c723&mac=08-00-27-bc-be-66&domain=&hostname=&serial=0

I believe that now, the issue is either: matchbox is not configured with the right MAC address (not specified properly in the Terraform configuration), or you are missing the CoreOS image in matchbox.

**Comment by Selva03** [comment]
@Quentin-M 
http://matchbox.example.com:8080/boot.ipxe

Response
#!ipxe
chain ipxe?uuid=${uuid}&mac=${mac:hexhyp}&domain=${domain}&hostname=${hostname}&serial=${serial}

http://matchbox.example.com:8080/ipxe?uuid=fc779ad7-0c01-4c1f-a570-b501bf90c723&mac=08-00-27-bc-be-66&domain=&hostname=&serial=0

Response
404 page not found

http://matchbox.example.com:8080/assets/coreos/1353.7.0/

![coreos_image](https://cloud.githubusercontent.com/assets/26217276/26122033/c1be11a8-3a93-11e7-85fe-8d8969694382.png)

**Comment by Selva03** [comment]
@Quentin-M @dghubble,
Is there any option to skip pxe boot. To add controller and worker node booted manually with coreos.iso and then proceed with the tectonic, kubernetes installation.

**Comment by Perdjesk** [comment]
@Selva03 Your iPXE boot is trying to reach for:
http://matchbox.example.com:8080/ipxe?uuid=fc779ad7-0c01-4c1f-a570-b501bf90c723&mac=08-00-27-bc-be-66&domain=&hostname=&serial=0

which gives a 404 meaning matchbox is not configured properly.
Either a typo in the MAC address in Tectonic installer or you restarted the matchbox container with losing its state.

The Tectonic installer appears to feed matchbox when pressing the "Submit" button. You might want to make sure to do this when you change MAC addresses or lose the state of matchbox.

**Comment by dghubble** [comment]
You have the Container Linux images and this isn't related to those assets.

Matchbox only returns iPXE/Ignition/etc configs to machines it is supposed to match. Receiving a 404 means there was no match. In the case of Tectonic, machines are matched by MAC address. Journal the logs to see if there is a complaint about a malformed object.

```
journalctl -u matchbox.service -f
```

You can view the raw set of objects representing machines that should be matched by inspecting.

```
cat /var/lib/matchbox/groups/* | grep "80:00:27:bc:be:66"
```

**Comment by robszumski** [comment]
Closing this out due to inactivity but please re-open as needed. Thank you for the help @dghubble and @Perdjesk
