### ISSUE TITLE
Using terraform v0.9.5 fails

### ISSUE THREAD

**Issue by bobhenkel** [coreos/tectonic-forum#122]
### Tectonic Version 
1.6.2-tectonic.1

### Environment
MacOS Sierra Version 10.12.4
terraform v0.9.5

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
#1 Following docs located here -> https://coreos.com/tectonic/docs/latest/install/aws/aws-terraform.html

#2 Run terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws

#3 Should show how many objects are going to be created(assuming brand new cluster)

### Actual Behavior
terraform plan fails
```
bash-3.2$ terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws
Error asking for user input: 2 error(s) occurred:

* module.vpc.var.worker_azs: At column 15, line 1: true and false expression types must match; have type string and type unknown in:

${ split("|", "${length(keys(var.tectonic_aws_worker_custom_subnets))}" > 0 ?
    join("|", keys(var.tectonic_aws_worker_custom_subnets)) :
    join("|", data.aws_availability_zones.azs.names)
  )}
* module.vpc.var.master_azs: At column 15, line 1: true and false expression types must match; have type string and type unknown in:

${ split("|", "${length(keys(var.tectonic_aws_master_custom_subnets))}" > 0 ?
    join("|", keys(var.tectonic_aws_master_custom_subnets)) :
    join("|", data.aws_availability_zones.azs.names)
  )}
```

### Other Information
If I downgrade terraform back to v0.9.4 it works.
You should call out the supported version of Terraform, Terraform is updated frequently and will cause issues like this often, I have scars.

**Comment by robszumski** [comment]
Hi @bobhenkel, you are right that only 0.9.4 is functional and tested at this point. And you are again right that it needs to be called out more explicitly. I opened https://github.com/coreos/tectonic-installer/issues/745 for tracking.

**Comment by robszumski** [comment]
Closing this and will track over there. Feel free to subscribe or re-open if needed.
