### ISSUE TITLE
tectonic-identity timing out and restarting

### ISSUE THREAD

**Issue by abh** [coreos/tectonic-forum#126]
### Tectonic Version 

1.6.2

### Environment

baremetal (under KVM)

### Actual Behavior

tectonic-identity regularly fails it's liveness probe and gets killed. It comes back okay, but it leaves a minute or two with no identity service (which makes API calls at least from the outside fail).

    May 22 05:35:49 hostname.tld kubelet-wrapper[1227]: E0522 05:35:49.708912    1227 event.go:259] Could not construct reference to: '&v1.ObjectReference{Kind:"Pod", Namespace:"tectonic-system", Name:"tectonic-identity-8985192-b01fw", UID:"81f17a3d-3eae-11e7-a91c-525400cdeea3", APIVersion:"v1", ResourceVersion:"9947062", FieldPath:"spec.containers{tectonic-identity}"}' due to: 'object does not implement the List interfaces'. Will not report event: 'Warning' 'Unhealthy' 'Liveness probe failed: Get http://10.2.2.26:5556/identity/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)'

**Comment by kbrwn** [comment]
@abh You might try increasing the `timeoutSeconds` parameter of the tectonic-identity deployment. 

$ kubectl -n tectonic-system edit deployment/tectonic-identity
  
```
timeoutSeconds: Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
```

k8s documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configuring-probes

**Comment by abh** [comment]
Thanks; I wasn't sure if that'd be appropriate. I try not fussing with anything in tectonic-system. :-) I changed it now. Would it be appropriate to run two replicas instead of just one, or would that cause other trouble?

**Comment by robszumski** [comment]
@abh Running more than one is totally safe and should now be the default. Some other performance tweaks have landed in https://github.com/coreos/tectonic-installer/pull/856, please re-open if you see this issue again after the next release.
