### ISSUE TITLE
Baremetal server doesn't boot with ipxe script

### ISSUE THREAD

**Issue by sanningr** [coreos/tectonic-forum#130]
### Tectonic Version 
Tectonic version 1.6.2

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

OVH Bare metal

### Expected Behavior

After completing tectonic configuration, the provisioning machine should start provisioning to master and worker nodes.

### Actual Behavior

Master and Worker node never request the matchbox machine. The ipxe script that i use is:

chain http://matchbox.premiumspace.gr:8080/boot.ipxe

I can see that no request has been made to matchbox:

time="2017-05-23T23:11:21Z" level=info msg="Starting matchbox gRPC server on 0.0.0.0:8081" 
time="2017-05-23T23:11:21Z" level=info msg="Using TLS server certificate: /etc/matchbox/server.crt" 
time="2017-05-23T23:11:21Z" level=info msg="Using TLS server key: /etc/matchbox/server.key" 
time="2017-05-23T23:11:21Z" level=info msg="Using CA certificate: /etc/matchbox/ca.crt to authenticate client certificates" 
time="2017-05-23T23:11:21Z" level=info msg="Starting matchbox HTTP server on 0.0.0.0:8080"

**Comment by dghubble** [comment]
A PXE-enabled network environment is responsible for chaining to the Matchbox iPXE entrypoint which is mentioned in [requirements](https://coreos.com/tectonic/docs/latest/install/bare-metal/requirements.html). Can you tell the team more about your network setup? Find docs on various ways to setup a suitable network environment [here](https://coreos.com/matchbox/docs/latest/network-setup.html).

**Comment by adarshaj** [comment]
I have same issue as the OP. I think OVH is actually not loading ipxe script at all. Is there anyway we can proceed with tectonic installation without the pre-req described in network environment? May be some steps like installing coreos can be done manually (following offline installation step of coreos -- directly to disk)? and once the servers have coreos stable up and running, terraform can somehow configure it further?

**Comment by adarshaj** [comment]
I was mistaken, the ipxe script was being loaded. However, there was some issue with chain loading. The solution I employed was to [set ipxe script on OVH server](https://github.com/gmasse/ovh-ipxe-customer-script#1-upload-your-custom-ipxe-script) to just
```
#!ipxe
shell
```
which drops to ipxe shell, where I manually typed in `chain http://matchbox.foo:8080/boot.ipxe` (on all the servers, using the ipmi console via kvm). 

After this point tectonic installer was able to proceed with terraform plan and apply steps.

**Comment by dghubble** [comment]
Seems like you've both been able to make the changes to your environment. Please re-open otherwise.
