### ISSUE TITLE
VPC peering not supported

### ISSUE THREAD

**Issue by bobhenkel** [coreos/tectonic-forum#135]
Docs here state VPC peering is not supported (https://coreos.com/tectonic/docs/latest/install/aws/troubleshooting.html)

But does this still hold true?  [https://github.com/kubernetes/kubernetes/commit/58191c446c76298b46904ac79914518e2489f94f](https://github.com/kubernetes/kubernetes/commit/58191c446c76298b46904ac79914518e2489f94f)

In addition your Terraform standup lets us set tectonic_service_cidr to what ever we want.

Thanks

**Comment by sym3tri** [comment]
@bobhenkel Thanks for raising this. That doc is out dated. I've filed an issue to fix it. Please follow up there if you have other specific concerns.

https://github.com/coreos/tectonic-installer/issues/897
