### ISSUE TITLE
Tectonic Web Console Not Showing HPA

### ISSUE THREAD

**Issue by bobhenkel** [coreos/tectonic-forum#137]
### Tectonic Version 
1.6.2-tectonic.1  Stable Channel

### Environment
What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS
### Expected Behavior
If you create a HPA with kubectl it should show up under the Tectonic Web Console under Workloads->Autoscalers

### Actual Behavior
When you click Workloads->Autoscalers you just get the ... if you have any HPA created.

### Reproduction Steps

  1. Go here https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  2. Follow steps 1, 2, and 3. 
  3. Verify you have a HPA up and running with kubectl get hpa.
  4.  Go to Tectonic Web Console and click Workloads->Autoscalers.
  5. You will see ... ... ... ...  and possibly fall into a trance.

P.S.
The falling into trance is made up, but the rest is spot on.

**Comment by robszumski** [comment]
Thanks for reporting this. Tracking this over on https://github.com/coreos/tectonic-installer/issues/861, but the summary is that HPAs are currently an alpha feature and we're going to remove this from the Console until the API stabilizes a bit.

**Comment by ayen-tibco** [comment]
+1
Please put HPA back in the web console for future tectonic 1.9.x release. Thanks.
