### ISSUE TITLE
etcd-operator fails to reach etcd members after restart

### ISSUE THREAD

**Issue by BdeUtra** [coreos/tectonic-forum#138]
### Tectonic Version 
1.6.2-tectonic.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
When an etcd-operator pod goes down the newly created one should be able to take over

### Actual Behavior
The newly created pod fails to update members. Logs from newly created etcd-operator below:
```
time="2017-05-31T17:17:12Z" level=info msg="etcd-operator Version: 0.2.5"
time="2017-05-31T17:17:12Z" level=info msg="Git SHA: e6c62c0"
time="2017-05-31T17:17:12Z" level=info msg="Go Version: go1.7.5"
time="2017-05-31T17:17:12Z" level=info msg="Go OS/Arch: linux/amd64"
time="2017-05-31T17:17:31Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-05-31T17:17:31Z" level=info msg="start running..." cluster-name=kube-etcd pkg=cluster
time="2017-05-31T17:17:31Z" level=info msg="starts running from watch version: 19236" pkg=controller
time="2017-05-31T17:17:31Z" level=info msg="start watching at 19236" pkg=controller
time="2017-05-31T17:17:44Z" level=error msg="failed to update members: grpc: timed out when dialing" cluster-name=kube-etcd pkg=cluster
time="2017-05-31T17:17:57Z" level=error msg="failed to update members: grpc: timed out when dialing" cluster-name=kube-etcd pkg=cluster
time="2017-05-31T17:18:10Z" level=error msg="failed to update members: grpc: timed out when dialing" cluster-name=kube-etcd pkg=cluster
time="2017-05-31T17:18:23Z" level=error msg="failed to update members: grpc: timed out when dialing" cluster-name=kube-etcd pkg=cluster

...
```

### Reproduction Steps

  1. Build new cluster using terraform with self-hosted etcd
  2. Wait for the cluster to become stable
  3. Delete etcd-operator pod
  4. Observe logs of newly created etcd-operator pod

**Comment by xiang90** [comment]
I suspect this is due to reschedule of etcd operator from the master node to a worker node. Worker node does not have access to master nodes, thus no access to etcd pods running on them anymore. We already fixed this by adding node selector to etcd operator pod. The next release of tectonic should fix this issue I believe.

**Comment by BdeUtra** [comment]
Thanks @xiang90 adding NodeSelector to the etcd-operator solved it (the toleration was already there).

When debugging this issue I've noticed that some control plane pods have PodIPs on the VPC CIDR instead of the Pods CIDR? Is there anywhere you can point me to understand the reasoning?

**Comment by xiang90** [comment]
> When debugging this issue I've noticed that some control plane pods have PodIPs on the VPC CIDR instead of the Pods CIDR? Is there anywhere you can point me to understand the reasoning?

Can you create a new issue for this? We want to keep one issue for one problem (better search and discovery). So I am going to close this one.
