### ISSUE TITLE
sshd handshake Baremetal Installer

### ISSUE THREAD

**Issue by reignblack** [coreos/tectonic-forum#139]
## Issue Report Template
So after finally getting good deployment process for our production 1.5, I decided to update to 1.6, which has now put me back to beginning trying to figure this all out again :)

### Tectonic Version 
1.6.2.1
### Environment
Bare Metal
What hardware/cloud provider/hypervisor is being used with Tectonic?
Both tried on Bare Metal and VMs
### Expected Behavior
Installation to complete
### Actual Behavior
Installation times out after 60mins

Terraform error:
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain * null_resource.kubeconfig[1]: 1 error(s) occurred

### Reproduction Steps

VLAN Subet 10.96.104.0/24
1 Provisioner Node – 10.96.104.10 – Running DHCP, Matchbox and Tectonic Installer via gui
1 Controller – 10.96.104.20 received from DHCP, DNS entry server-9001.example.com
1 Node – 10.96.104.22 received from DHCP, DNS entry server-9002.example.com

Followed baremetal documentation and setup matchbox and pxe boot, only difference is I didnt use the coreos dns/dhcp and used my own

Run Tectonic Installer 1.6.2.1

--Cluster Name – kube-a
--Controller DNS – kube-a.example.com – DNS record to 104.20
--Tectonic DNS – tectonic-a.example.com – DNS record to 104.22
---Certificates – Internal CA provided
--Matchbox Server – matchbox.example.com:8080/8081 – DNS record to 10.96.104.10
--Pod Range - 172.16.0.0/16
--Service Range – 172.30.0.0/24
--Etcd – Launch/install etcd for me
--I submitted the job, and then edited the worker and controller yaml files to include my proxy settings.
Power on Cluster
--Controller – Gets IP from DHCP, loads PXE boot and installs OS
--Node – Gets IP from DHCP, loads PXE boot and installs OS
--Both servers boot and then reboot, I leave them for a while.

Eventually times out with error on the installer:
`* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain * null_resource.kubeconfig[1]: 1 error(s) occurred`

I can log into both the controller and worker node and by running journalctl can see the the following retried over and over again, which is between master/node and the matchbox/installer server:

```
The start-up result is done.
Jun 01 13:18:21 kube9001.example.co.uk sshd[5891]: Connection closed by 10.96.104.10 port 60616 [preauth]
Jun 01 13:18:24 kube9001.example.co.uk systemd[1]: Started OpenSSH per-connection server daemon (10.96.104.10:60620).
-- Subject: Unit sshd@1111-10.96.104.20:22-10.96.104.10:60620.service has finished start-up
```

### Other Information
I am using coreos stable 1353.7.0, no firewalls are enabled.

I also added the /etc/kubernetes/kubelet.env with the required info in the yaml file for the worker node. I was getting issues with the kubelet-env.service not working with docker throwing veth NIC disabled errors....no idea why tbh

I'm not sure exactly where I am in the deployment process, i.e what is occurring at this sshd stage? So any help in troubleshooting would be grateful.

**Comment by reignblack** [comment]
Sorry didn't know it was already posted in the other forum:

https://github.com/coreos/tectonic-installer/issues/537

Prior to running  the submitted the job, I had to ensure ssh-agent was running and added my key. 

Not sure if this a requirement of the installer, but should be added to documentation, but looks like its being dealt with the other issue logged, so this can probably be closed.

**Comment by robszumski** [comment]
Thanks for following up. Let's track in that installer issue and the actual docs update in https://github.com/coreos/tectonic-installer/issues/1078
