### ISSUE TITLE
Installed with GUI, gets two errors running Terraform after saving assets

### ISSUE THREAD

**Issue by pgburt** [coreos/tectonic-forum#140]
User reports two errors Terraform on our mailing list: [https://groups.google.com/forum/#!topic/coreos-user/iA_giU8tc3k](https://groups.google.com/forum/#!topic/coreos-user/iA_giU8tc3k).

```
Running terraform plan -var-file=terraform.tfvars ../../../platforms/aws gives me:
2 error(s) occurred:
* module.vpc.aws_subnet.master_subnet: 2 error(s) occurred:
```

**Comment by PerWiklander** [comment]
Full error:

```
2 error(s) occurred:

* module.vpc.aws_subnet.master_subnet: 2 error(s) occurred:

* module.vpc.aws_subnet.master_subnet[2]: index 2 out of range for list var.master_azs (max 1) in:

${var.master_azs[count.index]}
* module.vpc.aws_subnet.master_subnet[1]: index 1 out of range for list var.master_azs (max 1) in:

${var.master_azs[count.index]}
* module.vpc.aws_subnet.worker_subnet: 2 error(s) occurred:

* module.vpc.aws_subnet.worker_subnet[2]: index 2 out of range for list var.worker_azs (max 1) in:

${var.worker_azs[count.index]}
* module.vpc.aws_subnet.worker_subnet[1]: index 1 out of range for list var.worker_azs (max 1) in:

${var.worker_azs[count.index]}
```

I used the default values in the setup, so 1 AZ, 1 master, 1 worker, 1 etcd.

**Comment by jganoff** [comment]
I've also ran into this issue using the 1.6.2 installer. I created a simple cluster with 3 masters and 2 workers on AWS. The cluster provisioned successfully through the Tectonic Installer; however, unpacking the asset archive running the following commands yields the same error:

```
terraform get platforms/aws
terraform plan -var-file=terraform.tfvars platforms/aws
```

**Comment by robszumski** [comment]
What region are you deploying these into? Can you describe the outcome of the AZs that you would like to see used?

**Comment by PerWiklander** [comment]
I was deploying in eu-west-1.  As I said, this is with the Terraform resources generated by a default install with the GUI. I would just like the exported resources to work, so that I can run a "terraform destroy" or start modifying my setup. I would have assumed that the GUI used Terraform as well, so I don't understand why it fails later.

**Comment by robszumski** [comment]
@PerWiklander @jganoff Can you confirm that you're using our patched Terraform binary? `which terraform`?

We're working to fix these bugs upstream but have to use a patched binary until we can get it merged.

**Comment by PerWiklander** [comment]
Uhm, I use the Terraform binary (0.9.6) that was installed when running `brew install terraform`. Where can I find your patched version?

**Comment by robszumski** [comment]
@PerWiklander it is included in the [installer download](https://releases.tectonic.com/tectonic-1.6.4-tectonic.1.tar.gz) at `/tectonic-installer/$PLATFORM/terraform`

**Comment by jganoff** [comment]
@robszumski I was not using your patched terraform binary. I must have missed that requirement.

```
$ which terraform
/usr/local/bin/terraform

$ terraform -version
Terraform v0.9.6
```

**Comment by robszumski** [comment]
Can you confirm that using that binary files the issue on your end?

**Comment by PerWiklander** [comment]
Using the correct binary (as the docs try to tell me I should, duh!) solved the problem.

**Comment by robszumski** [comment]
Glad to hear it :) We're working really hard to get the changes made upstream. I'm going to close this, but happy to re-open if needed.
