### ISSUE TITLE
Terraform apply failure - tectonic 1.6.2

### ISSUE THREAD

**Issue by mch1307** [coreos/tectonic-forum#145]
### Tectonic Version 
1.6.2
### Environment
Trying to setup a 1 master 2 workers tectonic cluster on 3 VM (Esx6.5)
All iPXE setup done with matchbox. Nodes are booted and ssh connection to nodes OK from installer workstation without password. Launched installer from linux desktop.

CoreOs 1353.7.0 installed on nodes
Installer stops with:
```
null_resource.bootstrap: Still creating... (20m50s elapsed)
null_resource.bootstrap (remote-exec): A dependency job for tectonic.service failed. See 'journalctl -xe' for details.
Error applying plan:
1 error(s) occurred:
* null_resource.bootstrap: 1 error(s) occurred:
* Script exited with non-zero exit status: 1
```

Unit bootkube.service failed on master

Master and worker journalctl: [jnlctl-logs.zip](https://github.com/coreos/tectonic-forum/files/1063087/jnlctl-logs.zip)

Master node has following containers running:
  kube-controller-manager_bootstrap-kube-controller-manager
  etcd_bootstrap-etcd
  kube-scheduler_bootstrap-kube-scheduler
  kube-apiserver_bootstrap-kube-apiserver

Worker nodes have no container running, only the kube-version image

### Expected Behavior
 all containers setup and running on master and worker nodes
 Tectonic console started

### Actual Behavior
  installation not complete
### Reproduction Steps
  Run installer on linux, choose bare metal
  Fill out setup info, apply and boot nodes

**Comment by mch1307** [comment]
After having reapplied several time and finally restart from scratch I found my problem. It was my mistake, I put one of the worker dns name in the master dns field...

**Comment by AnkushKN** [comment]
I am too having the same problem, verified the inputs as in your case but everything looks fine.
logs:
null_resource.kubeconfig.1: Creation complete
null_resource.bootstrap: Creating...
null_resource.bootstrap: Provisioning with 'file'...
null_resource.bootstrap: Provisioning with 'remote-exec'...
null_resource.bootstrap (remote-exec): Connecting to remote host via SSH...
null_resource.bootstrap (remote-exec):   Host: controller
null_resource.bootstrap (remote-exec):   User: core
null_resource.bootstrap (remote-exec):   Password: false
null_resource.bootstrap (remote-exec):   Private key: false
null_resource.bootstrap (remote-exec):   SSH Agent: true
null_resource.bootstrap (remote-exec): Connected!
null_resource.bootstrap: Still creating... (10s elapsed)
null_resource.bootstrap: Still creating... (20s elapsed)
null_resource.bootstrap: Still creating... (30s elapsed)
.
.
.
null_resource.bootstrap: Still creating... (19m50s elapsed)
null_resource.bootstrap: Still creating... (20m0s elapsed)
null_resource.bootstrap (remote-exec): A dependency job for tectonic.service failed. See 'journalctl -xe' for details.
Error applying plan:

1 error(s) occurred:

* null_resource.bootstrap: 1 error(s) occurred:

* Script exited with non-zero exit status: 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

is their any solution for this?

**Comment by mch1307** [comment]
As instructed, try to issue "journalctl -xe" one the target host (master and worker). It should help identifying where the issue could come from

**Comment by AnkushKN** [comment]
In master it says that bootkube.service failed with error status "API server is not ready: timed out waiting for the condition"
anything on this?

**Comment by squat** [comment]
@AnkushKN This is an issue with the experimental etcd operator pivoting from the bootstrap etcd to the self-hosted etcd cluster. It is hard to say what @mch1307 original issue was, but it seems to be unrelated. Please keep in mind that the self-hosted etcd flavor of Twctonic configuration is still very much alpha. Maybe @hongchaodeng can offer more insight. Please file a new issue if you would like to track this.

**Comment by mch1307** [comment]
My issue was for sure due to my mistake while filling out the wizard (worker hostname instead of the master one). I had no further issue with self-hosted etcd.
