### ISSUE TITLE
Unable to SSH in machine (AWS)

### ISSUE THREAD

**Issue by uberstudio** [coreos/tectonic-forum#148]
### Tectonic Version 
Tried & reproduced with 1.6.2 - 1.6.4

### Environment
AWS

### Expected Behavior
Should be able to SSH into master nodes with PEM file specified during installation

### Actual Behavior
Although using the same private key specified in the installer, trying to SSH in results in a password prompt. I'm trying to SSH with the user "core".

### Reproduction Steps

  1. Create assets file using installer
  2. Run 'terraform apply ...'
  3. The instance appears in EC2 as expected, with the correct key
  4. ssh -i {MY_KEY} core@{MASTER_NODE_IP} results in a password prompt

### Other Information
Is it possible that the instance is started with a different username than 'core'?

Thanks!

**Comment by robszumski** [comment]
Nothing should have changed regarding the SSH username. Does `ssh -v` show anything odd, like permissions issues on the key?

**Comment by uberstudio** [comment]
This turned out to be an AWS issue with my key.
