### ISSUE TITLE
Tectonic Stuck at "Starting Tectonic Console"

### ISSUE THREAD

**Issue by ingshtrom** [coreos/tectonic-forum#151]
### Tectonic Version 
1.6.4
### Environment
running on mac OS 10.12.5

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
It completes and then I can access my k8s cluster

### Actual Behavior
The UI shows that Terraform ran successfully (I verify that via AWS console) and that the DNS records resolved correctly, but "Starting Tectonic Console" never finishes.

### Reproduction Steps

  1. For me, it happens every time I use the Tectonic for AWS GUI installer

### Other Information
I'm choosing: 
- 3 master nodes at m4.xlarge
- 3 worker nodes at m4.large
- 3 etcd nodes at m4.large

I ran `etcdctl health-check` from one of the k8s master nodes and it returned that the etcd cluster was healthy.

There were a lot of errors in journalctl saying various things like "Unable to update cni config: No networks found in /etc/kubernetes/cni/net.d" and "Cannot list <insert_k8s_resource_here>". I'm not sure how else to debug the cluster at this point.

**Comment by ingshtrom** [comment]
I just realized that the difference between now and before when it worked was that I provided my own certs. I'm trying with generated certs by tectonic-installer to see if that fixes the problem.

The crt and key's I was using were the ones we usually plug into Nginx in our old infrastructure. I'm not sure why those wouldnt work

**Comment by ingshtrom** [comment]
huzza! it works with the auto-generated certs. Not sure why the ones I provided didn't work. Is there any way to verify them ahead of time?

**Comment by robszumski** [comment]
@ingshtrom Great, glad you got it up and running. The cert for the API server needs to have the following SANs:

- The common name used to address the api server, aka `tectonic_cluster_name` + `tectonic_base_domain`(what is mapped to the ELB)
- `kubernetes` 
- `kubernetes.default`
- `kubernetes.default.svc`
- `kubernetes.default.svc.cluster.local`
- the first IP in the service CIDR range

Let me know if that works for you.

**Comment by robszumski** [comment]
Related, is PR https://github.com/coreos/tectonic-installer/pull/1036 which better abstracts out the different certificates we are using within the cluster
