### ISSUE TITLE
Private subnets are not recognised

### ISSUE THREAD

**Issue by bitdivine** [coreos/tectonic-forum#155]
### Tectonic Version 
1.6.4

### Environment
AWS

### Expected Behavior
I am using the graphical installer and wish to use an existing VPC with a number of pre-existing private subnets.

### Actual Behavior
The dropdowns for Master and Worker subnets are blued out with a message of:

  vpc-XXX has no private subnets. Please create some using the AWS console.

### Reproduction Steps

It is obviously something to do with this VPC in particular but I doubt it is a good idea to publish the details so this is a bit difficult.  For other VPCs the private subnets are identified correctly.  Here the private subnets have a nat gateway and relatively long route table.  It might help if you could publish the steps you take to identify private subnets - please do! :-)  I have had a look and I don't see the method but it is probably somewhere.

**Comment by bitdivine** [comment]
Issue resolved.  I noticed that the route table on the subnet was inherited from the VPC.  I associated the route table explicitly and that part was happy.  I then ran into another problem but that is another issue!

**Comment by haimari** [comment]
Same issue here... associating the private subnet with the private route does not solve it for me

**Comment by haimari** [comment]
I read here and found my issue.
private route should have VPG or Nat GW once added it works, so these is no issue here, just RTM
