### ISSUE TITLE
Only one controller node allowed with installer?

### ISSUE THREAD

**Issue by abh** [coreos/tectonic-forum#16]
### Tectonic Version 

1.4.7

### Environment

Libvirt (bare metal installer for bootcfg).

### Expected Behavior

The installer has a dropdown for number of controller nodes, but "1" is the only choice given.

**Comment by rothgar** [comment]
I was going to open a ticket for this same issue. You beat me to it.

**Comment by sym3tri** [comment]
Yes this is a limitation of the installer currently. We are working on multi-controller, which will be coming soon.

**Comment by mfburnett** [comment]
hey @abh - thanks for filing this issue. Tracking HA questions in #6, so will close this thread.

**Comment by rushins** [comment]
hello i get the same issue using 1.6 tectonic where i cannot install multiple controllers ? is this bug fixed or still have it ?
i filed this new case ?

**Comment by rushins** [comment]
I am doing test with 3 Masters (controllers) and 3 workers deployment with tectonic 1.63 and installation failing with API server ? we are using 10 Node free license . Is there any limitation that only one MASTER (Controller) supported ? I tried with 1 master and 5 workers, it worked like charm but 3 masters and 3 worker always failing. 
 
Can you just through some information why this is failing. 
 
I get this error. 
 
have you seen this error?? sudo tail -300 bootstrap-kube-apiserver-ld4601.wdf.sap.corp_kube-system_kube-apiserver-8c7933423beaba4d7035b90aee734b7f5369e05aabbb563a6df4b860ca1e517d.log 
{"log":"Error: error waiting for etcd connection: timed out waiting for the condition\n","stream":"stderr","time":"2017-08-24T19:24:43.141656508Z"} 
{"log":"Error: error waiting for etcd connection: timed out waiting for the condition\n","stream":"stderr","time":"2017-08-24T19:24:43.14171726Z"}

**Comment by rushins** [comment]
hello sym3tri
I am doing test with 3 Masters (controllers) and 3 workers deployment with tectonic 1.63 and installation failing with API server ? we are using 10 Node free license . Is there any limitation that only one MASTER (Controller) supported ? I tried with 1 master and 5 workers, it worked like charm but 3 masters and 3 worker always failing.

Can you just through some information why this is failing.

I get this error.

have you seen this error?? sudo tail -300 bootstrap-kube-apiserver-ld4601.wdf.sap.corp_kube-system_kube-apiserver-8c7933423beaba4d7035b90aee734b7f5369e05aabbb563a6df4b860ca1e517d.log
{"log":"Error: error waiting for etcd connection: timed out waiting for the condition\n","stream":"stderr","time":"2017-08-24T19:24:43.141656508Z"}
{"log":"Error: error waiting for etcd connection: timed out waiting for the condition\n","stream":"stderr","time":"2017-08-24T19:24:43.14171726Z"}

any clue what;s wrong. checking ETCD cluster seems to be trouble as multi master ETCD is not talking each other nodes ..any firewall issue could be like 2379 ports between multiple masters ?

**Comment by rushins** [comment]
hello 

does anyone have 3 controller (masters) environment and have no issues running ? i still have the same problem with 3 controllers and 3 workers ...API keeps crashing.
