### ISSUE TITLE
HSTS Error trying to access Tectonic UI for first time

### ISSUE THREAD

**Issue by philchristensen** [coreos/tectonic-forum#163]
### Tectonic Version 
1.6.7-tectonic.1-rc.4

### Environment
What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS, existing VPC that meets requirements

### Expected Behavior
Chrome should warn about the invalid cert, but not reject access to Tectonic dashboard.

### Actual Behavior
Chrome raises an HSTS error and won't let me through.

### Other Information
Everything seems to be working otherwise, and all the appropriate AWS resources were created.

cURL output:
```
beefheart:~ $ curl --head -k https://stage.aws.logicworks.net/
HTTP/1.1 200 OK
Server: nginx/1.13.1
Date: Wed, 12 Jul 2017 16:58:17 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains;
```

Partial OpenSSL s_connect output:
```
beefheart:~ $ openssl s_client -connect stage.aws.logicworks.net:443
CONNECTED(00000003)
depth=0 /C=/ST=/L=/postalCode=/O=/OU=/CN=stage.aws.logicworks.net
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /C=/ST=/L=/postalCode=/O=/OU=/CN=stage.aws.logicworks.net
verify error:num=27:certificate not trusted
verify return:1
depth=0 /C=/ST=/L=/postalCode=/O=/OU=/CN=stage.aws.logicworks.net
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/C=/ST=/L=/postalCode=/O=/OU=/CN=stage.aws.logicworks.net
   i:/C=/ST=/L=/postalCode=/O=bootkube/OU=/CN=kube-ca
---
```

I'm not 100% sure on how HSTS works, but this looks like it should be okay. I'd expect an error about the unknown issuer, but I'm being entirely rejected.

**Comment by robszumski** [comment]
I see this happen on my cluster because the root domain is protected by HSTS.

```
$ curl -s -D- https://robszumski.com/ | grep -i Strict
Strict-Transport-Security: max-age=15724800; includeSubDomains; preload
```
What I have to do is trust the CA.crt generated by the installer in my operating system.

However, yours doesn't look like it is currently, but maybe was in the past, and Chrome remembered?

```
$ curl -s -D- https://logicworks.net/ | grep -i Strict
```

**Comment by philchristensen** [comment]
Thank you, that was exactly it. `aws.logicworks.net` got added to my HSTS cache in Chrome at some point, which I removed with the [instructions here](http://classically.me/blogs/how-clear-hsts-settings-major-browsers).
