### ISSUE TITLE
Excessive MountVolume.SetUp succeeded for volume "kubernetes.io/secret/..."

### ISSUE THREAD

**Issue by abh** [coreos/tectonic-forum#166]
### Tectonic Version 

1.6.7

### Environment

"Bare metal" on KVM

### Expected Behavior

Less logs.

### Actual Behavior

More logs.

### Reproduction Steps

I setup aggregated logging through fluentd and each day I get millions of entries like

    I0717 04:50:47.718073     715 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/c8e41391-6727-11e7-bc7a-525400f93bbc-default-token-jdzwk" (spec.Name: "default-token-jdzwk") pod "c8e41391-6727-11e7-bc7a-525400f93bbc" (UID: "c8e41391-6727-11e7-bc7a-525400f93bbc").

This particular pod is one of the linux container update pods. Why is the "MountVolume.SetUp" done every few seconds (or some such)?

**Comment by robszumski** [comment]
cc: @euank @dghubble

**Comment by euank** [comment]
This is operating as intended by upstream. The kubelet will constantly poll a volume to see if it should be remounted. The code that answers "should this be remounted" for a secret is here: https://github.com/kubernetes/kubernetes/blob/v1.6.7/pkg/volume/secret/secret.go#L84-L86

As you can see, it will remount it as often as possible.

Upstream has "fixed" this by reducing this message to [debug](https://github.com/kubernetes/kubernetes/pull/46367) level in v1.7.0

**Comment by abh** [comment]
@euank that's great news. :-) Maybe the same for the "node update" messages?
