### ISSUE TITLE
Cannot add additional nodes to cluster after initial provisioning

### ISSUE THREAD

**Issue by rothgar** [coreos/tectonic-forum#17]
### Tectonic Version 
1.4.7-tectonic.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
Bare Metal

### Expected Behavior
Able to add additional nodes to the cluster after initial provisioning

### Actual Behavior
I cannot find a way to add additional nodes to the cluster unless I either manually add the files to the bootcfg server or re-run the tectonic installer (thus wiping the existing cluster). The installer said I would be able to add more nodes after initial provisioning but I cannot find where/how to do that.

### Reproduction Steps

  1. Provision cluster with 2 nodes
  2. Attempt to add a 3rd node to the cluster

**Comment by kbrwn** [comment]
To add an additional node to a existing Tectonic cluster you need to copy two files in `/var/lib/bootcfg/groups/` directory on the provisioner machine and update the mac address to reflect the node you wish to join the cluster.   

```
$ ls /var/lib/bootcfg/groups/
tectonic-install-00-25-90-fd-76-40.json
tectonic-install-00-25-90-fd-78-0a.json
tectonic-node-00-25-90-fd-76-40.json
tectonic-node-00-25-90-fd-78-0a.json
```

The first file begins with `tectonic-install`. You should only need to change the `"mac"` parameter but you may wish to update the `"id"` to reflect the new mac as well:

```
$ cat /var/lib/bootcfg/groups/tectonic-install-00-25-90-fd-76-40.json 
{
	"id": "tectonic-install-00-25-90-fd-76-40",
	"name": "CoreOS Install",
	"profile": "install-reboot",
	"selector": {
		"mac": "00:25:90:fd:76:40"
	},
[...]
```

The second file begins with `tectonic-node-`. You need to update the `"mac"` and `"domain_name"` parameters to reflect the additional nodes designated metadata. 
 
```
$ cat /var/lib/bootcfg/groups/tectonic-node-00-25-90-fd-74-ce.json
{
	"id": "tectonic-node-00-25-90-fd-74-ce",
	"profile": "tectonic-worker",
	"selector": {
		"mac": "00:25:90:fd:74:ce",
		"os": "installed"
	},
	"metadata": {
		"domain_name": "lan-lab-02.lab.libcore.so",
		"etcd_initial_cluster": "node0=http://lan-lab-01.lab.libcore.so:2380",
[...]
```

After these two files are in place PXE boot the node with bootcfg and it should join the cluster.

**Comment by rothgar** [comment]
Thanks, that is what I did. I thought there would be a way to add nodes through the gui. Is that a future planned enhancement?

**Comment by dghubble** [comment]
In the future, there may be a GUI flow that helps create these worker configs.

**Comment by mfburnett** [comment]
@rothgar thanks for bringing up this issue. I've passed this along to the docs team, who will make sure to document how to do this.

**Comment by mfburnett** [comment]
@rothgar following up here, docs on scaling worker nodes for bare metal are public: https://coreos.com/tectonic/docs/latest/admin/bare-metal-scale.html. Closing this issue.
