### ISSUE TITLE
Failed to start Determine the Kubelet Image Version

### ISSUE THREAD

**Issue by tlarmier** [coreos/tectonic-forum#178]
### Tectonic Version 
1.7.1-tectonic.2.

### CoreOS Version 
1465.6.0

### MatchBox Version 
0.6.1

### Environment
Bare Metal , 1 master, 1 worker

hardware: Dell Desktop for test

### Expected Behavior
Finish the installation process of tectonic installer

### Actual Behavior
Install Failed on bootstrapping state (see log file below)
_null_resource.bootstrap: Still creating... (20m10s elapsed) 
null_resource.bootstrap (remote-exec): A dependency job for tectonic.service failed. See 'journalctl -xe' for details. 
Error applying plan: 1 error(s) occurred: * null_resource.bootstrap: 1 error(s) occurred: * Script exited with non-zero exit status: 1_

### Reproduction Steps

  1. Start tectonic Installer
  2. Configure and submit
  3. Boot master on network (Pxe) OK
  4. Reboot of master OK
  5 Master connected
  6 Boot Worker on network
  7 Reboot of worker OK
  8 Worker connected
  9 After 20 min Installer failed

### Other Information
After Ssh connect to worker and master we saw 'journalctl -xe' (see journalworker.txt and journalmaster.txt)

On worker we saw : "**Failed to start Determine the Kubelet Image Version**"

#### Log File from tectonic

[tectonic-sodicluster01.txt](https://github.com/coreos/tectonic-forum/files/1242169/tectonic-sodicluster01.txt)

#### Log File from worker 
[journalworker.txt](https://github.com/coreos/tectonic-forum/files/1242208/journalworker.txt)

### Log File from master

[journalmaster.txt](https://github.com/coreos/tectonic-forum/files/1242219/journalmaster.txt)

**Comment by lucab** [comment]
What does `sudo journalctl -e -u bootkube` says on master?

**Comment by tlarmier** [comment]
Thanks for answer so quickly... See result and file attached.
```
ug 22 13:19:47 master01.sodifrance.fr bash[1349]: [ 1500.807584] bootkube[5]: Error: API Server is not ready: timed out waiting for the con
Aug 22 13:19:47 master01.sodifrance.fr bash[1349]: [ 1500.808138] bootkube[5]: API Server is not ready: timed out waiting for the condition
Aug 22 13:19:47 master01.sodifrance.fr systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Aug 22 13:19:47 master01.sodifrance.fr systemd[1]: Failed to start Bootstrap a Kubernetes cluster.
Aug 22 13:19:47 master01.sodifrance.fr systemd[1]: bootkube.service: Unit entered failed state.
Aug 22 13:19:47 master01.sodifrance.fr systemd[1]: bootkube.service: Failed with result 'exit-code'.
```
[journbootkub.txt](https://github.com/coreos/tectonic-forum/files/1242354/journbootkub.txt)

**Comment by lucab** [comment]
From a quick look, it looks like bootstrapping the control plane on master is failing. However I don't  see any specific failure entry in the log, just generic connection failures on both master and worker.

The suspicious part is that the kubelet seems to detect the assets for the bootstrapping control plane and creating the pods, but never progressing from there. I'm not sure what could be causing this behavior. Did the docker/containerd by chance get stuck or killed while trying to execute those pods?

**Comment by squat** [comment]
It actually doesn't look like the kubelet starts any pods at all. The service successfully downloads the bootkube container and runs bootkube start, but nothing ever happens after that. It could be that the kubelet is erroring or dead and unable to start any of the bootstrap control plane pods. Could you post the output of `sudo journalctl -eu kubelet`?

**Comment by squat** [comment]
@tlarmier could you post your tfvars file? That would be helpful for debugging.

**Comment by tlarmier** [comment]
[terraform.tfvars.txt](https://github.com/coreos/tectonic-forum/files/1244533/terraform.tfvars.txt)

thanks

**Comment by tlarmier** [comment]
We found on the master log multiple acces to this adress:
Get https://masterkbn.sodifrance.fr:443 
This machine masterkbn.sodifrance.fr is our matcbox server ...
We havent no 443 port open on this machine, in https we use only the 8081 standart port for matchbox...
The question is what master and worker expect to found on this address ???
please help !!!

**Comment by lucab** [comment]
@tlarmier it expect the k8s api-server to show up there. Going through your tfvars, it looks like you may have a misconfigured entry pointing `tectonic_metal_controller_domain` to it.

**Comment by tlarmier** [comment]
We made a mistake on DNS Name declaration during configuration for workers and controllers....
It's OK Now.
Thanks for help.
