### ISSUE TITLE
Resolving subdomain DNS does not do anything

### ISSUE THREAD

**Issue by sichvoge** [coreos/tectonic-forum#181]
### Tectonic Version 

`1.7.1-tectonic.2` -> although somehow the installer still shows me `1.7.1-tectonic.1`

![image](https://user-images.githubusercontent.com/498114/29752385-d01a39c2-8b54-11e7-8117-2fd89bec23dc.png)

### Environment

AWS

What hardware/cloud provider/hypervisor is being used with Tectonic?

AWS vanilla install with all defaults

### Expected Behavior

Working Cluster Console

### Actual Behavior

I got till the end and the terraform apply process was successful. Now "resolving ..." is pending forever.

![image](https://user-images.githubusercontent.com/498114/29752404-2caa41a0-8b55-11e7-8d29-3734a951b329.png)

There is no log output or error message dialog.

### Reproduction Steps

1. Start browser based AWS install
2. Filled in all information and got to the end of the installation.
3. Wait.

**Comment by kbrwn** [comment]
To debug further, you could investigate the logs of the bootkube.service and  kubelet.service systemd units.

**Comment by sichvoge** [comment]
It was working after using another domain. Not sure why. I'll close this for now
