### ISSUE TITLE
Reboot loop with dsnmasq

### ISSUE THREAD

**Issue by sgrund42** [coreos/tectonic-forum#182]
### Tectonic Version 
1.7.1-tectonic.1

### Environment
VMware with bare metal installer

### Expected Behavior
ipxe installs worker / controller nodes

### Actual Behavior
I am following the Bare Metal documentation to setup a Tectonic cluster with 1 worker and 1 controller node. I have the provisioner running and went through the graphical installer to register the controller and worker.

Then I tried to boot the controller and first it looked okay for me, but I end up in a reboot loop.

The dnsmasq-log shows that the controller doesn't get the correct IP-Address.

### Other Information
- DNS:
$ nslookup llab12.fokus.fraunhofer.de
[...]
Name:   llab12.fokus.fraunhofer.de
Address: 192.168.231.12

- Asset:
$ cat lernlabor-llab12.json
{
        "id": "lernlabor-llab12",
        "profile": "tectonic-controller",
        "selector": {
                "mac": "00:50:56:bd:17:a9",
                "os": "installed"
        },
        "metadata": {
                "cni_bin_dir_flag": "",
                "domain_name": "llab12.fokus.fraunhofer.de",
                "etcd_enabled": "true",
                "etcd_image_tag": "v3.1.8",
                "etcd_initial_cluster": "llab12=https://llab12.fokus.fraunhofer.de:2380",
                "etcd_name": "llab12",
                "etcd_scheme": "https",
                "etcd_tls_enabled": "1",
                "exclude_tectonic": "0",
                "k8s_dns_service_ip": "10.3.0.10",
                "kubelet_image_tag": "v1.7.1_coreos.0",
                "kubelet_image_url": "quay.io/coreos/hyperkube",
                "ssh_authorized_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmNc/ZE28wzzPZMdPDGgjvRxvYrzipN2ncMoZ3c66v1eJcopN0nWGubID+GOYGnnw0Id5CC18L0WtZnNPuNDpLULjgAjiyv2QGF3FwhUSl0WQra7uzuKCYm/xAAUesrFKceUGRAMAcqwyaW5SrM4z58d8Y3oepN8XdIn68HmCsF53tpSDxkPzIVacOoKwwgQERX9S2wcZKMQS9BeLvfiWBGvcPnqbsCtNAOTdhTe7DiRsfTtQTG/VkbBymZhIFza9ZyYmflMUzb3XyWTOQhVlwG5ZffyPK1ZcMmUdYDteMddTDAkiSvDdi0NYSWaxI60PVWxQl3ZkpIIN783gyR60kdtu4s/y9SID2v/NYDkoyxxHymbZag/SPtyb4ljF8huDKc7h4Xvka/XuwqzniFehI6HsLBm6e4Sk++6eR502/klqRzO3Ct03O4a5icwkfI2L/u/uMjWZtj5IoOqnU3vxZATeWBpQ9nWSUj51NiYQVEEQheZzt9361j7xbDxirAXC2ecmFPUNxUMfICViRaDBw3G2OTgx+cHbIvZoF1MCReg+nMQccXCdkfx0KCUAedJjvhABHjwXoK2xFm+oPK/pvXIy1v9PprQHAjJ8n8XBaVWy1I8jlj1qa78LILXiaHRe8l0G1m7ojuMs7GzfyObDCcdNpBV/tH3S6iafUOlQlgQ== root@llab11.fokus.fraunhofer.de\n\n"
        }
}

- dnsmasq log
dnsmasq-dhcp: 1517280368 DHCPDISCOVER(ens160) 00:50:56:bd:17:a9
dnsmasq-dhcp: 1517280368 tags: ipxe, ens160
dnsmasq-dhcp: 1517280368 DHCPOFFER(ens160) 192.168.231.29 00:50:56:bd:17:a9

**Comment by kbrwn** [comment]
Are you using the coreos/dnsmasq container or your own dns? Can you share the dns configuration that you have passed? If using the coreos/dnsmasq container you can just share the docker run command.

**Comment by sgrund42** [comment]
I'm using the container:

docker run --rm --cap-add=NET_ADMIN --net=host quay.io/coreos/dnsmasq \
        -d -q \
        --dhcp-range=192.168.231.12,192.168.231.29 \
        --enable-tftp --tftp-root=/var/lib/tftpboot \
        --dhcp-userclass=set:ipxe,iPXE \
        --dhcp-boot=tag:#ipxe,undionly.kpxe \
        --dhcp-boot=tag:ipxe,http://llab-matchbox.fokus.fraunhofer.de:8080/boot.ipxe \
        --dhcp-option=option:router,192.168.231.1 \
        --address=/llab-matchbox.fokus.fraunhofer.de/192.168.231.10 \
        --log-queries \
        --log-dhcp

**Comment by sgrund42** [comment]
I'm using the container:

docker run --rm --cap-add=NET_ADMIN --net=host quay.io/coreos/dnsmasq \
        -d -q \
        --dhcp-range=192.168.231.12,192.168.231.29 \
        --enable-tftp --tftp-root=/var/lib/tftpboot \
        --dhcp-userclass=set:ipxe,iPXE \
        --dhcp-boot=tag:#ipxe,undionly.kpxe \
        --dhcp-boot=tag:ipxe,http://llab-matchbox.fokus.fraunhofer.de:8080/boot.ipxe \
        --dhcp-option=option:router,192.168.231.1 \
        --address=/llab-matchbox.fokus.fraunhofer.de/192.168.231.10 \
        --log-queries \
        --log-dhcp

**Comment by sgrund42** [comment]
Perhaps some clarification:
- the matchbox-Server runs as vm under CentOS 7
I've following the install guide at https://coreos.com/matchbox/docs/latest/deployment.html
The verification via curl / openssl are good
on this server runs also the docker container for dsnmasq as described under
https://coreos.com/matchbox/docs/latest/network-setup.html#coreosdnsmasq

- the tectonic installer runs under a second vm (CentOS with GUI)
$ wget https://releases.tectonic.com/tectonic-1.7.1-tectonic.1.tar.gz
$ tar xzvf tectonic-1.7.1-tectonic.1.tar.gz
$ cd tectonic/tectonic-installer
$ ./linux/installer

As written I've configured the cluster for one master/controller node and one worker node. When powering the nodes everythings looks fine. The machine boots via dhcp/pxe and installs CoreOS.
It stands about 5 seconds at the login-prompt then it reboots and the whole goes on and on.

**Comment by kbrwn** [comment]
@sgrund42 

> It stands about 5 seconds at the login-prompt then it reboots and the whole goes on and on.

It is perhaps possible that the machine is rebooting to update (although 5 seconds seems a bit quick for update-engine to work) but is set to PXE boot instead of booting from the disk CL was installed on.

**Comment by sgrund42** [comment]
@kbrwn 
> It is perhaps possible that the machine is rebooting to update (although 5 seconds seems a bit quick for
> update-engine to work) but is set to PXE boot instead of booting from the disk CL was installed on. 

You're right. The nodes are booting via DHCP/PXE instead of local disk. After correcting this the reboot loop doesn't happen. So this part of the problem is solved, but the second part still exists: the nodes doesn't have the configured IP-Adresses. I will close this issue and open a new one with more detail of my problems.

Thanks so far.
