### ISSUE TITLE
which is the latest tectonic version?

### ISSUE THREAD

**Issue by sgrund42** [coreos/tectonic-forum#190]
### Tectonic Version 
1.7.x

### Other Information

On https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html
in chapter 4.  Tectonic Installer is a link to https://releases.tectonic.com/tectonic-1.7.3-tectonic.1.tar.gz
However on https://coreos.com/tectonic/docs/latest/install/bare-metal/
in chapter 4. Tectonic Installer the link goes to https://releases.tectonic.com/tectonic-1.7.1-tectonic.2.tar.gz
Also under https://coreos.com/tectonic/docs/latest/ is tectonic-1.7.1-tectonic.2 as latest version given.

**Comment by sym3tri** [comment]
@sgrund42 Thanks for reporting this.

@coreos/team-docs This looks like a bug in the docs.

**Comment by robszumski** [comment]
Sorry for the confusion @sgrund42, the 1.7.3-tectonic.1 had [a bug in it](https://github.com/coreos/tectonic-installer/pull/1877) that was discovered late on Friday and we decided to roll back the docs so folks weren't installing a broken release over the weekend. You might have hit a temporarily cached page.

Look for an updated 1.7.3-tectonic.2 very soon.

**Comment by sgrund42** [comment]
Thanks for Your quick response. As far as I can see are the doc now correct.
I will close this issue.
