### ISSUE TITLE
Kubernetes API Connection has a problem

### ISSUE THREAD

**Issue by EvgenyKhaliper** [coreos/tectonic-forum#201]
### Environment

AWS

### Expected Behavior

To see kuberentes entities in tectonic dashboard
To be able to run against API and install Kuberentes Dashboard app

### Actual Behavior

After installation

Tectonic Dashboard
"Kubernetes API Connection
API server connection has a problem"
under tectonic cluster status
cannot see any k8s entities with no access restriction

cannot install k8s dashboard with:
Error: 'malformed HTTP response "\x15\x03\x01\x00\x02\x02"'
Trying to reach: 'http://10.2.1.9:8443/'

kubectl works just fine with kubeconfig from assets.zip

**Comment by robszumski** [comment]
It appears that you are connecting to http but the API server in Tectonic is only using TLS.

Did you make any modifications to the install around TLS?

Are you using kubectl to install the dashboard? With what command?

**Comment by EvgenyKhaliper** [comment]
I did not modify the install at all.
Dashboard is installed as described on its GitHub page. Kubectl create -f pathtofile.
Tectonic web portal cannot access k8s either so it is not just a dashboard issue.

Maybe it has something to do with kubernetes security introduced in 1.7 ?

**Comment by robszumski** [comment]
Can you take a look at the log in the tectonic-system namespace for Console and Identity? Do you see anything out of the ordinary there? Is anything crashlooping?

**Comment by EvgenyKhaliper** [comment]
@robszumski 

Hi, Console has this issue 
error verifying token: oidc: unable to verify JWT signature: no matching keys

one of Indentity had 2 restarts

**Comment by robszumski** [comment]
Can you post the logs of the restarting Identity pod? It seems like it is not generating new keys for some reason. The last few log lines should hint why.

**Comment by EvgenyKhaliper** [comment]
@robszumski , we randomly having issues once with installer which is stuck for hours on starting kuberentes, issue above and other issues so we decided try other products.

thanks for the help.
