### ISSUE TITLE
Kube-Scheduler Recovery cannot be loaded via tectonic-console

### ISSUE THREAD

**Issue by zonepalms91** [coreos/tectonic-forum#204]
### Tectonic Version 
1.7.3.tectonic.3

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
Pod scheduler recovery can only be done via the cli. I have a YAML configured to recover a scheduler, but the yaml throws an error when executing via console. Error states the nodename is declared twice, but when I remove the second occurrence, the recovery scheduler hangs indefinitely, and never creates the pod.
### Actual Behavior
Should be runnable via GUI or CLI

### Reproduction Steps

  1. have cluster with failed schedulers
  2. create scheduler-recovery
  3. attempt to load yaml (after following CoreOS recovery steps) in tectonic-console

### Other Information
`apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: null
    name: kube-scheduler-rescue
    namespace: kube-system
  spec:
    nodeName: ip-xx-x-xx-xxx.ec2.internal
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              pod-anti-affinity: kube-scheduler-1.7.3-tectonic.3
          namespaces:
          - kube-system
          topologyKey: kubernetes.io/hostname
    containers:
    - command:
      - ./hyperkube
      - scheduler
      - --leader-elect=true
      image: quay.io/coreos/hyperkube:v1.7.3_coreos.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 10251
          scheme: HTTP
        initialDelaySeconds: 15
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 15
      name: kube-scheduler-rescue
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    nodeName: ip-xx-x-xx-xx.ec2.internal
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  status: {}
kind: List
metadata: {}
`

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

**Comment by kbrwn** [comment]
@zonepalms91 It is likely that this recovery process will remain something that needs to be done via kubectl. The kube-scheduler pods becoming unavailable was mostly due to a configuration that allowed schedulers to all be deployed to the same controller node. There have been measures taken to prevent this in recent releases of Tectonic.
