### ISSUE TITLE
Ingress Events

### ISSUE THREAD

**Issue by ledor473** [coreos/tectonic-forum#205]
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS and bare metal

### Desired Feature
An Ingress resource could have an Events tab (just like a Pod) to show the related Events.

They are visible under Troubleshooting -> Events, but there's no way to drill-down on a specific Ingress (something like `kubectl describe ing <ingress name>`)

### Other Information
Another way to address that feature would be to have a dropdown in the Troubleshooting view that let you drill-down on a specific Ingress

**Comment by kbrwn** [comment]
@ledor473 Thanks for reporting this. I think this would be helpful for debugging ingress resources as well.
