### ISSUE TITLE
AWS-specific StorageClasses do not appear to be configured, so PVCs fail

### ISSUE THREAD

**Issue by bleggett** [coreos/tectonic-forum#209]
### Tectonic Version 
1.7.5-tectonic.1

### Environment

AWS

### Expected Behavior

AWS-specific StorageClasses would be configured so that volume claims can succeed.

### Actual Behavior
Volume Claims fail with error `no persistent volumes available for this claim and no storage class is set`

`kubectl get storageclasses` returns only `etcd-backup-gce`

### Reproduction Steps

  1. Stand up Kube cluster with Tectonic in AWS
  2. Publish deployment with baseline PVC with no storageclass defined.
  3. PVC will fail to provision.

**Comment by bleggett** [comment]
The root cause is documented in https://github.com/coreos/tectonic-installer/issues/711.

**Comment by johnwards** [comment]
How do I fix this for an AWS cluster? Applying the file linked in coreos/tectonic-installer#711 seems to error out

**Comment by johnwards** [comment]
Ah ha, I copy and pasted it wrong.

The key thing I think I took away, after reading all about PersistentVolume's etc is that in the [add on one](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/aws/default.yaml) it has the meta data that makes it the default storage class.

Currently tectonic on AWS doesn't setup a default storage class. For someone new to kubernetes like I am this is easy to miss.
