### ISSUE TITLE
Softlayer test

### ISSUE THREAD

**Issue by s4mur4i** [coreos/tectonic-forum#21]
### Environment

Softlayer

## Feature Request

I would like to test tectonic on softlayer with virtual machines. 
Docs say: "Tectonic clusters can be run on most cloud providers and on bare metal. " , but only aws and bare metal PXE is supported. It would be nice to be able to provision virtual machines and use consol, or if installer could create a virtual machine image, and spin up environment from it.

**Comment by sym3tri** [comment]
Thanks for letting us know. Those docs are incorrect and will be updated.

We will be adding support for additional platforms in the future.

**Comment by mfburnett** [comment]
Docs are updated now! Will make a note to come back to this issue in the future if we explore Softlayer support.

**Comment by mfburnett** [comment]
Closing this issue and will reopen if we explore Softlayer support.
