### ISSUE TITLE
Use static IP address from DNS

### ISSUE THREAD

**Issue by nlowe** [coreos/tectonic-forum#219]
### Tectonic Version 

`1.7.5-tectonic.1 (1cccbee)`

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

VMware ESX VM's using the bare-metal workflow

### Expected Behavior

One of the following:

* Tectonic Installer provides a way to specify static IP addresses for nodes to use
* The nodes use the IP address that DNS returns for their FQDN

### Actual Behavior

Nodes get an address from DHCP and use some UUID instead of the mac address as the client identifier. Microsoft's DHCP Server implementation does not seem to allow this when creating DHCP Reservations (See #116). Because the node's IP addresses do not match DNS, Tectonic Installer cannot contact them to finish the installation and the process hangs.

### Reproduction Steps

1. Create static DNS entries for the FQDN of master and worker nodes
    * Optional: Create DHCP Reservations
2. Submit tectonic configuration to matchbox and boot the nodes

### Other Information

I tried the workaround in #116 by placing the configuration file on the matchbox machine. It does not appear to have been applied.

**Comment by kbrwn** [comment]
@nlowe 

I won't comment on the merits of this request. A dev like @dghubble would have more insight into why this is/isn't a good idea. 

> Nodes get an address from DHCP and use some UUID instead of the mac address as the client identifier. 

This behavior is under your control as an sysadmin no? Using DHCP to provide an IP based on mac address as is documented by Microsoft here:
https://technet.microsoft.com/en-us/library/hh831538(v=ws.11).aspx#pba_1

**Comment by dghubble** [comment]
Configure the DHCP server to map requests from a MAC address to a configured IP address. A DNS server should provide a name mapping to those IPs. Tectonic [requires](https://coreos.com/tectonic/docs/latest/install/bare-metal/requirements.html#machines) the DNS name for each machine. Those names are used to mint TLS certificates and you should avoid assigning IPs directly - if in future you even need to make network changes, those IPs would be baked into the configurations of the machines, services, certificates, etcd, etc. Using DNS names gives you flexibility.

Here's the Matchbox example dnsmasq configuration which maps known MAC addresses to IPs and DNS names to those IPs: https://github.com/coreos/matchbox/blob/master/contrib/dnsmasq/docker0.conf#L6

**Comment by nlowe** [comment]
Thanks for the quick responses. Let me clarify:

I can create a reservation for an IP address based on the MAC Address of the machine in our DHCP Server. The problem I'm experiencing is that the machines are not taking these reservations. When I look in the address lease table, I see an address from the DHCP Pool assigned to the machine with the same hostname. For these leases, the Client ID is not the macaddress like most other machines in my network, but some other, much longer identifier. Does that clarify anything?

**Comment by kbrwn** [comment]
@nlowe This is not an issue of clarity. You have stated the problem: 

> The problem I'm experiencing is that the machines are not taking these reservations.

Now you should begin debugging why these leases do not have the correct parameters. Why is the client id not the mac address? It seems that the most likely case is that vmware is generating incorrect or incomplete mac addresses.

**Comment by nlowe** [comment]
I see. I misunderstood that this is actually a problem with my DHCP infrastructure and not how coreos asks for addresses. I'll look into it, thanks again for the help.
