### ISSUE TITLE
Redirect cycle accessing Tectonic dashboard

### ISSUE THREAD

**Issue by naphthalene** [coreos/tectonic-forum#22]
### Tectonic Version 

1.4.7

### Environment

- AWS - 1 x t2.medium controller, 3 x m4.xlarge workers
- Using Firefox to access console
- Linux installer

### Expected Behavior

When accessing the Tectonic console, I expect it to prompt me to login or redirect me to the login page.

### Actual Behavior

URL becomes ```/error?error_type=auth&error=logout_error``` and it starts to redirect cycle.
Occasionally it breaks out of the loop and redirects me to ```/identity/auth/local```

### Reproduction Steps

  1. Install fresh cluster
  2. Open console

**Comment by mfburnett** [comment]
hey @naphthalene, sorry for the delayed response here. Looking into this now and will follow up soon.

**Comment by ericchiang** [comment]
@naphthalene can use the kubeconfig in your downloaded assets bundle[0] to dump the logs of console and identity in the tectonic-system namespace? It's hard for us to know what's going on without those.

Also we cut down on some of this flakyness in more recent releases. If you're going to re-install consider updating the version.

[0] https://coreos.com/tectonic/docs/latest/admin/assets-zip.html

**Comment by mfburnett** [comment]
@naphthalene were you able to resolve this issue? We recently released Tectonic v1.6.2-tectonic.1 with a ton of improvements - would recommend you check it out!

**Comment by naphthalene** [comment]
I have not tried setting this up since the failure. I'll close the ticket since it seemed to be just me
