### ISSUE TITLE
Tectonic Console: Cannot Edit/Duplicate RoleBinding

### ISSUE THREAD

**Issue by a2ndrade** [coreos/tectonic-forum#226]
### Tectonic Version 
1.7.9
### Environment

AWS. 3 Masters, 3 Workers

### Expected Behavior

Should be able to duplicate/edit/etc. a RoleBinding through the Tectonic Console (UI)

### Actual Behavior

A JavaScript error prevents any of the options in the menu from working

### Reproduction Steps

  1. Go to Administration / RoleBindings
  2. Click on the small gear menu for one of the RoleBindings
  3. Select Edit/Duplicate/etc.

### Other Information

This started happening  (today) as soon as I upgraded from 1.7.5 to 1.7.9

**Comment by kbrwn** [comment]
hi @a2ndrade this has been fixed. There is not an official Tectonic release with the fixed image at this time. If you wish to remedy this issue immediately you can update the `image: quay.io/coreos/tectonic-console`  tag in the `tectonic-console` deployment to `v2.3.5`. 

```
$ kubectl -n tectonic-system edit deploy tectonic-console
```

**Comment by a2ndrade** [comment]
I just verified it. Thank you!
