### ISSUE TITLE
How to define multiple workers for Vagrant/Virtualbox

### ISSUE THREAD

**Issue by pipo02mix** [coreos/tectonic-forum#229]
### Tectonic Version 
1.7.1-tectonic.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
Runnin on Mac Os X the sandbox with Vagrant/Virtualbox 

### Expected Behavior
In the Vagrantfile or UI you can specify how many workers do you want (tectonic free tier is up to 10)
### Actual Behavior
Vagrantfile or UI has no any configuration parameter as it had [before](https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/vagrant)
### Other Information
I have tried to hack the Vagrantfile adding more workers using a loop, but I had some troubles.
I can do a PR with it and you can help me. I think it could be nice for others too

**Comment by 123BLiN** [comment]
It will be awesome to try multiple workers in the sandbox. I need to be able to emulate workers unavailability for current project at home, and our developers need this too.

**Comment by kbrwn** [comment]
@pipo02mix @123BLiN Tectonic Sandbox is a project with the goal of spinning up a cluster to test out Tectonic. It is not likely that we will expand it to include features like adding additional worker nodes. 

You could probably hack this up quite easily by editing the vagrant file if you desire.
