### ISSUE TITLE
Upgrade to 1.7.9 2 seems to have broken the tectonic console.

### ISSUE THREAD

**Issue by birdiesanders** [coreos/tectonic-forum#231]
### Tectonic Version 
1.7.9 2
### Environment
VSphere - installed as baremetal
What hardware/cloud provider/hypervisor is being used with Tectonic?

### Expected Behavior
Tectonic Console should start
### Actual Behavior
The pods fall into a crashloop, logs indicate that it cannot find the tectonic-ca-cert-secret/ca-cert 
### Reproduction Steps

  1. ... Update from 1.7.9 1 to 1.7.9 2
  2. ... Profit. 

### Other Information
I did update the tectonic license to one from another account shortly before running the update.

**Comment by kbrwn** [comment]
@birdiesanders does the secret exist in the tectonic system namespace?

**Comment by birdiesanders** [comment]
It does. And it appears to be valid. I would up realizing that since all I had to do was spend 45 minutes getting my cluster back up, it would be rather trivial to just tear down and rebuild the cluster. This time, I added a second master and another worker. No idea what happened, but it left me in a better position in the end.

**Comment by kbrwn** [comment]
@birdiesanders yeah I find that some problems are more easily resolved by spinning up a new cluster an migrating workloads. Although I am sure we could have resolved this issue during a live debugging session. It the future when submitting issues please share more information such as logs that show the error.
