### ISSUE TITLE
Cannot Download Tectonic Sandbox

### ISSUE THREAD

**Issue by mattmadhavan** [coreos/tectonic-forum#244]
Hello,
When I try to download the Tectonic Sandbox I am getting an access denied exception.

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>455D4525CAEEB11D</RequestId>
<HostId>
dLM4p37qMmK/Hls6zYHtFSEvVbBnn5kKPc+Cad3smwyWTXxo+nBLJL/0QIcqv1Y6Ttgbnmt6DKg=
</HostId>
</Error>`

**Comment by sym3tri** [comment]
@mattmadhavan Sorry about that. You should be able to download now. Please try it again.
