### ISSUE TITLE
Label update failing, If label comes with (key/value)separated by a slash (/) in tectonic(v1.8.4+coreos.0).

### ISSUE THREAD

**Issue by senpx** [coreos/tectonic-forum#245]
## Issue Report Template
Label update failing, If label comes with (key/value)separated by a slash (/) in tectonic(v1.8.4+coreos.0). as per k8s https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ , I am able to update the same in other k8s(1.8.4) cluster. 
Lable update with spash(/) failing in only on tectonic(1.8.4). Please find below error message:
"The Node "ip-10-0-62-153.us-west-2.compute.internal" is invalid: metadata.labels: Invalid value: "px~1service": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')"

### Environment 
What hardware/cloud provider/hypervisor is being used with Tectonic? - AWS cloud

NAME                                        STATUS    AGE       VERSION           EXTERNAL-IP     OS-IMAGE                                       KERNEL-VERSION
ip-10-0-62-153.us-west-2.compute.internal   Ready     35m       v1.8.4+coreos.0   <none>          Container Linux by CoreOS 1576.4.0 (Ladybug)   4.13.16-coreos-r2
ip-10-0-7-229.us-west-2.compute.internal    Ready     35m       v1.8.4+coreos.0   52.25.248.119   Container Linux by CoreOS 1576.4.0 (Ladybug)   4.13.16-coreos-r2
ip-10-0-86-223.us-west-2.compute.internal   Ready     35m       v1.8.4+coreos.0   <none>          Container Linux by CoreOS 1576.4.0 (Ladybug)   4.13.16-coreos-r2

### Reproduction Steps: example: 
SenS-MacBookPro:~ sen_sri$ kubectl label nodes ip-10-0-62-153.us-west-2.compute.internal px/service=disable --overwrite
The Node "ip-10-0-62-153.us-west-2.compute.internal" is invalid: metadata.labels: Invalid value: "px~1service": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]').

Did anyone face this issue? Please help us to resolve the same?

**Comment by Quentin-M** [comment]
Hi please,

Please see https://github.com/kubernetes/kubernetes/issues/54464.

**Comment by Quentin-M** [comment]
- What's your kubectl version? Please make sure it matches the version of Kubernetes you are using.
- If this wasn't enough, please try to escape/quote the label?

**Comment by senpx** [comment]
Please find below , I tried with escape and quote but still getting the same error as below.
SenS-MacBookPro:~ sen_sri$ kubectl label nodes ip-10-0-62-153.us-west-2.compute.internal px\/service=disable --overwrite
The Node "ip-10-0-62-153.us-west-2.compute.internal" is invalid: metadata.labels: Invalid value: "px~1service": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
SenS-MacBookPro:~ sen_sri$ kubectl label nodes ip-10-0-62-153.us-west-2.compute.internal 'px/service=disable' --overwrite
The Node "ip-10-0-62-153.us-west-2.compute.internal" is invalid: metadata.labels: Invalid value: "px~1service": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
SenS-MacBookPro:~ sen_sri$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"

**Comment by senpx** [comment]
hi Quentin-M, As you mentioned, I have upgraded my kubectl version to 1.8.4 to match with the tectonic cluster version 1.8.4, it works fine as below. 

```SenS-MacBookPro:tectonic-sandbox-1.7.5 sen_sri$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
SenS-MacBookPro:tectonic-sandbox-1.7.5 sen_sri$ kubectl label nodes ip-10-0-62-153.us-west-2.compute.internal px/service=disable --overwrite
node "ip-10-0-62-153.us-west-2.compute.internal" labeled``` 

We should be good to close the case. thanks for your prompt responses. Merry Christmas and New Year. 

Sen S
