### ISSUE TITLE
module.vpc.aws_elb.api_external: "name" cannot begin with a hyphen: "-ext"

### ISSUE THREAD

**Issue by MilenkoM** [coreos/tectonic-forum#246]
## Issue Report Template

terraform plan -var-file=build/my-cluster/terraform.tfvars platforms/aws
3 error(s) occurred:

* module.vpc.aws_elb.api_external: "name" cannot begin with a hyphen: "-ext"
* module.vpc.aws_elb.api_internal: "name" cannot begin with a hyphen: "-int"
* module.vpc.aws_elb.console: "name" cannot begin with a hyphen: "-con"

### Tectonic Version 
tectonic_1.8.4-tectonic.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS
### Expected Behavior
terraform plan configuration in a proper manner
### Actual Behavior
terraform plan -var-file=build/my-cluster/terraform.tfvars platforms/aws
3 error(s) occurred:

* module.vpc.aws_elb.api_external: "name" cannot begin with a hyphen: "-ext"
* module.vpc.aws_elb.api_internal: "name" cannot begin with a hyphen: "-int"
* module.vpc.aws_elb.console: "name" cannot begin with a hyphen: "-con"

### Reproduction Steps

  1.I am on Ubuntu 16.04, trying to install Tectonic on AWS with Terraform
  2. I have changed terraform.tfvars
tectonic_aws_external_worker_subnet_ids = "subnet-7b8f2336","subnet-99a61df2","subnet-ab24d8d6"

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by sym3tri** [comment]
Those names are derived from the `cluster_name` variable, which if left as empty string will result in invalidly named ELBs. It's seems `cluster_name` was not set. Feel free to reopen if you see the same error after setting `cluster_name`.
