### ISSUE TITLE
Upgrading Calico Manually guide for Tectonic 1.8.4, file is empty

### ISSUE THREAD

**Issue by yuko11** [coreos/tectonic-forum#247]
Guide:
https://coreos.com/tectonic/docs/latest/troubleshooting/upgrade-calico.html
Section:
Upgrade the Role-Based Access Control rules
URL:
https://coreos.com/tectonic/docs/latest/troubleshooting/calico-manifests/rbac-canal-tectonic-18.yaml
is empty

**Comment by robszumski** [comment]
@yuko11 Apologies for the issues, this looks like a rendering issue with our website. You can reference the file on Github here: https://github.com/coreos/tectonic-docs/blob/master/Documentation/troubleshooting/calico-manifests/rbac-canal-tectonic-18.yaml

**Comment by robszumski** [comment]
A fix is being deployed for the website now. Thanks for reporting this!

**Comment by yuko11** [comment]
Thanks a lot!
