### ISSUE TITLE
Tectonic console container fails to start

### ISSUE THREAD

**Issue by rothgar** [coreos/tectonic-forum#25]
### Tectonic Version 
1.5.1
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic? Bare Metal

### Expected Behavior
Tectonic console starts
### Actual Behavior
The tectonic console container is failing to start with the following message printed in the docker logs

2017/01/18 07:13:09 http: Provider config sync still failing, retrying in 8s: invalid character 'd' looking for beginning of value

That repeats for a few minutes and then the container dies.

### Reproduction Steps

  1. Follow tectonic installation steps with 2 nodes

### Other Information
I've had to reboot the controller multiple times due to #23 which may be a contributing factor. I also had to hand edit /etc/kubernetes/kubeconfig to change the api server hostname because of #24. Both items may be contributing here but as far as I can tell I got all of the services running on the worker node (ingress controllor, node-exporter, etc.) but the console fails to start.
Before the ingress controller was starting on the worker I was getting errors in the console logs saying it failed connecting to the $worker/identity endpoint which AFAIK was waiting for the ingress controller to start.

**Comment by dghubble** [comment]
The assets.zip bundle includes an auth/kubeconfig file. If the Tectonic console doesn't come up, could you use that to give a quick peek at which pods are failing and logs? There is a new doc on this over [here](https://tectonic.com/enterprise/docs/latest/admin/assets-zip.html).

**Comment by dghubble** [comment]
Yep, console has to talk to identity. If all pods are running successfully, except console, I suspect a naming or DNS issue using Ingress.

**Comment by rothgar** [comment]
The ingress route is failing
```
curl -k -L https://three.lan/identity/healthz
default backend - 404
```

I checked the apiserver and it appears to be down (last night it was up) because it cannot connect to etcd2.

```
kubectl get po --kubeconfig auth/kubeconfig -owide
Unable to connect to the server: dial tcp 192.168.86.105:443: getsockopt: no route to host
```

logs from the kube-apiserver container shows

```
I0118 16:41:26.340532       7 trace.go:61] Trace "Get /apis/oidc.coreos.com/v1/namespaces/tectonic-system/signingkeies/openid-connect-keys" (started 2017-01-18 16:41:24.386028396 +0000 UTC):
[1.954483795s] [1.954483795s] END
E0118 16:41:26.340547       7 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
E0118 16:41:56.357498       7 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
```

etcd2 shows it's running but in unhealthy which is probably where the problem lies

```
core@one ~ $ systemctl status etcd2
● etcd2.service - etcd2
   Loaded: loaded (/usr/lib/systemd/system/etcd2.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/etcd2.service.d
           └─40-etcd-cluster.conf
   Active: active (running) since Wed 2017-01-18 07:10:24 UTC; 9h ago
 Main PID: 1001 (etcd2)
    Tasks: 12
   Memory: 248.7M
      CPU: 3min 45.820s
   CGroup: /system.slice/etcd2.service
           └─1001 /usr/bin/etcd2

Jan 18 15:18:09 one.lan etcd2[1001]: compacted raft log at 135014
Jan 18 15:18:23 one.lan etcd2[1001]: purged file /var/lib/etcd2/member/snap/0000000000000009-0000000000015f99.snap successfully
Jan 18 15:56:00 one.lan etcd2[1001]: start to snapshot (applied: 150015, lastsnap: 140014)
Jan 18 15:56:00 one.lan etcd2[1001]: saved snapshot at index 150015
Jan 18 15:56:00 one.lan etcd2[1001]: compacted raft log at 145015
Jan 18 15:56:23 one.lan etcd2[1001]: purged file /var/lib/etcd2/member/snap/0000000000000009-00000000000186aa.snap successfully
Jan 18 16:33:50 one.lan etcd2[1001]: start to snapshot (applied: 160016, lastsnap: 150015)
Jan 18 16:33:50 one.lan etcd2[1001]: saved snapshot at index 160016
Jan 18 16:33:50 one.lan etcd2[1001]: compacted raft log at 155016
Jan 18 16:33:53 one.lan etcd2[1001]: purged file /var/lib/etcd2/member/snap/0000000000000009-000000000001adbb.snap successfully
core@one ~ $ etcdctl cluster-health                                                                                                                                                                                  
failed to check the health of member d483ac99c25d21dd on http://one.lan:2379: Get http://one.lan:2379/health: dial tcp 192.168.86.105:2379: getsockopt: no route to host
member d483ac99c25d21dd is unreachable: [http://one.lan:2379] are all unreachable
cluster is unhealthy
```

**Comment by mfburnett** [comment]
cc @dghubble @kbrwn

**Comment by kbrwn** [comment]
@rothgar Do you still  require assistance with this issue or did you resolve it by bringing your etcd cluster to a healthy state?

**Comment by rothgar** [comment]
I have not had time to retest my cluster but after conversations with multiple people it looks like the main failure (postgres supporting dex) is removed or being removed from the latest release.

I'll close this issue and open a new ticket on the newer version if I still have problems.

**Comment by rushins** [comment]
hi guys i have similar issue but not same. Tectonic console was not responding, so i deleted the PODs but after somepoint the PODS were not stated and i get gateway error.

502 Bad Gateway

nginx/1.13.1

any clue

**Comment by fii** [comment]
is this resolved ? seeing the same issue ..

**Comment by fii** [comment]
@rushins Got it working . Let me know if you need help.
