### ISSUE TITLE
"data.aws_route53_zone.tectonic: no matching Route53Zone found" during install

### ISSUE THREAD

**Issue by samiqs** [coreos/tectonic-forum#251]
### Tectonic Version 
1.8.4

### Environment
AWS

What hardware/cloud provider/hypervisor is being used with Tectonic?
Deploying to Private VPC w/ VPN Tunnel
Created Route53 Private hosted zone

### Expected Behavior
Running Terraform plan should complete successfully

### Actual Behavior

Getting error:
```
Error: Error refreshing state: 1 error(s) occurred:

* module.dns.data.aws_route53_zone.tectonic: 1 error(s) occurred:

* module.dns.data.aws_route53_zone.tectonic: data.aws_route53_zone.tectonic: no matching Route53Zone found
```

### Reproduction Steps

  1. created route53 private hosted zone for existing private vpc
  2. using terraform install. Set ```tectonic_base_domain = "kube.internal.aws"```
  3. exported required env variables 

```
export AWS_SESSION_TOKEN=###########
export AWS_SECRET_ACCESS_KEY=###########
export AWS_ACCESS_KEY_ID=#####
export AWS_REGION=us-east-1
export CLUSTER=proto
export TF_VAR_tectonic_admin_email="#####"
export TF_VAR_tectonic_admin_password="#####"
#export TF_LOG=DEBUG

terraform validate -var-file=build/${CLUSTER}/terraform.tfvars platforms/aws
```
### Other Information

- I see the hosted zone using ```aws route53 list-hosted-zones```
- I can successfully dig the route 53 domain
- ran install via VPN and from instance in VPC. Same results.

Also getting theses warning:

```
Warning: output "etcd_sg_id": must use splat syntax to access aws_security_group.etcd attribute "id", because it has "count" set; use aws_security_group.etcd.*.id to obtain a list of the attributes across all instances



Warning: output "aws_api_external_dns_name": must use splat syntax to access aws_elb.api_external attribute "dns_name", because it has "count" set; use aws_elb.api_external.*.dns_name to obtain a list of the attributes across all instances



Warning: output "aws_elb_api_external_zone_id": must use splat syntax to access aws_elb.api_external attribute "zone_id", because it has "count" set; use aws_elb.api_external.*.zone_id to obtain a list of the attributes across all instances



Warning: output "aws_api_internal_dns_name": must use splat syntax to access aws_elb.api_internal attribute "dns_name", because it has "count" set; use aws_elb.api_internal.*.dns_name to obtain a list of the attributes across all instances



Warning: output "aws_elb_api_internal_zone_id": must use splat syntax to access aws_elb.api_internal attribute "zone_id", because it has "count" set; use aws_elb.api_internal.*.zone_id to obtain a list of the attributes across all instances

```

**Comment by samiqs** [comment]
Warnings were related to incorrect terraform version in path. Error still persists.

**Comment by samiqs** [comment]
Resolved by adding private_zone to aws_route 
53_zone.

modules/dns/route53/tectonic.tf

```
data "aws_route53_zone" "tectonic" {
  name = "${var.base_domain}"
  private_zone=true
}

```

**Comment by sporkmonger** [comment]
I'm hitting the same thing. Tried making the change you mentioned above, but no dice for me.

**Comment by vicaraniron** [comment]
Worked for me, thx

**Comment by sshillo** [comment]
Tried the fix, doesn't work for me

**Comment by vibhuyadav** [comment]
I had this in my script:
`data "aws_route53_zone" "trial2" {
	name         = "trial2"
	private_zone = true
	vpc_id = "${aws_vpc.trial-vpc.id}"
}`

Then ran:
`aws route53 list-hosted-zones`

Got one of the zones as:
`{
            "ResourceRecordSetCount": 2,
            "CallerReference": "2018-04-11T18:22:55.33806-04:00",
            "Config": {
                "Comment": "Managed by Terraform",
                "PrivateZone": true
            },
            "Id": "/hostedzone/ZECXXXXXXFSB",
            "Name": "trial2."
        }`

But still I get this error when I run the script:
`data.aws_route53_zone.trial2: data.aws_route53_zone.trial2: no matching Route53Zone found`

**Comment by joshghent** [comment]
Did anyone ever manage to fix this issue?
I am observing the same behavior as @vibhuyadav
