### ISSUE TITLE
Tectonic LDAP integration: Symbol "$" is cut from bindPW field.

### ISSUE THREAD

**Issue by yuko11** [coreos/tectonic-forum#254]
### Tectonic Version 
1.8.4
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
Baremetal
### Expected Behavior
Password for ldap connector, transferred to LDAP server, as it is configured
### Actual Behavior
Password transferred cutting symbol "$"
### Reproduction Steps

  1. Configure LDAP integration
  2. set
bindDN: user
bindPW: pa$$word
 3. See that test of LDAP integration is working fine.
 3. Deploy new configmap
 4. Try to authenticate LDAP user
 5. Find error for tectonic-identity container:
time="2018-01-15T16:33:36Z" level=error msg="Failed to login user: ldap: initial bind for user \"user\" failed: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580"
6. TCPdump to find that transferred password is "paword", instead of "pa$$word"

**Comment by kbrwn** [comment]
@yuko11 We have an bug report of this on our internal jira. I am not sure when a fix will go out but it is certainly being tracked. 

Thanks for using Tectoinc by CoreOS and for submitting this bug report. Keep em coming!
