### ISSUE TITLE
Vault-operator github repo not accessible

### ISSUE THREAD

**Issue by gdmello** [coreos/tectonic-forum#255]
The Tectonic, Open Cloud Services offering - Vault OCS, includes a `vault-operator` which is referenced in the [documentation](https://coreos.com/tectonic/docs/1.7.9-tectonic.4/vault-operator/user/vault.html#writing-secrets-to-the-active-node), as [vault-operator](https://github.com/coreos-inc/vault-operator/blob/master/README.md#getting-started), but the link refers to a non-existent page.

Since I am considering using the vault operator in production, it would be great to have access to the source/ scripts being referenced in the docs.

**Comment by robszumski** [comment]
Hi gdmello, the Vault operator has not been open-sourced, but don't let that stop you from using it. Any scripts that are referenced in the docs should be available. We will take a spin through the docs and verify that. If you have a specific example, feel free to follow up here.

**Comment by gdmello** [comment]
@robszumski - thanks for the update. The `create cluster` and `tls gen` scripts referenced in [Setting up Ingress](https://coreos.com/tectonic/docs/1.7.9-tectonic.4/vault-operator/user/ingress.html) are not accessible. 

I understand that the `vault-operator` is not open sourced, but I'm looking for any docs on how to use the operator, and can't find any atm.

**Comment by adarshaj** [comment]
Any updates on this? I'm looking for operator's manifest options (i'm interested to see if it allows nodeSelector?)

**Comment by philips** [comment]
Fixed https://github.com/coreos/vault-operator

**Comment by philips** [comment]
Blog: https://coreos.com/blog/introducing-vault-operator-project Github: https://github.com/coreos/vault-operator
