### ISSUE TITLE
Thread errors in pods after Tectonic install 

### ISSUE THREAD

**Issue by bgroupe** [coreos/tectonic-forum#261]
# Issue Report Template

### Tectonic Version 
1.8.4-tectonic.3 (upgraded from 1.7.9)
Container Linux v 1576.5.0 (stable)

### Environment
9 nodes: 3 Master, 6 Worker
Installed via official Tectonic-provided Terraform template

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS/r4.2xlarge

### Expected Behavior
App running on worker node can process requests utilizing system resources limits.

### Actual Behavior
We have a Rails app that processes web requests running 12 pods across 6 nodes. When processing requests, we frequently see the following exception: 

~~~ruby
ThreadError: can't create Thread: Resource temporarily unavailable
  from timeout.rb:81:in `start'
  from timeout.rb:81:in `block in timeout'
  from timeout.rb:100:in `call'
  from timeout.rb:100:in `timeout'
  from net/http.rb:878:in `connect'
  from net/http.rb:863:in `do_start'
  from net/http.rb:852:in `start'
  from net/http.rb:1375:in `request'
  from new_relic/agent/instrumentation/net.rb:33:in `block in request_with_newrelic_trace'
  from new_relic/agent.rb:443:in `disable_all_tracing'
  from new_relic/agent/instrumentation/net.rb:32:in `request_with_newrelic_trace'
  from net/http.rb:1133:in `get'
  from faraday/adapter/net_http.rb:72:in `perform_request'
  from faraday/adapter/net_http.rb:37:in `call'
  from faraday/request/url_encoded.rb:14:in `call'
  from faraday/connection.rb:226:in `run_request'
  from faraday/connection.rb:87:in `get'
~~~

This exception occurs in all pods on all nodes. We did not alter any OS-level config on Tectonic install. On worker nodes `systemctl show -p TasksMax unitname` yields: 
~~~
TasksMax=32768
~~~ 

Inside app container `cat /proc/self/limits` yields:

~~~
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            1048576              1048576              files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       245460               245460               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
~~~
 

This app is deployed to another older, K8S cluster, manually installed on Debian Jessie. There is no TasksMax unit set, and the limits inside a container running the same app are as follows: 
~~~
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             1048576              1048576              processes
Max open files            1048576              1048576              files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       258129               258129               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
~~~

The thread error exception **does not** occur on this installation with the same request traffic. Please advise. 

### Reproduction Steps

  1. Install Tectonic cluster via Terraform
  2. Deploy application  (with Nginx reverse proxy)
  3. Monitor application logs for exception

**Comment by kbrwn** [comment]
@bgroupe I don't quite get the jump to systemd unit tasksmax values here. Care to expand upon why you think this is the issue? In any case the value is set to `infinity` for docker.service: 

```
$ systemctl show -p TasksMax docker
TasksMax=infinity
```
What does the grafana dashboard for this pod look like then this error occurs? any abnormalities?

**Comment by bgroupe** [comment]
@kbrwn Originally the issue was submitted through sales rep and Container Linux team requested TasksMax value on worker node. TasksMax value for docker service on worker nodes is not set to infinity (but very high): 

~~~
TasksMax=18446744073709551615
~~~

We have since unscheduled this pod in our cluster, but there were no abnormalities observed in Grafana, when pod was processing heavy web traffic and New Relic APM graphs for pods in both old and Tectonic cluster are comparable . Thread errors were intermittent, roughly 250 over the course of 3 days.

**Comment by kbrwn** [comment]
@bgroupe This issue seems to be related to the performance of your applications ruby code rather than any coreos software. I don't think that we can really provide the assistance that you seek in this forum.

**Comment by bgroupe** [comment]
@kbrwn Yes the app is experiencing performance issues, but was looking to get a clarification on the difference in behavior between the linux distribution we currently use and Container Linux that ships with Tectonic. Apologies if this is the wrong project, but there is no Container Linux-specific Github project (that I could find). If you have a suggestion of where else I could post this question, I would appreciate.
