### ISSUE TITLE
LDAP connector does not pick up what groups a user belongs to

### ISSUE THREAD

**Issue by magnus-larsson** [coreos/tectonic-forum#265]
### Tectonic Version 

tectonic-sandbox-1.7.5-tectonic.1

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

* MacBook Pro (15-inch, 2017)
* macOS 10.13.2
* Vagrant 2.0.1
* VirtualBox 5.2.6

### Expected Behavior

That role bindings can be created for LDAP-users based on what groups they belong to in LDAP.

### Actual Behavior

Role bindings can only be created for specific LDAP-users and not using the LDAP-groups they belong to.

### Reproduction Steps

**Note:** LDAP OrgId and passwords are replaced with "..." in the description below!

1. Create an account in https://jumpcloud.com

1. Setup users and groups
Registered a user named `magnus` that belongs to the group `cluster-viewers` in the JumpCloud directory.

1. Verify the user `magnus` using `ldapsearch`

        $ ldapsearch -H ldap://ldap.jumpcloud.com:389 -ZZ -x -b "ou=Users,o=...,dc=jumpcloud,dc=com" -D "uid=ldapservice,ou=Users,o=...,dc=jumpcloud,dc=com" -w "..." "(objectClass=inetOrgPerson)"
        
        # magnus, Users, ..., jumpcloud.com
        dn: uid=magnus,ou=Users,o=...,dc=jumpcloud,dc=com
        sn: Larsson
        cn: Magnus Larsson
        uid: magnus
        gidNumber: 5001
        homeDirectory: /home/magnus
        mail: magnus.larsson.ml@gmail.com
        givenName: Magnus
        objectClass: top
        objectClass: person
        objectClass: organizationalPerson
        objectClass: inetOrgPerson
        objectClass: shadowAccount
        objectClass: posixAccount
        objectClass: jumpcloudUser
        uidNumber: 5001
        loginShell: /bin/bash
        jcLdapAdmin: TRUE
        memberOf: cn=cluster-viewers,ou=Users,o=...,dc=jumpcloud,dc=com

1. Verify the group`cluster-viewers` using `ldapsearch`

        $ ldapsearch -H ldap://ldap.jumpcloud.com:389 -ZZ -x -b "ou=Users,o=...,dc=jumpcloud,dc=com" -D "uid=ldapservice,ou=Users,o=...,dc=jumpcloud,dc=com" -w "..." "(&(objectClass=groupOfNames)(member=uid=magnus,ou=Users,o=...,dc=jumpcloud,dc=com))"

        # cluster-viewers, Users, ..., jumpcloud.com
        dn: cn=cluster-viewers,ou=Users,o=...,dc=jumpcloud,dc=com
        cn: cluster-viewers
        ou: cluster-viewers
        objectClass: top
        objectClass: groupOfNames
        description: tagGroup
        member: uid=magnus,ou=Users,o=...,dc=jumpcloud,dc=com

1. Configure Tectonic for using the LDAP connector

    Following the instructions at https://console.tectonicsandbox.com/settings/ldap, I extended the ConfigMap ´tectonic-identity´ in namespace `tectonic-system` with:

        connectors:
          - name: ldap
            id: tectonic-ldap
            type: ldap
            config:
              host: 'ldap.jumpcloud.com:389'
              bindDN: 'uid=ldapservice,ou=Users,o=...,dc=jumpcloud,dc=com'
              bindPW: ...
              userSearch:
                baseDN: 'ou=Users,o=...,dc=jumpcloud,dc=com'
                filter: (objectClass=inetOrgPerson)
                username: uid
                idAttr: uid
                emailAttr: mail
                nameAttr: cn
              groupSearch:
                baseDN: 'ou=Users,o=...,dc=jumpcloud,dc=com'
                filter: (objectClass=groupOfNames)
                userAttr: dn
                groupAttr: member
                nameAttr: cn
              insecureNoSSL: true

    ...and redeployed the `tectonic-identity` deployment...

1. Try login with a LDAP user `magnus` in the console

    Works like a charm :-)

1. Setup kubeconfig for the LDAP user

    Downloads `kubectl-config` the standard way and setup the environment variable `KUBECONFIG`.

1. Try a kubectl read operation (fails on no-priv)

        $ kubectl get namespace
        Error from server (Forbidden): User "magnus.larsson.ml@gmail.com" cannot list namespaces at the cluster scope. (get namespaces)

1. Bind the clusterrole `view` to the LDAP user

        $ kubectl create clusterrolebinding cluster-viewer-binding --clusterrole=view --user=magnus.larsson.ml@gmail.com

1. Try a kubectl read operation (works)

        $ kubectl get namespace
        NAME              STATUS    AGE
        default           Active    4h
        kube-public       Active    4h
        kube-system       Active    4h
        tectonic-system   Active    4h          

1. Remove the cluterrolebinding  for the LDAP user

        $ kubectl delete clusterrolebinding cluster-viewer-binding

1. Bind the clusterrole view to a LDAP group that LDAP user belongs to

        $ kubectl create clusterrolebinding cluster-viewer-binding --clusterrole=view --group=cluster-viewers

1. Try a kubectl read operation (fails on no-priv, expected it to succeed)

        $ kubectl get namespace
        Error from server (Forbidden): User "magnus.larsson.ml@gmail.com" cannot list namespaces at the cluster scope. (get namespaces)

### Other Information

Logs from the tectonic-identity pods:

        $ kubectl -n tectonic-system logs tectonic-identity-2868094004-kfxpv

        time="2018-02-01T11:48:53Z" level=info msg="performing ldap search ou=Users,o=...,dc=jumpcloud,dc=com sub (&(objectClass=inetOrgPerson)(uid=magnus))" connector=ldap
        time="2018-02-01T11:48:53Z" level=info msg="username \"magnus\" mapped to entry uid=magnus,ou=Users,o=...,dc=jumpcloud,dc=com" connector=ldap
        time="2018-02-01T11:48:53Z" level=info msg="login successful: connector \"tectonic-ldap\", username=\"Magnus Larsson\", email=\"magnus.larsson.ml@gmail.com\", groups=[]"

The output from the log seems to indicate that Tectonic doesn't succeed with connecting the LDAP user to the LDAP groups it belongs to.

Have I configured the LDAP connector incorrectly or what could be the cause?

**Comment by kbrwn** [comment]
@magnus-larsson LDAP functionality is mainly used/tested with Active Directory ldap. 
 I think that this is a Jumpcloud specific issue and relates to their implementation of LDAP groups as OpenLDAP does not have groups by default.

**Comment by magnus-larsson** [comment]
Thanks, took a while to get access to a MS AD to try it out.
Works fine when used with a MS AD LDAP server!
