### ISSUE TITLE
Master HA setup not working

### ISSUE THREAD

**Issue by yuko11** [coreos/tectonic-forum#268]
### Tectonic Version 
tectonic_1.8.4-tectonic.3

### Environment
What hardware/cloud provider/hypervisor is being used with Tectonic?
VMware (installed by terraform with platforms/metal)

### Expected Behavior
When shutdown 1 of the 3 master nodes, Tectonic Console continue to work properly
### Actual Behavior
When shutdown 1 of the 3 master nodes, Tectonic Console stop working. Behaviour depends on what master node to shutdown.
### Reproduction Steps

  1. Fresh installed cluster, using load balancer in front, according to the below article:
https://coreos.com/tectonic/docs/latest/reference/f5-ltm-lb.html
  2. Use VMware (installed by terraform with platforms/metal).
  3. Use default config (3 masters with etcd) and 3 workers
  4. Shutdown 1 master, see that Tectonic console not working anymore, frontend stuck  on "Loading your Tectonic Console" message. Turn on master node again, successfully fixing the issue.
  5. Shutdown second master node (first one turned on), cause worker nodes stop replying to F5 loadbalancer for service Tectonic Console, console becomes unavailable.
  6. "kubectl get nodes" showing all nodes ready even passing a long time after node shutdown.

**Comment by kbrwn** [comment]
@yuko11 

As etcd is running on the master nodes, shutting down a single node could cause issues if there is any connection loss or other types of failure between the remaining etcd/master nodes. 

Shutting down a node is a bit vague. In kubernetes land it should be noted that the default response node that is simply powered down or rebooted is to assume that all pods will remain and become available again on the next boot. Pods on a unavailable node will not be rescheduled until the `--pod-eviction-timeout` is exceeded. This timeout defaults to 5 minutes and these pods can be delayed if there is no node with a matching label/selector or with available resource capacity. 

It is suggested to issue a `kubectl drain` on a node before shutdown. This will ensure that the pods on this node are rescheduled and that no new pods will be scheduled on the node as resources become available. 

https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/#maintenance-on-a-node

**Comment by yuko11** [comment]
Thanks for the explanation. I was testing master HA in case of failure, that's why didn't drain node.
