### ISSUE TITLE
Tectonic for Kubernetes v1.9

### ISSUE THREAD

**Issue by krish7919** [coreos/tectonic-forum#269]
We are waiting for support of network load balancers in AWS on our Kubernetes cluster.
This is currently in beta in k8s v1.9.

Any idea when is Tectonic going to support it?

### Environment
AWS

**Comment by kbrwn** [comment]
@krish7919 Support for kubernetes 1.9 is planned for release mid-march.

**Comment by rushins** [comment]
hi any updates ..its May already and i dont see Tectonic 1.9 is available yet. lot of confusion also going circles with Redhat acqusition where the  tectonic going to be.

**Comment by robszumski** [comment]
Hi everyone, [Tectonic 1.9.6](https://coreos.com/tectonic/releases/#1.9.6-tectonic.1) is now available!
