### ISSUE TITLE
CoreOS account dependency

### ISSUE THREAD

**Issue by pierreozoux** [coreos/tectonic-forum#276]
As RedHat acquired CoreOS and RedHat [is commited to open source and is opposed to open core](https://www.redhat.com/en/blog/open-source-or-open-core-why-should-you-care), will the need for a CoreOS account be lifted for Tectonic?

Thanks!

**Comment by kbrwn** [comment]
@pierreozoux Nothing will change in regards to needing a CoreOS account to use Tectonic in the near term. Although this may change in the future.
