### ISSUE TITLE
installer stalls after STS security token included in the request is expired

### ISSUE THREAD

**Issue by davidc-donorschoose** [coreos/tectonic-forum#28]
### Tectonic Version
 
tectonic-1.5.1

### Environment

AWS

### Expected Behavior

When I created the tectonic-installer IAM role, I configured it to require an MFA token. Essentially, this involved modifying the aws-sts-trust-policy.json to add a Condition to enforce "aws:MultiFactorAuthPresent": true. Before I started using the tectonic-installer/darwin/installer, I use the AWI CLI to generate a temporary session token using my 2FA device (aws sts assume-role ... --token-code=[CURRENT-AUTHY-CODE]). I was able to get quite far through the installer, and all of the AWS resources began to be allocated and spun up. 

### Actual Behavior

But it stalled out, probably after exactly one hour. When the tectonic-installer got to the "Start Kubernetes" screen, an error shows up:

>  ! Starting AWS CloudFormation: The security token included in the request is expired

I am pretty sure that the temporary token expired after one hour, and I'm not sure how to restart this. This was the first pass through the tectonic-installer, so my cluster is partly up, probably not all up.
 
### Reproduction Steps

(See above)

**Comment by davidc-donorschoose** [comment]
## Update - Tried saving tectonic.progress, but am still stuck

I did save the "tectonic.progress" file and restarted the tectonic-installer sequence, after rerunning the "aws sts assume-role ..." command.

This got me most of the way through the Define Cluster screens, which were populated with my original choices -- very promising.

But the "Submit Definition" button failed:

> Failed to submit definition: RecordSet for "dctest-k8s.dctest.aws..............org" already exists in Hosted Zone "dctest.aws..............org."

I cannot get to the Boot Cluster screens.

**Comment by davidc-donorschoose** [comment]
## Workaround - Delete the AWS CloudFormation stack, then start over

I was able to start over with the tectonic-installer by deleting the CloudFormation stack through the AWS CloudFormation console (https://console.aws.amazon.com/cloudformation/). There seem to be 51 separate resources, and not all of the names were clearly related to Tectonic. So it was a relief to realize they could all be deleted with one action on their CloudFormation (http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CleaningUp.html#cleanup-CFN-stack).

## Suggestion

Add this to the "Known issues and gotchas in Tectonic installation on AWS" (https://coreos.com/tectonic/docs/latest/install/aws/troubleshooting.html). Note that I was specifically using MFA as a security feature, which was a deviation from the usual Tectonic installation instructions. However, other folks are probably going to do the same, especially if they are trying out Tectonic in an organization already using AWS with established security procedures.

**Comment by mfburnett** [comment]
hey @davidc-donorschoose - thanks for filing this issue and documenting your workaround. I've passed this along to the docs team to add to our known gotchas. Will comment back here when it is added.

**Comment by radhikapc** [comment]
I am working on it, please assign this defect to me.

**Comment by mfburnett** [comment]
@radhikapc will do!

**Comment by joshix** [comment]
https://coreos.com/tectonic/docs/latest/install/aws/troubleshooting.html#tectonic-installer-stalls-if-the-sts-security-token-expires-during-a-session
