### ISSUE TITLE
Adding container registry policy to instance IAM roles

### ISSUE THREAD

**Issue by aknuds1** [coreos/tectonic-forum#286]
### Tectonic Version 
1.8.7-tectonic.2

### Environment
AWS

### Request
I'd like for Tectonic on AWS to automatically configure instance IAM roles with the necessary permissions to pull images from the EC2 Container Registry. The kops tool does this if you enable the `iam.allowContainerRegistry` flag as you can read [here](https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md#iam-roles). If this isn't done, it's not possible to pull images from one's private ECR.

**Comment by sym3tri** [comment]
Hi @aknuds1 
We only default to the least permissive policies. If you'd like to customize these you can by creating your own Roles and providing those Role names to the installer.

**Comment by aknuds1** [comment]
@sym3tri OK thanks, then I know what to do at least.
