### ISSUE TITLE
Tectonic 1.8.9-tectonic.1 subPath unmount issue

### ISSUE THREAD

**Issue by yuko11** [coreos/tectonic-forum#292]
### Tectonic Version 
Tectonic 1.8.9-tectonic.1 and Tectonic 1.8.7-tectonic.2
### Environment
Bare metal
What hardware/cloud provider/hypervisor is being used with Tectonic?
VMware
### Expected Behavior
Pods with subPath successfully removed
### Actual Behavior
Pods with subPath are not removed and stuck in Terminating state, logs said can't get container status
### Reproduction Steps

  1. In Tectonic 1.8.9-tectonic.1, use subPath for volumeMounts in Deployment.
  2. Try to remove Pod and see it stuck in terminating state.
  3. For version Tectonic 1.8.7 it was working fine, also I have manage to replicate the issue updating Tectonic from 1.8.7 to 1.8.9 on other cluster.
  4. Try to remove subPath from volumeMounts and try to delete Pod, see that it fixes the issue and Pod removed successfully. 
  5. Pod force delete is working fine in both versions.

### Other Information
Seems to be the issue with deleting Pod is due to unmount failure.

**Comment by HBO2** [comment]
@yuko11 i have exactly the same issue. From my point of view it also influences the creation time of a pod.

I am using a trick to get them out of terminating loop by setting the grace-period to ¨0¨

**Comment by rendhalver** [comment]
I am having the same problem.
Any chance this will get fixed any time soon?

**Comment by yuko11** [comment]
I saw reply to the issue with similar description, saying with next release early April.

**Comment by rendhalver** [comment]
Which issue @yuko11 ?

**Comment by robszumski** [comment]
Same issue as https://github.com/coreos/tectonic-forum/issues/290

**Comment by rendhalver** [comment]
Define Early April.

**Comment by robszumski** [comment]
Hi folks, apologies for the delay but [Tectonic 1.9.6](https://coreos.com/tectonic/releases/#1.9.6-tectonic.1) has been released to the pre-production channel and should fix this issue. Please report back if you do or don't see a change in behavior.

1.9.6 will be pushed to the production channel after baking in pre-prod.

**Comment by rendhalver** [comment]
Thanks @robszumski
