### ISSUE TITLE
Container Linux upgrade not finishing

### ISSUE THREAD

**Issue by rendhalver** [coreos/tectonic-forum#293]
### Tectonic Version 
Tectonic 1.8.9-tectonic.1

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
Bare metal

### Expected Behavior

Container linux upgrade should finish.

### Actual Behavior

It is stuck upgrading one node in our cluster.

<img width="778" alt="screen shot 2018-04-10 at 15 38 26" src="https://user-images.githubusercontent.com/1026337/38579516-42738262-3cd5-11e8-97e0-4aa8eaa5dfbc.png">

### Reproduction Steps

  1. ...
  2. ...

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by rendhalver** [comment]
The worker that is waiting to upgrade has this in the logs:
```
I0411 05:39:56.226974 1 agent.go:120] Waiting for ok-to-reboot from controller... W0411 06:17:00.084748 1 agent.go:126] error waiting for an ok-to-reboot: waiting for annotation "container-linux-update.v1.coreos.com/reboot-ok" failed: watch closed before Until timeout ```

Any ideas on how to fix this?

**Comment by lucab** [comment]
Hi and thanks for the report. Sorry for the breakage, it looks like there may be a regression in latest kubernetes release related to the scheduling of some pods.

Can you please check in the journal of the stuck node if the kubelet is logging any error about `failed to prepare subPath for volumeMount \"runtime-mappings-cm\" of container \"update-agent\"`?

**Comment by rendhalver** [comment]
Ah I thought it was related to the issue I reported earlier.

**Comment by rendhalver** [comment]
We managed to resolve the issue manually by redeploying the torcx daemonsets.

**Comment by robszumski** [comment]
Hi folks, apologies for the delay but [Tectonic 1.9.6](https://coreos.com/tectonic/releases/#1.9.6-tectonic.1) has been released to the pre-production channel and should fix this issue. Please report back if you do or don't see a change in behavior.

1.9.6 will be pushed to the production channel after baking in pre-prod.

**Comment by rushins** [comment]
hi 
i hit the same issue on 1.9.6 and my nodes reboots off and on ? this makes the cluster inaccessable some times ?  i am running 1.9.6-tectonic.1 and my channel is 1.9.6 ? can someone please let me know the fix.

**Comment by rushins** [comment]
hello @rendhalver : can you provide the steps how to do torcx daemonsets steps you were able to resolve using  torcx daemonsets.

**Comment by rendhalver** [comment]
We stopped using tectonic a while ago.
I will try and find the steps we used to resolve this and get back to you.

**Comment by rushins** [comment]
thank you. @rendhalver 👍

**Comment by rushins** [comment]
hi @rendhalver : any help . all our nodes getting frequent reboots due to this container linux updates and this cause some delay of our tests as cluster is not healthy for workloads.

can you help to send the steps. 
@robszumski : Any updates from you how to fix this.

**Comment by rushins** [comment]
@rendhalver : I found this link relates to torcx demonsets ? does this procedure helps 
https://github.com/coreos/tectonic-forum/issues/235

**Comment by rushins** [comment]
@robszumski: Did you get a chance to look on this . we still have issues and nodes rebooting due to container linux upgrade is in this stage when i see from tectonic console cluster settings  "Download and finalize updates" --> 
Apply Container Linux updates --> Queued for Update (3 of 4) --> Reboot Success (1 of 4)
can you help.

**Comment by dirkmoors** [comment]
+1 same issue happening here!
