### ISSUE TITLE
kubernetes 1.9

### ISSUE THREAD

**Issue by rushins** [coreos/tectonic-forum#298]
## Issue Report Template
upgrade from 1.8.4 to 1.9
### Tectonic Version 
1.9

### Environment
baremetal
What hardware/cloud provider/hypervisor is being used with Tectonic?
physical 
### Expected Behavior
how to upgrade
### Actual Behavior
nothing available for upgrade
### Reproduction Steps

  1. ...does 1.8.4 supports upgrade to 1.9
  2. ...1.9 revision is not available in tectonic 

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by robszumski** [comment]
Hi there, [Tectonic 1.9.6](https://coreos.com/tectonic/releases/#1.9.6-tectonic.1) is now available!
