### ISSUE TITLE
Unclear where to find/create AWS ssh keys when running Tectonic's AWS setup

### ISSUE THREAD

**Issue by dpritchett** [coreos/tectonic-forum#3]
### Tectonic Version 
```sh
> darwin/installer --version
1.4.5-tectonic.1
```

### Environment
OSX El Capitan ☠️ 

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS 

### Expected Behavior
Me knowing how to find and manage the keys that the little refresh button is looking for

### Actual Behavior
Me asking in IRC after googling for 20 minutes

### Reproduction Steps

![image](https://cloud.githubusercontent.com/assets/147981/21110324/691460c6-c062-11e6-857c-122c87c42ba1.png)

### Other Information

The current solution is to dig around in the EC2 panel on AWS until you find the key management options.  Nothing on the relevant tectonic screen quite hinted in that direction:

![image](https://cloud.githubusercontent.com/assets/147981/21110434/c8639164-c062-11e6-97ba-5c80f60f636b.png)

hi @pgburt!  👋 

thanks @robszumski 🤗

**Comment by mfburnett** [comment]
hey @dpritchett, thanks for filing this issue! Yes, we absolutely should have clearer directions on where to find the SSH keys. We can build some documentation for it and add a note in the installer.

**Comment by joshix** [comment]
https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#ssh-key

**Comment by dpritchett** [comment]
Looks reasonable to me. I can't remember what it said before :P
