### ISSUE TITLE
Disable updates  

### ISSUE THREAD

**Issue by patrickmuhi** [coreos/tectonic-forum#302]
### Tectonic Version 
1.9.6-tectonic.1 and 1.8.9-tectonic.2
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS
### Expected Behavior
Updates shouldn't stop a productive cluster
### Actual Behavior
All my worker nodes shut down completely, I've never had a successful update, I had to re-install tectonics again.
### Reproduction Steps

  1. Run tectonics
  2. Let it update

### Other Information
Is it normal for tectonics to close all it's worker node when updating?
## Feature Request
How do I disable updates, it's very bad, I don't want it to update it's so annoying.
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS
### Desired Feature
Disable updates and only trigger them when I want, **Require admin approval for Container Linux updates** don't work, it updates itself whatsoever

**Comment by IvanCherepov** [comment]
One way of disabling auto reboots is described in https://support.coreos.com/hc/en-us/articles/115001299613.

**Comment by ghost** [comment]
@IvanCherepov that sounds like a hacky workaround. Why would it be so difficult to require an admin approval or at the very least a configurable update window option? This is a huge blocker for moving to production and without a suitable solution it even is causing tools and workloads on dev clusters to fail.
