### ISSUE TITLE
apiserver.cer expired

### ISSUE THREAD

**Issue by esselfour** [coreos/tectonic-forum#304]
### Tectonic Version 
1.6.10
### Environment
Baremetal
What hardware/cloud provider/hypervisor is being used with Tectonic?
Virtual Machines
### Expected Behavior
Console Appears
### Actual Behavior
Nginx 502 error + Chrome shows HST error.
Kubectl reports - error: error fetching provider config: Get https://tectontic<xxx>/identity/.well-known/openid-configuration: x509: certific
ate has expired or is not yet valid.
### Reproduction Steps
1. kubectl <any command> see above error
2. Tectonic Console fails to load.
3. The cert has expired

  
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

### Other Information

Need some pointers more than anything else, it seems the apiserver.crt has expired? What are the steps to replace this safely? Thankyou!

**Comment by IvanCherepov** [comment]
Please follow [TLS Certificate Rotation in Tectonic](https://coreos.com/tectonic/docs/latest/tls/rotate-tls.html).

**Comment by esselfour** [comment]
Hi Ivan..Apologies but I am a little lost on this article. Which step in particular to follow?

**Comment by IvanCherepov** [comment]
You should follow all steps.

**Comment by rushins** [comment]
had the same issue in tectonic 1.8 cluster "Unable to connect to the server: x509: certificate has expired or is not yet valid". Since this tectonic method how to fix this.
