### ISSUE TITLE
Document whether cluster nodes should always boot using PXE more clearly

### ISSUE THREAD

**Issue by urzds** [coreos/tectonic-forum#33]
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

bare-metal

### Desired Feature

It is currently unclear to me whether cluster nodes should always boot using PXE, or only during the installation, when first booting after running the Tectonic Installer. it would be nice if the documentation could be more clear on that.

### Other Information

Reading the [bare-metal](https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html) and [network-setup](https://coreos.com/tectonic/docs/latest/install/bare-metal/network-setup.html) documentation, it is obvious that the nodes have to be initially booted using PXE, but not what should happen afterwards. The installer mentions that "Container Linux is downloaded and installed to disk", but not whether the nodes should directly boot from there or still through PXE.

I.e. does Matchbox somehow distinguish between already provisioned nodes and fresh ones, when handing out the Ignition configs? How does it boot from PXE into the installed environment on disk for provisioned nodes? Or should I disable PXE booting after the installation? Or does Tectonic automatically switch of PXE boot after installing CoreOS Container Linux?

**Comment by mfburnett** [comment]
Hey @urzds - thanks for your recommendations around documentation for installing Tectonic on bare metal! I've passed these along to our docs team, who will make sure to review + update our documentation accordingly.

**Comment by dghubble** [comment]
It is ultimately up to the user whether to configure their hardware to boot from disk (except when re-provisioning) or to always-PXE, depending on their needs.

Booting from disk should be the default. Its simple, widely used, and just works with auto-updates, I recommend it to most people. If you prefer to network boot each time, just have a plan for serving the latest CoreOS version to nodes.

**Comment by urzds** [comment]
@mfburnett Thanks for passing this on!

@dghubble Is this recommendation included in the documentation?

**Comment by mfburnett** [comment]
@urzds it is not in our documentation, but we'll make sure to add it. thanks for bringing this up!

**Comment by joshix** [comment]
https://coreos.com/tectonic/docs/latest/install/bare-metal/requirements.html#machines-1

closed in https://github.com/coreos-inc/tectonic/pull/1399/files
