### ISSUE TITLE
AWS Cloudformation Stack Creation Fails

### ISSUE THREAD

**Issue by lattwood** [coreos/tectonic-forum#40]
### Tectonic Version 

Latest

### Environment

AWS

### Expected Behavior

Lovely green `CREATE_COMPLETE` for every item in the CloudFormation stack Events list.

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/6198952/22471652/5a45565e-e7a9-11e6-8011-9f9d6cd0ba48.png)
![image](https://cloud.githubusercontent.com/assets/6198952/22471699/88c5aa6a-e7a9-11e6-90be-419ec16d0910.png)

### Reproduction Steps

1. Attempt to install Tectonic on AWS

**Comment by dghubble** [comment]
What version are you using? v1.5.2?

**Comment by sym3tri** [comment]
Have you confirmed you have all the required permissions as documented here: https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#privileges ?

**Comment by mfburnett** [comment]
hey @lattwood - did you end up getting this issue resolved?

**Comment by mfburnett** [comment]
With Tectonic 1.6.2-tectonic.1, we're now using Terraform instead of CloudFormation. Closing this issue!
