### ISSUE TITLE
Cannot set flannel public IP in 1.5

### ISSUE THREAD

**Issue by InAnimaTe** [coreos/tectonic-forum#41]
### Tectonic Version 

1.5.2-tectonic.1

### Environment

* 1x Controller Node is VPS with public IPv4 Address (Vultr allows for iPXE endpoints)
* 1x Worker Node (bare-metal) behind NAT address (so interface has internal IP but has to be accessed via external public IP)

### Current Status

My cluster is 3/4 of the way created; Hanging at `Waiting for Kubernetes components.` via a `journalctl`
Presumably, this is because flannel is having a heart attack over the worker node IP.

Pre-1.5, you just needed something like:

```
$ cat /etc/systemd/system/flanneld.service.d/10-custom.conf  
[Service]
Environment="FLANNELD_PUBLIC_IP=1.2.3.4"
```
Now, it seems flannel is running as a DaemonSet, which makes configuring it a bit harder.

#### What I've Tried

I took a look at its yaml config and see that it takes some configuration from (on the host) `/etc/kubernetes/cni/net.d`, but that config seems to be specific to what it provides, not core configuration like `--public-ip`:

```
worker net.d # cat 10-flannel.conf
{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
```

Additionally, I tried doing an edit on the DaemonSet directly to add the `--public-ip` option to the command using:

```
kubectl edit ds/kube-flannel -n kube-system
```

Unfortunately, I get a `Invalid value: "The edited file failed validation": the server does not allow access to the requested resource` :(

**Is there another way to achieve what I'm trying to do in this new flannel deployment model? Or, what am I doing wrong?**

### Outputs

Some details to show what's going on. Let me know if you'd like more to help diagnose.

```
└[~]> kubectl get ds -n kube-system -o wide
NAME                   DESIRED   CURRENT   READY     NODE-SELECTOR   AGE       CONTAINER(S)               IMAGE(S)                                                                   SELECTOR
checkpoint-installer   1         1         1         master=true     21h       checkpoint-installer       quay.io/coreos/pod-checkpointer:5b585a2d731173713fa6871c436f6c53fa17f754   k8s-app=pod-checkpoint-installer
kube-apiserver         1         1         1         master=true     21h       kube-apiserver             quay.io/coreos/hyperkube:v1.5.2_coreos.1                                   k8s-app=kube-apiserver
kube-flannel           2         2         1         <none>          21h       kube-flannel,install-cni   quay.io/coreos/flannel:v0.7.0-amd64,busybox                                app=flannel,tier=node
kube-proxy             2         2         2         <none>          21h       kube-proxy                 quay.io/coreos/hyperkube:v1.5.2_coreos.1                                   k8s-app=kube-proxy

```

```
└[~]> kubectl get pods -n kube-system        
NAME                                                READY     STATUS              RESTARTS   AGE
checkpoint-installer-9dm3l                          1/1       Running             0          21h
kube-apiserver-wcjnw                                1/1       Running             3          21h
kube-controller-manager-3654003418-vdl6b            0/1       ContainerCreating   0          21h
kube-controller-manager-3654003418-xjmfv            1/1       Running             0          21h
kube-dns-4101612645-rsffh                           0/4       ContainerCreating   0          21h
kube-flannel-2x4j5                                  2/2       Running             0          21h
kube-flannel-rcwps                                  1/2       CrashLoopBackOff    257        21h
kube-proxy-71stj                                    1/1       Running             0          21h
kube-proxy-ddcvb                                    1/1       Running             0          21h
kube-scheduler-850181384-1n4mr                      0/1       ContainerCreating   0          21h
kube-scheduler-850181384-kkcb9                      1/1       Running             0          21h
pod-checkpointer-tectonic-controller-01.arroyo.io   1/1       Running             0          21h

```

```
└[~]> kubectl get ds/kube-flannel -n kube-system -o wide  
NAME           DESIRED   CURRENT   READY     NODE-SELECTOR   AGE       CONTAINER(S)               IMAGE(S)                                      SELECTOR
kube-flannel   2         2         1         <none>          21h       kube-flannel,install-cni   quay.io/coreos/flannel:v0.7.0-amd64,busybox   app=flannel,tier=node

```

**Comment by ericchiang** [comment]
```
Invalid value: "The edited file failed validation": the server does not allow access to the requested resource
```

Kubectl edit acts funny when you try to edit a field with a "status" field. Can you remove that and see if the edit works? (you'll definitely want to back up the manifest before doing so)

Can you elaborate on why you need to set this flag? Does it choose the wrong network interface by default?

**Comment by InAnimaTe** [comment]
Removing the status section didn't seem to made any difference ;(

The reason this option needs to be changed is because this box is behind a NAT gateway (although all traffic flows through it). This means the IP of its "public" interface is not its actual IP address, and as I'm aware and was necessary in previous versions, I need to make flannel aware of that.

**Comment by ericchiang** [comment]
daemonsets should be editable. Maybe try something like this?

```
$ kubectl get daemonsets -n kube-system kube-flannel -o yaml > flannel.yaml
$ vim flannel.yaml 
$ kubectl replace -f flannel.yaml 
daemonset "kube-flannel" replaced
```

For self-hosted flannel we're using bootkube's[0] implementation. If there are absolutely no work around you may go ask them.

[0] https://github.com/kubernetes-incubator/bootkube

**Comment by InAnimaTe** [comment]
```
└[~/arrovenv/inflow-tectonic]> kubectl replace -f flannel.yaml 
error: error validating "flannel.yaml": error validating data: the server does not allow access to the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
(arrovenv) ┌[mloria@lovell] [master ⚡] [1]
└[~/arrovenv/inflow-tectonic]> kubectl replace -f flannel.yaml --validate=false
daemonset "kube-flannel" replaced
```

**Comment by philips** [comment]
@InAnimaTe just be aware you need to kill the pods, daemonset edits don't change the running instances.

**Comment by InAnimaTe** [comment]
@philips thx.

Is there a way to set this option for only pod's deployed on a particular host? I only need this for one of the hosts, not both. (playing around with it atm)

**Comment by alekssaul** [comment]
Had a discussion with @InAnimaTe over slack this afternoon. Doesn't sound like he has time to continue troubleshooting however adding our discussion points in-case someone else requires the information.

Based on my research, flannel configuration that has traditionally reside on etcd "/coreos.com/networking" is implemented via kubernetes annotations on the nodes when flannel is self-hosted. 
```
kubectl get nodes -o json | jq '.items[].metadata.annotations'
{
  "flannel.alpha.coreos.com/backend-data": "{\"VtepMAC\":\"76:a1:98:8f:f2:6f\"}",
  "flannel.alpha.coreos.com/backend-type": "vxlan",
  "flannel.alpha.coreos.com/kube-subnet-manager": "true",
  "flannel.alpha.coreos.com/public-ip": "10.0.0.50",
  "node-agent.v1.coreos.com/current-kubelet-image": "quay.io/coreos/hyperkube:v1.5.2_coreos.1",
  "volumes.kubernetes.io/controller-managed-attach-detach": "true"
}
```

My recommendation was to change host annotation for `flannel.alpha.coreos.com/public-ip` to the public IP address. The code [0], has some sync events which may automatically override these values, so I am not certain if this will resolve the issue.

[0] https://github.com/coreos/flannel/blob/master/subnet/kube/kube.go

**Comment by InAnimaTe** [comment]
Yeah I want to thank @alekssaul for his input on this. Like he said, I don't exactly have the time atm but hopefully soon. For now, I'm going to close this issue. I will comment further about my findings.

I'd really like to see more documentation around topics relating to minor configuration to make varying environments work properly. The way Tectonic is setup now, everything is very one-track which is off-putting. 

Thanks for the help guys!
