### ISSUE TITLE
404 on deployer guide

### ISSUE THREAD

**Issue by AndrewDryga** [coreos/tectonic-forum#44]
https://coreos.com/tectonic/docs/latest/deployer/tectonic_console.html

**Comment by ericchiang** [comment]
Sorry, what page and content were you expecting?

**Comment by AndrewDryga** [comment]
Official docs have bunch of links to this page. In past, it had description and yaml files for tectonic console. Look at bottom left of this screenshot.

<img width="1440" alt="2017-02-03 19 42 18" src="https://cloud.githubusercontent.com/assets/1877644/22601734/fab2fd3e-ea48-11e6-9813-c2886b524a29.png">

**Comment by ericchiang** [comment]
Hmmm,"starter" was a offering we've phased out. How did you get there? Do you have that page bookmarked or something?

I'd recommend this link for setting up your cluster https://coreos.com/tectonic/docs/latest/. You should be 404 free if you use the material there.

Sorry for the dead links. We'll have someone look into that.

**Comment by AndrewDryga** [comment]
<img width="1440" alt="2017-02-03 20 17 24" src="https://cloud.githubusercontent.com/assets/1877644/22602899/ce7b813c-ea4d-11e6-8da6-a9552b76fa18.png">

So it's not possible to use Tectonic Console as alternative GUI for existing Kubernetes cluster any more?

**Comment by mfburnett** [comment]
Hi @AndrewDryga, we're in the process of phasing out Tectonic Starter (and have replaced it with the ability to grab Tectonic today for free up to 10 nodes!). So yes - you won't be able to use Tectonic Console as an alternative GUI for an existing Kubernetes cluster anymore. In a few weeks, we'll send an official email to our Tectonic Starter users about the phase out and next steps for them.

**Comment by robszumski** [comment]
I've restored these guides. They shouldn't have been dropped as we moved content over to coreos.com.

https://coreos.com/tectonic/docs/latest/starter/

Thank you for reporting.
