### ISSUE TITLE
Install stuck on 'Starting Tectonic components' 

### ISSUE THREAD

**Issue by fii** [coreos/tectonic-forum#45]
Hello, 

GUI seems to be stuck on 'Starting Tectonic Components' 

Feb 08 19:18:39 ip-10-0-0-50 bootkube-start[2386]: Waiting for Kubernetes components...
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Heapster
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Namespace
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Initial Roles
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic ConfigMap
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Secrets
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Identity
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Console
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Monitoring
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Ingress
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Stats Emitter
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Creating Tectonic Updater
Feb 08 19:18:49 ip-10-0-0-50 bootkube-start[2386]: Waiting for third-party resource definitions...
Feb 08 19:18:52 ip-10-0-0-50 bootkube-start[2386]: Waiting for third-party resource definitions...
Feb 08 19:18:55 ip-10-0-0-50 bootkube-start[2386]: Waiting for third-party resource definitions...
Feb 08 19:18:58 ip-10-0-0-50 bootkube-start[2386]: Waiting for third-party resource definitions...
Feb 08 19:18:58 ip-10-0-0-50 bootkube-start[2386]: Done

![image](https://cloud.githubusercontent.com/assets/1127598/22753636/b8945ea8-ee34-11e6-82a8-88567e91ac07.png)

Can you help please ..

Thanks

**Comment by mfburnett** [comment]
Hey @fii, thanks for filing this issue! It's a little confusing, but it's not actually stuck - you need to download the assets and run those commands. Let me know once you do that step if you see your console!

**Comment by fii** [comment]
@mfburnett We've tried that several times and its still the same.  After scp'ing the files its just sits there and dies nothing .

**Comment by pompomJuice** [comment]
lol, my tectonic installer does not show me that I need to run those commands.

Unlucky I guess.

**Comment by fii** [comment]
bootkube.service - Bootstrap a Kubernetes control plane with a temp api-server
   Loaded: loaded (/etc/systemd/system/bootkube.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-02-09 20:23:42 UTC; 1s ago
  Process: 28964 ExecStart=/opt/bootkube/assets/bootkube-start (code=exited, status=255)
 Main PID: 28964 (code=exited, status=255)

Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.328781] bootkube[5]: E0209 20:23:42.486630       5 server.go
Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.341833] bootkube[5]: I0209 20:23:42.499608       5 leaderele
Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.354518] bootkube[5]: I0209 20:23:42.512359       5 leaderele
Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.453047] bootkube[5]: [restful] 2017/02/09 20:23:42 log.go:30
Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.453424] bootkube[5]: [restful] 2017/02/09 20:23:42 log.go:30
Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.507586] bootkube[5]: I0209 20:23:42.665383       5 serve.go:
Feb 09 20:23:42 ip-10-0-0-50 bootkube-start[28964]: [ 1286.508070] bootkube[5]: F0209 20:23:42.665900       5 genericap
Feb 09 20:23:42 ip-10-0-0-50 systemd[1]: bootkube.service: Main process exited, code=exited, status=255/n/a
Feb 09 20:23:42 ip-10-0-0-50 systemd[1]: bootkube.service: Unit entered failed state.
Feb 09 20:23:42 ip-10-0-0-50 systemd[1]: bootkube.service: Failed with result 'exit-code'.
~
~
~
~
~
~
~

**Comment by fii** [comment]
@pompomJuice your point is ? Does one need luck to evaluate a product ?

**Comment by pompomJuice** [comment]
@fii have you done chmod +x /opt/bootkube/assets/bootkube-start?

That looks like it just dies. Run it manually paste the logs.

**Comment by mfburnett** [comment]
hey @pompomJuice - what version of Tectonic are you running? Thanks!

@fii - looking into your issue today. Will post back here soon.

**Comment by fii** [comment]
@mfburnett [fii@laptop linux]$ ./installer -version
1.5.2-tectonic.1
[fii@laptop linux]$ 

Thanks.

**Comment by colhom** [comment]
@fii this looks an issue with the tectonic updater third party resources not initializing correctly. Assuming you still have access to the affected cluster, could you ssh into the master node and curl the following endpoints.

* `http://127.0.0.1:8080/apis/coreos.com/v1/channeloperatorconfigs`
* `http://127.0.0.1:8080/apis/coreos.com/v1/appversions`

I think the output will inform further debugging.

**Comment by pompomJuice** [comment]
@mfburnett Yes I am attempting the bare metal setup.

But I suspect these two issues should stay related because the issue that it points out is the same. Customer focus. early adopters have but days to take marketing material promises to results. 

Encountering scripts that have incorrect paths in them really breaks our opinion of how streamlined this evaluation period is going to be.

Just have your engineers try to run through the installation documentation steps and fix the little niggles.

For example, why must I copy the assets to /opt/bootkube manually when tectonic can give that config to matchbox's ignition config and so deploy it for me? That is what I expected would happen so when I heard that I have to copy it manually I was like... how should I have guessed that??

**Comment by fii** [comment]
@colhom 

Here you go ... 

ip-10-0-0-50 core # curl http://127.0.0.1:8080/apis/coreos.com/v1/channeloperatorconfigs
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}ip-10-0-0-50 core # curl http://127.0.0.1:8080/apis/coreos.com/v1/appversions
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}ip-10-0-0-50 core # 



Thanks

**Comment by mfburnett** [comment]
thanks for the info, @fii - @colhom will get back to you after the weekend. 

I understand your frustration, @pompomJuice. We absolutely are working to improve the BM install process to address some of the issues you've been having. Would you mind breaking this out into a separate issue with an actionable bug report so we can focus on helping you without confusing those who may be coming to this issue for help? Going to take the bare metal label off this issue. Thanks!

**Comment by colhom** [comment]
@fii sorry to delay.

Could you try manually creating the TPRs that are missing?

```sh
  curl -H "Content-Type: application/yaml" -XPOST -d"$(cat assets/updater/tectonic-channel-operator-config-kind.yaml)" "http://127.0.0.1:8080/apis/extensions/v1beta1/thirdpartyresources"
  curl -H "Content-Type: application/yaml" -XPOST -d"$(cat assets/updater/app-version-kind.yaml)" "http://127.0.0.1:8080/apis/extensions/v1beta1/thirdpartyresources"

```

**Comment by fii** [comment]
Don't worry about it. Just close it.

**Comment by bartoszhernas** [comment]
Hi, I am having the same problem, trying to install on AWS:

The curl response:

```
core@ip-10-0-12-141 /opt/bootkube/assets $ curl http://127.0.0.1:8080/apis/coreos.com/v1/channeloperatorconfigs

{
	"kind": "ChannelOperatorConfigList",
	"items": [{
		"apiVersion": "coreos.com/v1",
		"appID": "6bc7b986-4654-4a0f-94b3-84ce6feb1db4",
		"automaticUpdate": false,
		"channel": "tectonic-1.5",
		"kind": "ChannelOperatorConfig",
		"metadata": {
			"name": "default",
			"namespace": "tectonic-system",
			"selfLink": "/apis/coreos.com/v1/namespaces/tectonic-system/channeloperatorconfigs/default",
			"uid": "9301755f-04f4-11e7-9934-0a3ae35ce943",
			"resourceVersion": "788",
			"creationTimestamp": "2017-03-09T18:16:54Z"
		},
		"server": "https://tectonic.update.core-os.net",
		"triggerUpdate": false,
		"triggerUpdateCheck": false,
		"updateCheckInterval": 2700
	}],
	"metadata": {
		"selfLink": "/apis/coreos.com/v1/channeloperatorconfigs",
		"resourceVersion": "152174"
	},
	"apiVersion": "coreos.com/v1"
}


core@ip-10-0-12-141 /opt/bootkube/assets $ curl http://127.0.0.1:8080/apis/coreos.com/v1/appversions
{
	"kind": "AppVersionList",
	"items": [{
		"apiVersion": "coreos.com/v1",
		"kind": "AppVersion",
		"metadata": {
			"name": "kubernetes",
			"namespace": "tectonic-system",
			"selfLink": "/apis/coreos.com/v1/namespaces/tectonic-system/appversions/kubernetes",
			"uid": "9308c303-04f4-11e7-9934-0a3ae35ce943",
			"resourceVersion": "790",
			"creationTimestamp": "2017-03-09T18:16:54Z",
			"labels": {
				"managed-by-channel-operator": "true"
			}
		},
		"spec": {
			"desiredVersion": "1.5.3+tectonic.1",
			"paused": false
		},
		"status": {
			"currentVersion": "1.5.3+tectonic.1",
			"paused": false
		}
	}, {
		"apiVersion": "coreos.com/v1",
		"kind": "AppVersion",
		"metadata": {
			"name": "tectonic-cluster",
			"namespace": "tectonic-system",
			"selfLink": "/apis/coreos.com/v1/namespaces/tectonic-system/appversions/tectonic-cluster",
			"uid": "930267f3-04f4-11e7-9934-0a3ae35ce943",
			"resourceVersion": "789",
			"creationTimestamp": "2017-03-09T18:16:54Z",
			"labels": {
				"managed-by-channel-operator": "true"
			}
		},
		"spec": {
			"desiredVersion": "1.5.3-tectonic.1",
			"paused": false
		},
		"status": {
			"currentVersion": "1.5.3-tectonic.1",
			"paused": false
		}
	}],
	"metadata": {
		"selfLink": "/apis/coreos.com/v1/appversions",
		"resourceVersion": "152198"
	},
	"apiVersion": "coreos.com/v1"
}

```

Tectonic version:

```
# bhernas @ BHMBP in ~/Downloads/tectonic/tectonic-installer [10:24:48]
$ ./darwin/installer --version
1.5.3-tectonic.1
```

**Comment by bartoszhernas** [comment]
I have reproduced it while trying to set up cluster on AWS in Ireland (eu-west), using t2.medium instances, with etcd set up by Tectonic (tried 1 instance and 3 instances)
