### ISSUE TITLE
The problem is.....

### ISSUE THREAD

**Issue by pompomJuice** [coreos/tectonic-forum#46]
That if you advertise software on the interwebs that does a lot of boostrapping from the internet and the software is borked (as in tectonic's case) then everyone is constantly nuking their cluster nodes and restarting them trying to figure out what the hell is going on.

That means download speeds for these nodes take weeks instead of days because everyone's clusters is failing and everyone is constantly restarting everything.

Make sure your stuff works before you release so that you don't cause ddos on these poor repo providers.

I have been trying to get a basic no brainer tectonic configured cluster going for days now... 99% of the time I am staring at a screen showing me download progress at mere bytes per second. The joys!

I could have invented my own tectonic by this time already.

**Comment by ericchiang** [comment]
We're happy to provide support for our free offering but there's not really an actionable bug report here.

What's your environment/provider? Is there a repo we're pulling too often? Or are your nodes themselves being rate limited because they're trying to pull too many Docker images?

**Comment by ericchiang** [comment]
Going to close this for now. Please feel free to open a new issue or comment on this one if you have a more actionable issue.
