### ISSUE TITLE
'FailedScheduling' no nodes available to schedule pods - baremetal and VM`s

### ISSUE THREAD

**Issue by Opswatch** [coreos/tectonic-forum#48]
### Tectonic Version 
1.5.2
### Environment
Baremetal
What hardware/cloud provider/hypervisor is being used with Tectonic?

### Expected Behavior
Install
### Actual Behavior
Stuck on launching bootkube
### Reproduction Steps

  1. Run installer
  2. Start bootkube

No matter what I try both in baremetal and VM always gets stuck with the following
controller.ops.local bootkube-start[1258]: [  277.613668] bootkube[5]: I0213 04:54:39.587936       5 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kube-scheduler-850181384-3xnkn", UID:"4373d6b1-f1a6-11e6-b09c-00155d01050a", APIVersion:"v1", ResourceVersion:"100", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods

On the controller when I do cluster health it only sees the controller
When i do it from the 2 nodes they only see the controller
Any ideas? - its almost like the controller does not see the nodes as being part of the cluster - they can all ping each other by dns with no issues - the installer reports all checks on power on step

**Comment by mfburnett** [comment]
Hey @Opswatch, thanks for filing this issue. This is @dghubble's domain, I'll ask him to take a look - he should be able to get back to you in a couple of days.

**Comment by dghubble** [comment]
Can you inspect the kublet flags (hostname-override) in use on worker nodes? Can you also inspect the kubeconfig  file on workers for the server field? The worker may be unable to register with the controller or be reporting a name that doesn't resolve. Those values are based on what you entered when completing the installer UI.

Its also if you're more specific about "when I do cluster health" and "they can ping each other by DNS".

**Comment by Opswatch** [comment]
For the controller i got controller.ops.local and for the nodes i got node1.ops.local and node2.ops.local i can ping both nodes from the controller by domain name and do the same from both nodes to each other 

and the controller, for cluster health I do etcdctl cluster-health - it says its healthy from both the controller and the nodes but it only sees the controller as a member.

How would i check the kublet flags and the kubeconfig file?

**Comment by dghubble** [comment]
```
systemctl cat kubelet
vim /etc/kubernetes/kubeconfig
```

If those names are correct, you might also try not using `*.local`. There have been various upstream issues about Kubernetes' use of the reservation. https://github.com/coreos/coreos-kubernetes/issues/658

**Comment by pompomJuice** [comment]
Tectonic 1.5.2 installer is a complete bug man.

Does not work at all forget it.

**Comment by Opswatch** [comment]
I switched to .com for the domain and redeployed - now im getting the same failed scheduling error plus tls handshake errors in the controller - i did check out the kubeconfig in the nodes and it does have the correct controller address - im going to put things on hold for now and switch over to kubeadm - shoulden`t be this hard to get a kubernetes cluster up :(

**Comment by pompomJuice** [comment]
Look at what I did [here](https://github.com/pompomJuice/matchbox/commit/a317eb632ba1a49c70febd0acb2aca379d6d174a#diff-201f741d2fdc5f1447d64a73631fe210)

I suspect that the key generations that are done for you don't work at all.

Replace all of my domain with all of your domain and feed that ca.crt and key to the installer. Then things will start working.
