### ISSUE TITLE
Install guides are unclear that Tectonic is pure Kubernetes

### ISSUE THREAD

**Issue by pgburt** [coreos/tectonic-forum#52]
### Environment

Baremetal

### Desired Feature

Make direct links to guides clear about Tectonic being 100% pure upstream Kubernetes.

https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html

### Other Information

I often link directly to Tectonic AWS installer or Tectonic Baremetal when I get questions about how to install Kubernetes. Why? Because the installer is so easy / good! 

I'm realizing that these docs may not make it clear that Tectonic is pure Kubernetes, though. Should we add a line to the top of the docs (or somewhere else) that clarifies that Tectonic is a pure implementation of k8s?

**Comment by dghubble** [comment]
Sure, want to open a PR?

**Comment by mfburnett** [comment]
Thanks @pgburt - we'll make sure to clarify that in our docs!

**Comment by ElijahCaine** [comment]
@pgburt Should we just repost this image?

![100% K8s](https://coreos.com/assets/images/svg/platform-features.svg)

(found on coreos.com/tectonic landing page)

**Comment by mfburnett** [comment]
Going to close this issue for now, as we've updated our docs to better clarify this.
