### ISSUE TITLE
AWS Cloudformation Stack too large to upload

### ISSUE THREAD

**Issue by samuelmasuy** [coreos/tectonic-forum#53]
### Tectonic Version 

Latest

### Environment

AWS

### Expected Behavior

AWS Cloudformation accepts Cloudformation Stack

### Actual Behavior

```at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200 400```

Same issue as reported here: https://github.com/coreos/kube-aws/issues/38

Their solution is to use S3 to upload the Cloudformation stack definition.

### Reproduction Steps

  1. Fill forms
  2. Submit Cloudformation stack definition

### Environment

MAC OSX

**Comment by Quentin-M** [comment]
Hi.

We are aware of this current limitation and are sorry it affects your experience with our installer. The workaround until we release a patch is to use an existing VPC.

Thank you.

**Comment by TimMeade** [comment]
My existing VPC (created by AWS) will not pass muster for some reason.  I cannot get past the installation page.

**Comment by brianstarke** [comment]
I'm having the same issue.  My manually created VPC doesn't seem to work.  I've got an internet gateway and the correct CIDR range.

**Comment by dghubble** [comment]
@brianstarke This is an area we're actively improving. You may want to use the next release (later this week) which will resolve both the CloudStack size issue and allow existing VPCs with custom CIDR ranges.

**Comment by nithin-bose** [comment]
@Quentin-M is there a way to get the cloud formation stack definition generated by the installer so we can try to upload it to s3 as suggested in the coreos/kube-aws#38?

**Comment by Quentin-M** [comment]
@nithin-bose Tectonic 1.5.3-tectonic.1 (released 03/02/2017) uploads the CF stack definition to S3 for you.

**Comment by nithin-bose** [comment]
@Quentin-M the aws installation guide still refers to tectonic-1.5.2-tectonic.2. Doc update pending?

**Comment by robszumski** [comment]
@nithin-bose It's up now, might have lagged by a few minutes: https://coreos.com/tectonic/docs/latest/
