### ISSUE TITLE
Not able to start matchbox service on ubuntu

### ISSUE THREAD

**Issue by Opswatch** [coreos/tectonic-forum#55]
### Tectonic Version 
Latest
### Environment
VM 
What hardware/cloud provider/hypervisor is being used with Tectonic?
Hyper-v
### Expected Behavior
Matchbox service should start
### Actual Behavior
Service does not start with error matchbox.service: Main process exited, code=exited, status=217/USER
### Reproduction Steps

  1. Setup ubuntu VM following the baremetal instructions - tried 15.10 / 16.04 and 16.10 
  2. Run the command sudo systemctl start matchbox

### Other Information
Worked fine on 1.5.2 as long as you copied the binaries to /usr/bin

**Comment by mfburnett** [comment]
Hey @Opswatch - thanks for filing this issue. I've let @ErnestG4 know; he'll get back to you in a few days and will pull in others from our team as necessary.

**Comment by dghubble** [comment]
What matchbox.service systemd unit file did you use? There is one for CoreOS (uses rkt) and one for generic Linux distros (calls the binary). You can check with `systemctl cat matchbox`.

**Comment by alekssaul** [comment]
Please also make sure that you've created the matchbox user with `sudo useradd -U matchbox` . Seems like 1.5.2-tectonic.2 documentation page has a rendering issue. 

Lines below are all applicable to Ubuntu.
----------------
##### Set Up User/Group

The `matchbox` service should be run by a non-root user with access to the `matchbox` data directory (`/var/lib/matchbox`). Create a `matchbox` user and group.
$ sudo useradd -U matchbox
$ sudo mkdir -p /var/lib/matchbox/assets
$ sudo chown -R matchbox:matchbox /var/lib/matchbox
----------------

**Comment by dghubble** [comment]
Install `matchbox` on the provisioner node. You need only choose one of the following options.

### CoreOS Container Linux

On a CoreOS Container Linux provisioner, run `matchbox` with the provided systemd unit.

```sh
$ sudo cp contrib/systemd/matchbox-for-tectonic.service /etc/systemd/system/matchbox.service
```

### General Linux

Pre-built binaries are available for general Linux distributions. Copy the `matchbox` static binary to an appropriate location on the provisioner node.

```sh
$ cd tectonic/matchbox
$ sudo cp matchbox /usr/local/bin
```

##### Set Up User/Group

The `matchbox` service should be run by a non-root user with access to the `matchbox` data directory (`/var/lib/matchbox`). Create a `matchbox` user and group.

```sh
$ sudo useradd -U matchbox
$ sudo mkdir -p /var/lib/matchbox/assets
$ sudo chown -R matchbox:matchbox /var/lib/matchbox
```

##### Create systemd Service

Copy the provided `matchbox` systemd unit file.

```sh
$ sudo cp contrib/systemd/matchbox.service /etc/systemd/system/
```

### RPM-based Distro

On an RPM-based provisioner, install the `matchbox` RPM from the Copr [repository](https://copr.fedorainfracloud.org/coprs/g/CoreOS/matchbox/) using `dnf`.

```sh
dnf copr enable @CoreOS/matchbox
dnf install matchbox

**Comment by Opswatch** [comment]
It was what alek said the page did not render properly and was missing the setup user instructions I got it working now :)..thanks

**Comment by rothgar** [comment]
I just ran into this because I installed via RPM (thank you @dghubble) but the rpm didn't create the folder for me. Please update your post install script

**Comment by dghubble** [comment]
@rothgar which folder?

**Comment by rothgar** [comment]
all folders. I manually had to create /var/lib/matchbox/{assets,profiles}
oddly enough after creating those the others (groups, ignition) got created for me

**Comment by dghubble** [comment]
Ok, I'll add the spec files to the repo and look over them before the upcoming v0.6.0.

**Comment by dghubble** [comment]
https://github.com/coreos/matchbox/issues/481

**Comment by volgasimsek** [comment]
hi there,
I think the instructions for CoreOS and generic linux at https://coreos.com/matchbox/docs/latest/deployment.html#generic-linux is mixed up. 

sudo cp contrib/systemd/matchbox-on-coreos.service /etc/systemd/system/matchbox.service should be used for generic linux, not CoreOS. And same prompt for generic linux copies the file intended for CoreOS
