### ISSUE TITLE
Can't use existing VPC

### ISSUE THREAD

**Issue by patagona-afriemann** [coreos/tectonic-forum#56]
### Tectonic version

1.5.2 

### Environment

AWS

### Expected Behavior

Configuration should tell me what the issue is.

### Actual Behavior

"Next step" stays gray.

### Reproduction Steps

We have an existing VPC with the CIDR 10.0.0.0/16.
When running the installer, everything seems fine until we get to the "Advanced Networking" part.
We select the VPC in question but are not able to continue; the "Next step" button remains gray.

![2017-02-21-112353_791x498_scrot](https://cloud.githubusercontent.com/assets/13764034/23160837/4263d0e4-f828-11e6-9ffd-2b1a42156760.png)

Set log level to 10, no errors are being logged.

**Comment by samueltbrown** [comment]
I encountered the same issue and because of the 51200 character limit on cloud formation I was also not able to have the installer create a VPC for me.  I was not able to install Tectonic at all :(

**Comment by omkensey** [comment]
^ Same here.  FWIW, assuming you can, using 1.5.2-1 worked fine.

**Comment by samueltbrown** [comment]
@omkensey Assuming that would be the download "tectonic-1.5.2-tectonic.1.tar.gz" instead of "tectonic-1.5.2-tectonic.2.tar.gz"?? Thanks!

**Comment by omkensey** [comment]
You got it!

**Comment by mfburnett** [comment]
Hey @patagona-afriemann - thanks for filing this issue. I've let @ErnestG4 know; he'll get back to you in a few days and will pull in others from our team as necessary. 

cc @samueltbrown @omkensey

**Comment by Quentin-M** [comment]
As a side note, letting you know that the CloudFormation issue will be resolved in the next release.

**Comment by kans** [comment]
It looks like you don't have any subnets in the VPC you selected (the Controllers/Workers sections are empty).  You will need to create at least two subnets (outside of the installer) to proceed.  If you selected 'Internal Cluster' on the Cluster Info page, they must be private.

**Comment by Quentin-M** [comment]
**'Public' Cluster**:
- The subnets you want to use for Controllers must have an attached and routed Internet Gateway. 
- The subnets you want to use for Workers must have an attached and routed NAT Gateway, living in one of the Controller subnets.
- The route tables should explicitly attached to their subnets.

**Internal Cluster**:
- The subnets you want to use for Controllers and Workers must have an attached and routed NAT Gateway, living in any Public subnet,
- The route tables should explicitly attached to their subnets.
- You should have a VPN access to the VPC.

**Comment by omkensey** [comment]
^ This is changed behavior in -2 then?  IIRC 1.5.2-1 didn't require anything for an existing VPC but an attached Internet gateway and a 10.0.0.0/16 CIDR.

**Comment by Quentin-M** [comment]
@omkensey Using an existing VPC now implies using existing Subnets on the UI Installer.

**Comment by joshix** [comment]
@omkensey That was my understanding, too (thus what the doc says), but I didn't test existing VPC myself until 1.5.2-tectonic-2. Did you previously install into existing VPC without creating 2 subnets?

**Comment by patagona-afriemann** [comment]
I was using tectonic-1.5.2-tectonic.2.tar.gz today.

@kans we are using that VPC in production with several subnets, so that is not the case.
@Quentin-M there is an IGW in our VPC and routing is setup (and works perfectly fine in all subnets)

**Comment by omkensey** [comment]
@joshix yes, previously it worked exactly as https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#using-an-existing-vpc stated.

**Comment by TimMeade** [comment]
This is not what the documentation says also.  It says the VPC must have 10.0.0.0/16.  Nothing about subnets.  We had setup subnets and then deleted them.   But we didn't add the other criteria.  We are trying to setup a trial and this is a little frustrating.   We will try again with information found here.

**Comment by TimMeade** [comment]
We have created the routes and followed the requirements above.    The Next Step button is still grayed out.   So we are dead in the water.   Cannot install with create new and cannot add to existing.

**Comment by mfburnett** [comment]
Hi @patagona-afriemann, @TimMeade - wanted to let you know that we released T[ectonic 1.5.3-tectonic.1](https://coreos.com/tectonic/releases), which includes full configuration of existing VPC CIDR ranges and should also address the subnet issue you were encountering. 

@samueltbrown - we also fixed the CF character limit issue in this release.

**Comment by samueltbrown** [comment]
@mfburnett Appreciate the follow-up!  I'll check it out.

**Comment by joshix** [comment]
Noting incremental expansion of https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#using-an-existing-vpc

**Comment by patagona-afriemann** [comment]
@mfburnett thanks for the update. Set up a cluster with that version and it seems to be working fine. There still seem to be some minor problems, but I guess I'll open another Issue for that.

**Comment by mfburnett** [comment]
@patagona-afriemann okay thanks! Going to close this issue now. Feel free to file further issues on the other things you mentioned.
