### ISSUE TITLE
Set or override cloud-provider settings during or after install

### ISSUE THREAD

**Issue by MattMencel** [coreos/tectonic-forum#58]
### Tectonic Version 

1.5.2-tectonic.1

### Environment

VMware ESXi 6.0

## Feature Request

I've deployed a small k8s cluster to my VMware environment.  I'd like to take advantage of dynamic persistent storage.  In order to do that I have to add a default vSphere datastore setting to the apiserver, kubelets, and controller.  Is there are way to do this during or after the install process?

Specifically I'd like to be able to add the --cloud-provider=vsphere and --cloud-config={CONFIGFILE} parameters.

**Comment by mfburnett** [comment]
Hey @MattMencel - thanks for filing this issue. I've let @ErnestG4 know; he'll get back to you in a few days and will pull in others from our team as necessary.

**Comment by alekssaul** [comment]
Hi @MattMencel,

**Please note that below is for education purposes, hasn't been tested or officially supported. However if you choose to test it, we would love to hear your feedback.**

Tectonic deploys kubernetes API server in self-hosted [0] manner. Once tectonic is up, the API server options are located in "kube-apiserver" Daemonset under kube-system. You should be able to modify the --cloud-provider flag and killing the API server pod. 

 Please also note that changes to kube-apiserver daemonset spec may be overwritten during Tectonic in-place upgrades and may require re-applying changes post upgrade.

[0] - https://github.com/kubernetes/community/blob/master/contributors/design-proposals/self-hosted-kubernetes.md

**Comment by MattMencel** [comment]
Hi @alekssau,

Thanks.  I found the Daemonset, just need to test that.  

I was mucking around with the bootkube assets that get uploaded to the controller node and figured out how to edit those to get the right data deployed to all the containers, but the vSphere integration piece wouldn't work.  Editing the Daemonset will probably be easier.

The problem I haven't figured out yet with the Daemonset is how to get this vSphere settings config file onto the container. https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/vsphere/vsphere.conf

Matt

**Comment by alekssaul** [comment]
Sounds like you can create a secret object in kube-system namespace and use volumemounts; https://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-files-from-a-pod

**Comment by MattMencel** [comment]
Hi @alekssaul ,

I was able to deploy the secret and add the config and volumemount to the Daemonset.  I killed the apiserver and it restarted with the new config, so that looks good.

According to the vSphere volume docs here: https://kubernetes.io/docs/getting-started-guides/vsphere/

It looks like I need to also restart kubelet and controller-manager.

> Provide the cloud config file to each instance of kubelet, apiserver and controller manager via --cloud-config=<path to file> flag. Cloud config template can be found at Kubernetes-Anywhere

Do I need to do the same additions to the kube-controller-manager ReplicaSet?  Or is this not required or is there something else I need to update?

Matt

**Comment by alekssaul** [comment]
Hi @MattMencel ,

Based on my understanding of vSphere requirements, you should apply similar changes to kube-controller-manager deployment or replicaset and kill the kube-controller pods. 

The kubelet itself however is run via systemd unit on each host. You can find the systemd unit file under `/etc/systemd/system/kubelet.service`. One thing to note is that, kubelet is run by rkt. You may want to create the vsphere conf file in `/etc/kubernetes/vsphere.conf` since /etc/kubernetes folder is mounted into the kubelet container.

Once you've edited kubelet service you can `sudo systemctl daemon-reload` and `sudo systemctl restart kubelet`.

**Comment by MattMencel** [comment]
I think I've got the configs in the right places.  I opened an issue with the Kubernetes team because it might be a problem with the vSphere config itself.

https://github.com/kubernetes/kubernetes/issues/42026

**Comment by alekssaul** [comment]
Hi @MattMencel ,

We cut Tectonic 1.5.3-1 today. Docs and release notes should be synced soon and upgrade should be available in Tectonic console under Administration\Cluster Settings soon.

If you still have the bandwidth to work on it, can you please try to upgrade ? Would be great to confirm if your changes survive the upgrade and if 1.5.3 vSphere cloudprovider configuration works.

**Comment by mfburnett** [comment]
@MattMencel @alekssaul going to close this issue due to lack of activity - please feel free to re-open with any new info/comments/questions!
