### ISSUE TITLE
High availability questions

### ISSUE THREAD

**Issue by xueshanf** [coreos/tectonic-forum#6]
### Tectonic Version 
1.4.5-tectonic.1
### Environment

Mac OS X EL Capitan

What hardware/cloud provider/hypervisor is being used with Tectonic?

AWS

### Expected Behavior

I am able to create the kube cluster using the installer. 

### Other Information

I'd like to know the on-going platform management process:

1. How do I add new  worker nodes  in other availability zones? If I use AWS CF, will the tectonic service knows about the new nodes? 
2. Currently there is only 1 controller/etcd. If the contoller/etcd node is crashed, will it recover with configurations, or do we need to restore from etcd backups?  What about the deployed applications on worker nodes? Do they need to be re-deployed?
3. If one controller cannot provide HA, how to create/add more controllers, like 3?

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by mfburnett** [comment]
Hey @xueshanf, thanks for your questions around HA! Enabling HA for Tectonic is a big focus point for us right now.

> 1. How do I add new worker nodes in other availability zones? If I use AWS CF, will the tectonic service knows about the new nodes?

Right now you can't, but enabling multi-AZ worker nodes is top of our priority list in the coming weeks.

> Currently there is only 1 controller/etcd. If the contoller/etcd node is crashed, will it recover with configurations, or do we need to restore from etcd backups? What about the deployed applications on worker nodes? Do they need to be re-deployed?

Yes, we would recommend restore from etcd backups. We're working on shipping multi-node etcd some time in Q1. 

> If one controller cannot provide HA, how to create/add more controllers, like 3?

You're right, one controller cannot provide HA. Multi-controller in AWS is on our roadmap for Q1!

**Comment by xueshanf** [comment]
@mfburnett Thanks! Glad it's on the road map. I rebooted controller/etc and it has no problem to get going with the configurations from the etcd data on disk. I will test crash-recovery.

**Comment by chulkilee** [comment]
Instead of a cluster to manage workers on multiple AZ, do you have plan to use kubernetes federation on the top of single-az clusters? I think using federation gives much more flexibility (e.g. not only cross az but cross region, etc)

**Comment by ericchiang** [comment]
> Instead of a cluster to manage workers on multiple AZ, do you have plan to use kubernetes federation on the top of single-az clusters? I think using federation gives much more flexibility (e.g. not only cross az but cross region, etc)

Federation and multiple AZs are very different features and not mutually exclusive. Multi AZ is something that works today so we're focusing on getting that in the next release. We've been investigating federation, but part of that is determining the maturity of the feature, if it's ready for production environments, what the auth story is, etc.

**Comment by chulkilee** [comment]
I know - just throwing that since that is another way to achieve HA in different ways..

If coreos will use this project to share the roadmap, we should create more specific issue for individual features (e.g. multi-AZ customer, federation, multi-node controller or etcd) once they are identified..

**Comment by InAnimaTe** [comment]
In the realm of HA, I have pretty much some of the same questions, but in relation to **Bare-Metal** clusters...

1. Can I add more than one controller node?
2. Can I add more than one worker node?
3. What backup/HA options are available presently?

I don't really see any docs on this stuff either. Are there any docs you can point to on how to achieve this? Is there console support there (or coming) for these?

**Comment by Quentin-M** [comment]
@InAnimaTe @xueshanf 

1/3) We expect to ship the ability to setup multi-controllers clusters in the coming weeks - it is currently our highest priority. It is currently not supported on either bare-metal or AWS. 

However, the upcoming version of Tectonic will let users specify an external etcd cluster, rather than having the installer provision one for you, which will allow using an existing HA etcd cluster. From this point, multiple nodes could be tagged as master nodes and the desired deployments may be scaled up, but there will no guarantee until we officially release, and thoroughly test, this feature.

etcd being the main datastore for Kubernetes and Tectonic, it is the most critical component you want to monitor, snapshot/backup. Guides for doing so are available [here](https://coreos.com/etcd/docs/latest/).

2) Absolutely. The installer lets you choose the servers you'd like to define as workers.

**Comment by InAnimaTe** [comment]
@Quentin-M 

Thanks a lot for the response! Regarding 2, I meant after-the-fact i.e. you have a cluster running already, how would you add more worker nodes. Not seeing anything in the docs around this for tectonic, only seeing [this](https://coreos.com/kubernetes/docs/latest/deploy-workers.html) general guide for k8s. (probably my fault for not looking hard enough).

Regarding guides for backing up etcd, [this](https://coreos.com/etcd/docs/latest/v2/admin_guide.html#disaster-recovery) is more a direct link to backup/restore ;)

**Comment by Quentin-M** [comment]
@InAnimaTe Sorry for the delay. On bare-metal clusters, you'd have to add new groups to your bootcfg (recently renamed matchbox) configuration, matching the MAC addresses of the nodes you'd like add to the cluster. You can literally copy-paste the existing `tectonic-install-<MAC>.json` and `tectonic-node-<MAC>.json` files, rename them and edit them to add the appropriate MAC addresses. You want to make sure your DHCP is properly configured for these machines too. Then, boot these nodes w/ PXE. Matchbox/bootcfg should catch them, make them install CoreOS and then reboot them into CoreOS and let them join the Kubernetes cluster.

**Comment by InAnimaTe** [comment]
@Quentin-M Awesome. I presume the team is working to make this process a bit easier in the future. Would be nice if I could merely use the Tectonic UI to add hosts which would automatically take care of logging into my matchbox instance, creating the json ignition config, and then tell me to pxe boot the box.

It'd also be nice to see some documentation on this process. Its undoubtedly many people are going to want to do at some point with their cluster.

**Comment by Quentin-M** [comment]
@InAnimaTe Happy to help. This is definitely something we'd like to achieve in the future!

**Comment by mfburnett** [comment]
@xueshanf to answer your original questions:

1. How do I add new worker nodes in other availability zones? If I use AWS CF, will the tectonic service knows about the new nodes?
[
See docs](https://coreos.com/tectonic/docs/latest/admin/aws-scale.html) on how to scale worker nodes on AWS. Tectonic will know about new nodes. 

2. Currently there is only 1 controller/etcd. If the contoller/etcd node is crashed, will it recover with configurations, or do we need to restore from etcd backups? What about the deployed applications on worker nodes? Do they need to be re-deployed?

We [shipped this release](https://coreos.com/tectonic/docs/latest/admin/aws-scale.html#external-etcd-cluster) with HA etcd (alternatively, you can connect an existing etcd cluster). [Here are the docs](https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html#etcd-disaster-recovery-on-coreos) on disaster recovery for etcd.

If one controller cannot provide HA, how to create/add more controllers, like 3?

See docs](https://coreos.com/tectonic/docs/latest/admin/aws-scale.html) on how to scale controller nodes on AWS.

@InAnimaTe see the responses above! Default HA controller nodes for AWS and bare metal (as well as HA etcd for bare metal) is set to come very soon. I'll comment back here when that is released.

**Comment by mfburnett** [comment]
Hi @xueshanf @InAnimaTe, following up here. Our latest release, v1.5.4-tectonic.1, includes HA by default for both AWS and bare metal: https://coreos.com/tectonic/releases/. Closing this issue for now.

**Comment by rushins** [comment]
hello mfburnett,

I am doing test with 3 Masters (controllers) and 3 workers deployment with tectonic 1.63 and installation failing with API server ? we are using 10 Node free license . Is there any limitation that only one MASTER (Controller) supported ? I tried with 1 master and 5 workers, it worked like charm but 3 masters and 3 worker always failing. 
 
Can you just through some information why this is failing. 
 
I get this error. 
 
have you seen this error?? sudo tail -300 bootstrap-kube-apiserver-ld4601.wdf.sap.corp_kube-system_kube-apiserver-8c7933423beaba4d7035b90aee734b7f5369e05aabbb563a6df4b860ca1e517d.log 
{"log":"Error: error waiting for etcd connection: timed out waiting for the condition\n","stream":"stderr","time":"2017-08-24T19:24:43.141656508Z"} 
{"log":"Error: error waiting for etcd connection: timed out waiting for the condition\n","stream":"stderr","time":"2017-08-24T19:24:43.14171726Z"}

**Comment by armenr** [comment]
I've been prospecting Kubernetes (and Tectonic in particular) for laying down the ground-zero infrastructure for a startup I'm at. 

First, I'd like to say: YOU PEOPLE ARE DOING INCREDIBLE WORK! Thank you! (CAPS intended).

I have some questions around scaling - but nothing too involved or particular.

Concern 1: If we were to discover that the instance type/size for designated master nodes or etcd nodes needed to be revised, how do we go about doing that?

Example: I want to change instance type from t2.medium to m4.xlarge. If I rolled out the terraform apply for this, what would that look like? Would it simply nuke the existing masters and replace them with new masters? If so, how do we architect for zero-downtime/high availability in this case? 

If my question sounds uninformed/ignorant, that's because you're right. I've not worked with Kubernetes or Tectonic before, so I am unfamiliar with HA deploy/upgrade patterns around this ecosystem.

Thank you for your kindness and patience!
