### ISSUE TITLE
Installation instructions reference /usr/local/bin, systemd unit file expects/usr/bin

### ISSUE THREAD

**Issue by MarkusTeufelberger** [coreos/tectonic-forum#60]
### Tectonic Version 
1.5.2

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
Ubuntu 16.04 in an LXD container, following the bare metal install

### Expected Behavior
After following the guide at https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html#2-provisioning-infrastructure after the "systemctl start matchbox" step, matchbox is running

### Actual Behavior
matchbox is located at /usr/local/bin/matchbox according to the guide while systemd tries to run /usr/bin/matchbox (https://github.com/coreos/matchbox/blob/master/contrib/systemd/matchbox.service#L9) - so it isn't run.

### Reproduction Steps

Follow the official bare metal installation guide at https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html until the "Verify" section.

### Other Information
Works if the systemd file is modified to include the proper path or alternatively copying matchbox to the correct location.

**Comment by mfburnett** [comment]
Hey @MarkusTeufelberger - thanks for filing this issue. I've let @ErnestG4 know; he'll get back to you in a few days and will pull in others from our team as necessary. cc @dghubble

**Comment by dghubble** [comment]
That's a typo. `contrib/matchbox.service` is bundled in the RPM (no clear reason to give this to users in the tarball). If you're placing the binary yourself (generic Linux distros), use `contrib/matchbox-local.service`.

**Comment by mfburnett** [comment]
Looping in @joshix for this docs typo fix. cc @MarkusTeufelberger @dghubble

**Comment by eric-lopez** [comment]
Confirmed fixed on Ubuntu 16.04

copied `contrib/matchbox-local.service` to `/etc/systemd/system/matchbox.service` 

matchbox service is able to start at boot now after it has been enabled.

**Comment by joshix** [comment]
I believe this can close after https://github.com/coreos-inc/tectonic/pull/1451

**Comment by joshix** [comment]
fix published in https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html#install (1.5.3-t.1). Closed.
