### ISSUE TITLE
Unable to install with alternative CIDR 

### ISSUE THREAD

**Issue by timechanter** [coreos/tectonic-forum#61]
### Tectonic Version 
1.5.2

### Environment

Bare Metal

XenServer VMs

### Expected Behavior
Its possible to deploy tectonic using alternative CIDR for Pods/Services, such that it can be installed into a network that already uses 10.2.0.0/16 and 10.3.0.0/16 , and specifically already has uninvolved servers 10.3.0.1 and 10.2.0.1 .

### Actual Behavior
If you install tectonic into a network with already routable via 10.2.0.0/16 and/or 10.3.0.0/24 then the installation stalls as soon as Flannel overlay starts up.

Tectonic assumes (hardcodes) the overlay network will be using 10.2.0.0/16 and 10.3.0.0/24, along with several well known IPs within that range for DNS, API Services, Nginx Proxy. There is no mechanism to specify the CIDRs for Pods/Services during installation, and no way to add AltNames to the generated certificates to permit the cluster to correctly deploy/start.

### Other Information

My target network to install tectonic on is already using the 10.0.0.0/16, 10.2.0.0/16, and 10.3.0.0/16 ranges.
So I need to install tectonic away from the default (hard coded) network ranges.
I have pulled the PRs from bootkube 0.3.9 for respecting the CIDRs in the templates , and patched 0.3.5 to match the current tectonic installer. I have modified the assets and matchbox to use my new ranges (10.20 10.30) , and reissued the alt names of the apiserver.crt

After a lot of installs I can get the controller running and sometimes register the worker. It appears the controller is using my apiserver.crt for bootstrap but then switches to a 10.3.0.1 one. If I shell into the controller apiserver I see it's no longer using my cert (from assets) .

even when the worker registers with the controller flannel container times out trying to access the Apiserver via 10.30.0.1 which is understandable as until flannel has setup the overlay network that address doesn't route.

**Comment by timechanter** [comment]
My target network to install tectonic on is already using the 10.0.0.0/16, 10.2.0.0/16, and 10.3.0.0/16 ranges. 
So I need to install tectonic away from the default (hard coded) network ranges. 
I have pulled the PRs from bootkube 0.3.9 for respecting the CIDRs in the templates , and patched 0.3.5 to match the current tectonic installer. I have modified the assets and matchbox to use my new ranges (10.20 10.30) , and reissued the alt names of the apiserver.crt

After a lot of installs I can get the controller running and sometimes register the worker. It appears the controller is using my apiserver.crt for bootstrap but then switches to a 10.3.0.1 one. If I shell into the controller apiserver I see it's no longer using my cert (from assets) .

even when the worker registers with the controller flannel container times out trying to access the Apiserver via 10.30.0.1 which is understandable as until flannel has setup the overlay network that address doesn't route. 

Sorry Im on mobile and can't edit the details ATM.

**Comment by timechanter** [comment]
I am deploying tectonic via 2 xenserver VMs

**Comment by dghubble** [comment]
This is not supported in Tectonic 1.5.2.

We added changes to bootkube to support pod and service range customization. These changes will be reflected in the next Tectonic AWS release and shortly after for Tectonic bare-metal. Internal details like picking the apiservice IP and DNS service IP will be handled as well.
* https://github.com/kubernetes-incubator/bootkube/pull/318
* https://github.com/kubernetes-incubator/bootkube/pull/307

**Comment by timechanter** [comment]
The missing piece of information I needed was that the Certs (apiserver.crt) and friends are actually stored in etcdc /registry/secrets/kube-system/kube-apiserver   and these are used to boot strap the cluster on restart. I don't know where/how that first go updated with the "wrong/default" AltName , however by stopping kubelet and all the docker containers I could then update the secretes with the correct apiserver.crt (for my changed CIDR) and then restart kubelet. The installer continued ("waiting for kubenetes") and the workers all joined happily.

**Comment by mfburnett** [comment]
hey @timechanter thanks for the update - letting our docs team know to clarify this piece of information in our documentation/troubleshooting guide! cc @joshix

**Comment by dghubble** [comment]
If you've changed the CIDR range after assets.zip generation in 1.5.2, there are several manifests you'd likely need to change. Flags to the controller manager, scheduler, and kube-dns service as well. This will be handled in 1.5.3 automatically.

**Comment by timechanter** [comment]
Hi @dghubble , yes I had to change quite a few manifests, and the assets/tls/apiserver.crt (AltNames for the new apiserver address). And once the Controller has initialised/pivoted I had to update the etcd /registry/secrets/kube-system/kube-apiserver apiserver.crt entry (I also updated the checkpoint version for good measure).

**Comment by timechanter** [comment]
Its working well, and nothing special is needed for adding new workers. Its only the initial bootstrap thats trouble some. Took a few days to resolve, lots of reimages via matchbox ;)

**Comment by dghubble** [comment]
The Tectonic 1.5.3 release is available. The pod and service CIDR ranges can be chosen on both bare-metal **and** AWS. Previously, I said bare-metal was delayed, but its included.

Anyone installing in an environment that uses `10.2.0.0/16` or `10.3.0.0/24` already should use that new functionality. You don't want conflicts/strangeness to appear randomly in the future when deploying new services or pods.

**Comment by mfburnett** [comment]
Going to close this issue for now, given that we've worked to better document requirements around CIDR ranges and shipped a few releases that expand the customization options for networking. Please feel free to comment and re-open if you have any further issues, @timechanter.
