### ISSUE TITLE
etcd completely open ;(

### ISSUE THREAD

**Issue by InAnimaTe** [coreos/tectonic-forum#66]
### Tectonic Version 
1.5.2-tectonic.1

### Environment
bare-metal

### Expected Behavior
Not completely open etcd (certificates+auth) and possibly different port.

### Actual Behavior
Completely wide open on default port.

### Reproduction Steps

Running the useful etcdbrowser application on my laptop pointed to my controller node:

```
docker run --rm --name etcd-browser -p 8001:8000 --env ETCD_HOST=controller.k8s.example.com --env ETCD_PORT=2379 -t -i buddho/etcd-browser
```

yields rw access to everything:

![](https://transfer.sh/xTWVj/screenshot-from-2017-02-28-16-24-45.png)

## Feature Request

As a lot of people deploy clusters on a variety of public resources (i.e. cloud providers), and as etcd is essential to the overall operation of the cluster, not to mention the lackluster secrets storage method, it's a really good idea to secure this by default. I mean lets not turn into mongodb ;)

**Comment by dghubble** [comment]
On bare-metal, network isolation is needed to protect etcd. On AWS, private subnets and security groups are used for this. We may add TLS configuration to on-host etcd. However, self-hosted etcd (i.e. as pods, see [bootkube](https://github.com/kubernetes-incubator/bootkube/blob/master/cmd/bootkube/start.go#L29)) is upcoming and will change the story significantly.

**Comment by robszumski** [comment]
Hi @InAnimaTe, Tectonic 1.6.7 is out with full TLS support for etcd, no matter how it's deployed. Check it out: https://coreos.com/blog/kubernetes-the-coreos-way
