### ISSUE TITLE
bare-metal ipxe boot fails with "No such file or directory"

### ISSUE THREAD

**Issue by kwtalley** [coreos/tectonic-forum#67]
### Tectonic Version 
1.5.2

### Environment
bare-metal

### Expected Behavior
pxe hand off to ipxe -> os boot

### Actual Behavior
boot.ipxe is successfully loaded, but fails when invoking the chain

### Reproduction Steps

  1. install coreos
  2. install matchbox and configure
  3. configure dnsmasq container to proxy dhcp and provide pxe/ipxe:
`sudo rkt run coreos.com/dnsmasq:v0.3.0 --net=host -- -d -q --dhcp-range=192.168.1.1,proxy,255.255.255.0 --enable-tftp --tftp-root=/var/lib/tftpboot --dhcp-userclass=set:ipxe,iPXE --pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe --pxe-service=tag:ipxe,x86PC,"iPXE",http://provisioner.example.com:8080/boot.ipxe --log-queries --log-dhcp`
   4. attempt to pxe boot another host

### Other info
when a new host boots, it successfully picks up the pxe boot option, proceeds to the next server correctly and loads boot.ipxe script. immediately after, it fails with:

`http://provisioner.example.com:8080/boot.ipxe.0... ok`
`boot.ipxe.0 : 104 bytes [script]`
`ipxe?uuid=<uuid>&mac=<mac>&domain=example.com&hostname=&serial=<serial>... No such file or directory (http://ipxe.org/2d0c613b)`
`Could not boot image: No such file or directory (http://ipxe.org/2d0c613b)`
`No more network devices`

`Operating System not found`

If I curl `http://provisioner.example.com:8080/ipxe`passing any url query parameters, it will always return a 404.

**Comment by dghubble** [comment]
matchbox doesn't serve provisioning configs to machines it doesn't know about yet. The Tectonic Installer GUI creates and injects this information via the matchbox API, you you'll want to go through that flow to pick various properties of your Tectonic cluster (cert generation, Ingress, CIDRs, etc.).

If you're using just open-source `matchbox` and not Tectonic, you can borrow some of the [example](https://github.com/coreos/matchbox/tree/master/examples) configs and added them directly to `/var/lib/matchbox` [subdirectories](https://coreos.com/matchbox/docs/latest/matchbox.html#data) manually.

**Comment by kwtalley** [comment]
oh man that makes a lot of sense. thank you @dghubble i was going on the assumption that it would discover nodes first and then go through the commissioning process. i'll keep going forward!

**Comment by dghubble** [comment]
I'd like to make discovery and surfacing those discovered machines in the Tectonic Installer a feature someday :)

**Comment by rushins** [comment]
hello 

i had happen to have the same issue, i have all my MAC addresses of systems in my DNSMASQ.conf and i use the same information for Master and workers MAC address during the tectonic installer . All correct as i verify twice but after boot the host  it gets error "could not boot image : No such file directory (http://ipexe.org/2d0c613b)
no more network devices

Any clue what log file to check 

BR
