### ISSUE TITLE
Don't assume static AWS credentials in the Tectonic installer

### ISSUE THREAD

**Issue by copumpkin** [coreos/tectonic-forum#7]
### Tectonic Version 

1.4.5-tectonic.1

### Environment

AWS

### Expected Behavior

I have the option to use AWS "instance credentials" rather than an access key + secret key.

### Actual Behavior

I cannot proceed unless I give it an access key + secret key.

### Reproduction Steps

1. Run tectonic installer
2. Click through until it asks you if you want "bare metal" or "AWS"
3. Pick AWS
4. Get stuck on the access key + secret key prompt

### Other Information

Ever since the beginning of AWS, EC2 instances have had a magic hypervisor-provided "instance metadata service" listening on 169.254.169.254 that provides rotating temporary IAM credentials in a standard location. The thing about temporary IAM credentials is that they have _three_ components, not _two_, so in addition to the access key and secret key, you also get a blob of crypto called the session token.

All AWS SDKs that I know of (for python, c++, java, go, etc.) have supported this mechanism forever. So if you specify an access key + secret key explicitly, it'll use that, but if you don't specify anything, it'll fall back to 169.254.169.254 and pull the credentials from there. As such, I expect that if the tectonic installer is using the Go AWS SDK, it should be simple to address this ticket (by simply not specifying the credentials explicitly)

See also https://github.com/AdRoll/hologram, which simulates the instance metadata service on a non-EC2 box.

**Comment by mfburnett** [comment]
Hey @copumpkin, thanks for filing this issue! Looking into this and will get back to you within a day or two.

**Comment by mfburnett** [comment]
Hey @copumpkin, sorry for the delay here! We're hitting the API directly from the installer on your laptop - not booting an EC2 instance, then doing the install from that. So unfortunately you wouldn't be able to take advantage of this functionality.

**Comment by copumpkin** [comment]
I know! I use the same mechanism on my laptop via an open source tool
called Hologram, and have mostly banished static credentials from my life
:) I realize it's not the common case but given that the SDK supports this
feature natively out of the box it doesn't seem too hard to support it in
the installer.

**Comment by copumpkin** [comment]
To be clear, tools forcing static credentials are rare enough that my
organization has mostly forbidden IAM users (i.e., static keys) from our
AWS accounts. At the very least, putting in an optional third field for the
session token would also achieve this goal, but it would still probably be
easier to let the SDK just do its thing.

**Comment by sym3tri** [comment]
We've actually just added support for STS session tokens which will be shipping in our next release, due out later this week :)

**Comment by copumpkin** [comment]
Awesome, thanks!

**Comment by mfburnett** [comment]
Closing this issue, as we addressed this with support for STS session tokens.
