### ISSUE TITLE
Upgrading your cluster

### ISSUE THREAD

**Issue by pompomJuice** [coreos/tectonic-forum#70]
### Tectonic Version 

1.5.3 -> 1.6.0 beta

### Environment

vmware bare metal

### Expected Behavior

It should work

### Actual Behavior

It does not work.

### Reproduction Steps

Follow [these](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube-upgrades.md) instructions.

### Other Information

The logs spam the shit out of you. There is no indication about what went wrong. The tectonic console just disappears. You are left with journalctl -f -u kubelet on your controller which produces 2000 lines of error logs per second while consuming 300% CPU power.

This system seems overly brittle to me? I question any claims that it is being used in production. There is no documentation on how to troubleshoot your cluster. All documentation goes on as if everything works but it does not. No mention of how to check that what was supposed to work actually worked. 

I am trying to get my feet wet with this thing. But there is no logical way to debug why your cluster does not work or how you can systematically roll back things that you tried to do off of incomplete documentation to undo damage. How are we to convert 2000 logs per second in actionable information?

I mean, I have literally an empty cluster, 1.5.3, I followed the instructions step by step. And it fails. While doing the instructions I can clearly see how the instructions are wrong and the examples in the instructions are wrong. 

For example, this part:  

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3+coreos.0", GitCommit:"7819c84f25e8c661321ee80d6b9fa5f4ff06676f", GitTreeState:"clean", BuildDate:"2016-10-17T21:19:17Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

Why would the Client version suddenly be bumped? The client is kubectl that is not upgraded by any previous instructions mentioned. The documentation is just plain wrong. Like all the other documentation. 

This is causing serious time wastage while we have to now debug your product and your documentation. It's just unacceptable. 

And what is the point of having this awesome coreos always upgrade when upgrading your cluster is a process that is about as manual as wiping your own...

I mean I would supply some logs, but what logs? There is just millions of logs all spamming the same errors as fast as possible.

**Comment by dghubble** [comment]
For Tectonic clusters, please follow Tectonic [docs](https://coreos.com/tectonic/docs/latest/admin/upgrade.html). If you've enabled upgrades (an experimental feature) you may press the "check for updates" button to check for updates we've pushed to upgrade your cluster. The latest Tectonic version is 1.5.3 so you will not find an upgrade to 1.6.0-beta.

We don't have plans to push non-final Kubernetes releases to clusters and the experimental upgrades feature is currently scoped to the minor version channel (i.e. fixes / vulnerabilties in 1.5) as well.

**Comment by pompomJuice** [comment]
How the hell should I have know that?

**Comment by mfburnett** [comment]
Hi @pompomJuice, we follow a [Code of Conduct at CoreOS](https://coreos.com/code-of-conduct/) that applies "both within project spaces and in public spaces when an individual is representing the project or its community." We take this Code of Conduct seriously and expect others to as well.

Please adopt a more cordial tone in order to make this friendly, respectful, and productive for everyone. 

Per the Code of Conduct guidelines, cc'ing @philips.

**Comment by pompomJuice** [comment]
Ok.

I apologize.

I am stressed out.

I will stop it.

Werner.
