### ISSUE TITLE
Tectonic installer (bootkube) only works in 1st world countries.

### ISSUE THREAD

**Issue by pompomJuice** [coreos/tectonic-forum#71]
### Tectonic Version 

1.5.3

### Environment

vmware bare metal

### Expected Behavior

Tectonic should install

### Actual Behavior

Tectonic fails

### Reproduction Steps

Run the installation process

### Other Information

Bootkube does not wait for the nodes to download  hyperkube long enough. It assumes that everyone has the same internet quality and speed. 

`133-0264-11e7-a36a-005056a9e04e", APIVersion:"v1", ResourceVersion:"94", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods
Mar 06 12:20:57 controllers.ctlab.com bootkube-start[2539]: [ 6866.399296] bootkube[5]: Error: error while checking pod status: timed out waiting for the condition
Mar 06 12:20:57 controllers.ctlab.com bootkube-start[2539]: [ 6866.401242] bootkube[5]: Error: error while checking pod status: timed out waiting for the condition
Mar 06 12:20:57 controllers.ctlab.com bootkube-start[2539]: [ 6866.401924] bootkube[5]: error while checking pod status: timed out waiting for the condition
Mar 06 12:20:57 controllers.ctlab.com systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 12:20:57 controllers.ctlab.com systemd[1]: bootkube.service: Unit entered failed state.
Mar 06 12:20:57 controllers.ctlab.com systemd[1]: bootkube.service: Failed with result 'exit-code'.
`

**Comment by mfburnett** [comment]
Hi @pompomJuice, thanks for filing this issue. Bootkube currently has a timeout of 20 min; in the future, we hope to make this more flexible. 

As we've mentioned to you before, VMware is currently an untested and unsupported platform for Tectonic and we cannot guarantee your experience attempting to install via our bare metal installer. This issue may be related to that.
