### ISSUE TITLE
Installation questions - Tectonic DNS

### ISSUE THREAD

**Issue by pjatacsukb** [coreos/tectonic-forum#72]
### Tectonic Version 
1.4.7-tectonic.1
### Environment
VMWare
What hardware/cloud provider/hypervisor is being used with Tectonic?
VMWare
### Expected Behavior
Not clear instructions on installation
### Actual Behavior
Additional information about one of the steps.
### Reproduction Steps

We installed Tectonic, but we had some confusion about one of the steps. 
![2017-03-02](https://cloud.githubusercontent.com/assets/22151883/23651911/52f810fa-0327-11e7-8fa6-56b574a7bd7e.png)

What exactly the Tectonic DNS means?
Should it point to a loadbalancer that points to a random worker node each time?

We just pointed it to one of our worker node's (lets callit worker1).
Now we are testing what happens if the worker1 goes "down".
We cannot access the cluster if this worker1 goes down.
What is the expected behaviour if one of the worker nodes goes down?

**Comment by dghubble** [comment]
Tectonic bare-metal runs Ingress as a daemonset across workers. The "Tectonic Domain" is a name which resolves to any worker node(s) and will be the name by which you access the console. Your Tectonic DNS choice, depends on the infrastructure you have available.

Possible options might be a single DNS entry (as you've done), round robin DNS, or the name of a load balancer fronting the workers. For higher availability, use a load balancer over many workers.

If none of these suit your liking, you can tweak things on your own after initial setup. Such as pinning ingress to specific nodes or using ip routing.

**Comment by pjatacsukb** [comment]
Thank you for your answer, that clear things up.
Can I change the Tectonic DNS after installation or I have to redo the process?

**Comment by dghubble** [comment]
The DNS name is used in the configuration of console and identity (which could be tweaked, carefully) and generated certificates are specific for the name. You'd need to generate certificates for the new SAN too. Overall, this is a dangerous set of changes on a running cluster and I don't recommend it. We're hoping to make these rotations easier in future.

**Comment by pjatacsukb** [comment]
Thank you, we are gonna investigate how really badly we need the reinstall then.

**Comment by joshix** [comment]
fixed in https://coreos.com/tectonic/docs/latest/install/bare-metal/index.html#dns

**Comment by mfburnett** [comment]
Going to close this issue for now, given the documented requirements. @pjatacsukb please feel free to comment and re-open if you have further issues.
