### ISSUE TITLE
specify IAM roles

### ISSUE THREAD

**Issue by patagona-afriemann** [coreos/tectonic-forum#73]
### Environment

AWS

### Desired Feature

I can specify the IAM role for workers/controllers.

### Other Information

This behavior is necessary for us since we use IAM roles to separate privileges for pods with kube2iam. This requires modifying roles to allow the worker role to assume them. Doing this after creating the cluster is not feasible (especially with green/blue environments).

**Comment by robszumski** [comment]
This is being tracked in our installer repo here: https://github.com/coreos/tectonic-installer/issues/666
