### ISSUE TITLE
Deletion fails with existing VPC on AWS

### ISSUE THREAD

**Issue by patagona-afriemann** [coreos/tectonic-forum#75]
### Tectonic Version 

1.5.3

### Environment

AWS

### Expected Behavior

Deleting the cloudformation stack should terminate.

### Actual Behavior

Deletion fails with error 

```
Network vpc-xxxxxxxx has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
```

when deleting the VPCGatewayAttachment.

### Reproduction Steps

  1. Create a cluster in an existing VPC.
  2. Go to the cloudformation console and delete the stack.
  3. Wait forever.

### Other Information

This should not even happen. It seems to me the template/cloudformation tries to delete the existing IGW, which would be devastating to our environment.

**Comment by mfburnett** [comment]
Hi @patagona-afriemann - this is a bug that we are resolving in the upcoming release next week. Thanks for bringing this up.

**Comment by mfburnett** [comment]
@patagona-afriemann this should be resolved now! Closing this issue; feel free to reopen with any questions or comments.
