### ISSUE TITLE
Installer freezes due to what seems to be SOA timeout

### ISSUE THREAD

**Issue by rezaloo** [coreos/tectonic-forum#78]
### Tectonic Version 
Latest Stable

### Environment

AWS

### Expected Behavior

Installation completes

### Actual Behavior

Installation frozen at Kublet start: 

```Starting Kubelet
 Resolving r-type-k8s.treza.com
 Waiting for kubelet to be ready```

Seems like it's due to my SOA TTL having been too high. I did change this from 900 to 60 after I noticed this massage, but it has not helped.



### Reproduction Steps

  1. ...
  2. ...

### Other Information

## Feature Request

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

### Desired Feature

### Other Information

**Comment by mfburnett** [comment]
@rezaloo thanks for filing this issue! I've let @ErnestG4 know; he should get back to you in a few days. He will pull in any other team members as necessary.

**Comment by lblackstone** [comment]
I'm seeing the same behavior, but I'm not sure it's due to the SOA timeout. Mine is set at 60 seconds, and I let the installer run for nearly an hour before the service token expired.

I've deleted the CF stack and tried again again a couple of times, with and without the experimental operators feature enabled, but the same thing keeps happening.

**Comment by rezaloo** [comment]
Just to update this issue. I tried to install from scratch (now using 1.5.5) and this time set the SOA TTLs to 60 from the onset. This time installer seems to be stuck when trying to start Kubelet. Been in this state for 1+ hour. I have attached the screen shot. 

[installer.pdf](https://github.com/coreos/tectonic-forum/files/891146/installer.pdf)

**Comment by ggreer** [comment]
It looks like you need to update your nameservers in your registrar:

    ggreer@zinc:~% whois rtype.com
    ...
    Name Server: NS.123-REG.CO.UK
    Name Server: NS2.123-REG.CO.UK

also:

    ggreer@zinc:~% dig NS rtype.com
    ;; ANSWER SECTION:
    rtype.com.		12822	IN	NS	ns.hosteurope.com.
    rtype.com.		12822	IN	NS	ns2.hosteurope.com.

Those NS records should be something like ns-1069.awsdns-05.org.

**Comment by rezaloo** [comment]
This was my bad - I was using the wrong domain. Once I used one with a reachable NS, the installation completed successfully. Thanks a great deal for your help.

**Comment by ggreer** [comment]
Glad that helped. Just FYI, the installer will soon have more warning messages related to these kinds of mistakes.
