### ISSUE TITLE
Install without IGW and NAT Gateways ?

### ISSUE THREAD

**Issue by dadux** [coreos/tectonic-forum#79]
### Tectonic Version 
1.5.3-tectonic.1
### Environment
AWS

### Expected Behavior
We are trying to deploy to an existing VPC that uses Virtual Private Gateway to our AWS direct connect. 
We should be able to manually specify the subnets when there's no IGW or NATGW.

### Actual Behavior
No subnets are available for selection.

### Reproduction Steps
VPC that doesn't use IGW or NAT Gateways.

### Desired Feature
Ability to manually select the subnet for existing VPC option.

**Comment by mfburnett** [comment]
Hi @dadux - right now, we do require NAT Gateways. However, we're working on loosening that requirement in the upcoming releases. I'll make sure to keep you updated.

**Comment by mfburnett** [comment]
@dadux - the latest versions of Tectonic no longer require NAT Gateways.

**Comment by mfburnett** [comment]
Closing this issue - please feel free to comment and reopen with any questions!
