### ISSUE TITLE
Unable to connect to the server: could not refresh token: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by nithin-bose** [coreos/tectonic-forum#80]
### Tectonic Version 
1.5.3-tectonic.1

### Environment
AWS

### Expected Behavior
The expected kubectl command should complete sucessfully

### Actual Behavior
```
$ kubectl cluster-info
Unable to connect to the server: could not refresh token: invalid character '<' looking for beginning of value
```
### Reproduction Steps
Not exactly sure. This happened all of a sudden during usual workflow
  1.  Generate kube config from tectonic
  2.  Appeared all of a sudden after a few days

### Other Information
Recreated kube config again from tectonic and replaced the existing config with the new one. Things seem to work fine now.

**Comment by mfburnett** [comment]
Hi @nithin-bose - thanks for letting us know about this. I've passed this along to our team and will let you know when we start investigating!

**Comment by nithin-bose** [comment]
This seems to be happening quite frequently now a days. Is there something I can do as a work around??

**Comment by kbrwn** [comment]
@nithin-bose could you grab the logs from the tectonic-identity container immediately after attempting a `kubectl cluster-info` ? If would also be helpful to verify that your kubeconfig is valid. You can email it to me at kyle.brown@coreos.com if you prefer.

**Comment by kbrwn** [comment]
@nithin-bose what is your version of kubectl? The error: 

```
time="2017-03-21T05:34:29Z" level=error msg="refresh token with id 76glzufe5r7q35br7vuawdi2jm claimed twice" 
time="2017-03-21T05:36:06Z" level=error msg="refresh token with id 76glzufe5r7q35br7vuawdi2jm claimed twice" 
time="2017-03-21T05:36:50Z" level=error msg="refresh token with id 76glzufe5r7q35br7vuawdi2jm claimed twice" 
time="2017-03-21T05:40:05Z" level=error msg="refresh token with id 76glzufe5r7q35br7vuawdi2jm claimed twice" 
``` 

Is possibly an issue with using an older version of kubectl. 

```
$ kubectl cluster-info
Unable to connect to the server: could not refresh token: invalid character '<' looking for beginning of value
```

Is likely related to ingress being unable to talk to dex or dex failing a healthcheck (this does not appear to be the case from the logs you shared via email.)

**Comment by nithin-bose** [comment]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sym3tri** [comment]
I believe this was fixed in version 1.5.4-tectonic.1. @ericchiang can you confirm?

**Comment by ericchiang** [comment]
This error:

```
time="2017-03-21T05:34:29Z" level=error msg="refresh token with id 76glzufe5r7q35br7vuawdi2jm claimed twice" 
```

implies you're using the same kubeconfig in two places, and is unrelated to a different fix. tectonic-identity implements refresh token rotation to identify when someone else has redeemed your refresh token (potentially maliciously).

**Comment by nithin-bose** [comment]
Sorry for the late reply

This happens in my CI/CD server. I am not using the same config a two places. What I think happens is 
1. helm finds the token is invalid
2. helm uses the refresh fresh token (refresh token is used once) to get the new token
3. The build runs
4. The CI/CD server discards the build environment including the changes to the config file in step 2
5. Another build happens, and helm finds the token is invalid
6. helm uses the refresh fresh token (second use of the refresh token) and errors out

I have no idea how to fix this, is there an API or something to renew the config file?

**Comment by ericchiang** [comment]
@nithin-bose I'd recommend using a service account token for your CI/CD system, not your OpenID Connect configuration. The latter's meant for human use, the former's for automation.

**Comment by nithin-bose** [comment]
Correct me if I am wrong, but service accounts can only be used from with in the cluster right?? And my CI server is outside my cluster.

**Comment by ericchiang** [comment]
@nithin-bose you're service account credentials are just bearer tokens.[0] You can use them to connect from wherever.

[0] https://kubernetes.io/docs/admin/authentication/#service-account-tokens

**Comment by nithin-bose** [comment]
I am still stuck on this. Can you tell me how to gene a kube-config file for a service account so I can use helm from outside the cluster?

**Comment by robszumski** [comment]
@nithin-bose You can manually construct a kubeconfig with the bearer token:

```
apiVersion: v1
kind: Config
users:
- name: serviceaccount
  user:
    token: eyJpc3MiOiJrdWJlcm5ldeyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9GVzL3z ...snip...
clusters:
- name: us-east
  cluster:
     server: https://us-east.example.com:443
     certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM ...snip...
contexts:
- context:
    cluster: us-east
    user: serviceaccount
    namespace: production
  name: production
current-context: production
```

You will need to provide a `token`, `server` and base64'd `certificate-authority-data`

**Comment by nithin-bose** [comment]
That seems to work thanks
