### ISSUE TITLE
Private subnets in an existing VPC is not recognized by the installer

### ISSUE THREAD

**Issue by paalkr** [coreos/tectonic-forum#82]
### Tectonic Version 
1.5.3-tectonic.1

### Environment
Windows 10

What hardware/cloud provider/hypervisor is being used with Tectonic?
AWS

### Expected Behavior
Private subnets in an existing VPC is not recognized

### Actual Behavior
We have an existing VPC with 3 private and 3 public subnets. The install wizard does not recognize any of the private subnets when selecting the existing VPC in the wizard.

### Other Information
Please see below for our subnet setup. 
![subnets](https://cloud.githubusercontent.com/assets/9726307/24014916/faec76c8-0a86-11e7-98a9-62a86bc01e19.png)

The private subnets are routed to our on premise data center through VPN tunnels, and they route to internet through NAT instances in the public subnets.

Error message in the installer
![installer_error](https://cloud.githubusercontent.com/assets/9726307/24015191/fefba120-0a87-11e7-8f9c-3b1216a90c96.png)

**Comment by mfburnett** [comment]
Hi @paalkr, thanks for filing this issue. Pulling in @kbrwn, who will respond in a few days and pull in others from our team as necessary!

**Comment by mfburnett** [comment]
@paalkr this should have been resolved with the latest releases of Tectonic - the most recent is Tectonic 1.6.2-tectonic.1. Going to close this issue for now but feel free to reopen if you are still experiencing this issue.
