### ISSUE TITLE
Tectonic v1.5.4 Installer bootkube race condition

### ISSUE THREAD

**Issue by pompomJuice** [coreos/tectonic-forum#83]
### Tectonic Version 
1.5.4
### Environment

bare metal dell server

### Expected Behavior

It should work

### Actual Behavior

It does not work

### Reproduction Steps

  1. Follow installation steps as given

### Other Information

All of the bootkube `ExecStartPre` jobs are running asynchronously (think it is because of **sh -c ''**) that causes `bootkube-start` to fail because the "assets" folder has not been prepared yet. (In this case the chmod fails)

## Feature Request
Add many extra `ExecStartPre=/bin/sleep 1` to turn spaghetti code into that sequentially consistent working kind of code...

Maybe add extra `ExecStartPre=-/bin/sh -c 'rm -rf /opt/bootkube/assets'` to enable bootkube to run at least more than once before all the other `ExecStartPre` jobs

Add extra brain power to the dev team.

**Comment by pompomJuice** [comment]
```
[Unit]
Description=Bootstrap a Kubernetes control plane with a temp api-server
[Service]
Type=simple
WorkingDirectory=/opt/bootkube
ExecStartPre=-/bin/sh -c 'rm -rf /opt/bootkube/assets'
ExecStartPre=-/bin/sh -c '/usr/bin/base64 --decode /opt/bootkube/assets.b64 > /opt/bootkube/assets.zip'
ExecStartPre=-/usr/bin/unzip /opt/bootkube/assets.zip -d /opt/bootkube
ExecStartPre=-/bin/sh -c 'chmod +x /opt/bootkube/assets/bootkube-start'
ExecStartPre=/bin/sleep 5
ExecStart=/opt/bootkube/assets/bootkube-start

```

**Comment by pompomJuice** [comment]
The assets that are now delivered via matchbox base64 payload is really impressive.

Who ever suggested that should get a promotion immediately.

**Comment by mfburnett** [comment]
Closing this per our Code of Conduct guidelines.
