### ISSUE TITLE
Missing Admission Controller DefaultStorageClass

### ISSUE THREAD

**Issue by mcfedr** [coreos/tectonic-forum#84]
### Tectonic Version 
1.5.4-tectonic.1
### Environment
AWS
### Expected Behavior
DefaultStorageClass to be enabled after install
### Actual Behavior
Its not
### Reproduction Steps

  1. Start cluster using tectonic

### Other Information
I've now added it to the params in the daemonset for the api server, now trying to workout how i can restart the api server

**Comment by mfburnett** [comment]
Hi @mcfedr, thanks for filing this issue. Pulling in @kbrwn here, who will get back to you in a few days. He'll pull in others from our team as necessary.

**Comment by kbrwn** [comment]
@mcfedr 

You can edit and restart the api-server pod with the following commands: 

```
kubectl get daemonset/kube-apiserver --namespace=kube-system -oyaml > api.yaml
<edit api.yaml with your favorite editor>
kubectl apply -f api.yaml
```
Just FYI, automatic/push button updates to the cluster are no longer supported if you make modifications to the kube-apiserver. 

It looks like dynamic provisioning and storages classes is no longer beta in 1.6. I believe this means  DefaultStorageClass should be supported without any modification of the api-server.
