### ISSUE TITLE
Etcd is deployed with http plain text

### ISSUE THREAD

**Issue by vmatekole** [coreos/tectonic-forum#86]
We're are moving away from etcd and fleet as a result of discovering Tectonic. Our hope was that Tectonic would deploy etcd over TLS. Our current setup has TLS enabled but it was a trial to get it setup. Are there any plans to include TLS for etcd in future updates to Tectonic?

### Tectonic Version 
1.5.3
### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?
Vultr cloud service
### Expected Behavior
etcd to be deployed over TLS
### Actual Behavior
Deployed over HTTP

**Comment by mfburnett** [comment]
Hey @vmatekole, thanks for filing this issue. This is on our immediate roadmap; I'll let you know when it ships!

**Comment by robszumski** [comment]
Hi @vmatekole, Tectonic 1.6.7 is out with full TLS support for etcd, no matter how it's deployed. Check it out: https://coreos.com/blog/kubernetes-the-coreos-way

**Comment by vmatekole** [comment]
@robszumski Fantastic! After Fleet lost support — we ended up going with Docker cloud and Ubuntu, for the time being... With a view to returning to our much loved CoreOS, once Tectonic has better support for cloud deployment, currently only AWS. Looking forward to getting back into it later in the yr.

**Comment by robszumski** [comment]
@vmatekole What platform are you looking for? We have Azure, VMware, and OpenStack in alpha.

**Comment by vmatekole** [comment]
@robszumski  Digital Ocean. However, I have tried on Vultur as they support iPxe boot. I managed to deploy successfully, after much persistence, but then ran into some other issues.

**Comment by robszumski** [comment]
As an FYI, work is underway on DO here: https://github.com/coreos/tectonic-installer/pull/604
