### ISSUE TITLE
Unable to deploy the OMS agent as a Daemon Set using the UI

### ISSUE THREAD

**Issue by OguzPastirmaci** [coreos/tectonic-forum#87]
### Tectonic Version
1.5.4-tectonic.1

### Environment
MacOS Sierra 10.12.3

#### What hardware/cloud provider/hypervisor is being used with Tectonic?
Azure

### Expected Behavior
Being able to deploy the containerized Microsoft OMS agent as a Daemon Set using the UI.

### Actual Behavior
The UI says "the server does not allow this method on the requested resource". Deploying the same yaml with Kubectl works.

### Reproduction Steps

  1. Login to Tectonic UI.
  2. Use the following yaml to create a Daemon Set. The values in WSID and KEY doesn't matter.
https://github.com/Microsoft/OMS-docker/blob/master/Kubernetes/omsagent.yaml

### Other information
<img width="1256" alt="screen shot 2017-03-22 at 12 32 06 pm" src="https://cloud.githubusercontent.com/assets/11318065/24217082/d3a9fff8-0efb-11e7-8942-69794f349a4e.png">

**Comment by mfburnett** [comment]
Hi @OguzPastirmaci, thanks for filing this issue! Have you seen our recently announced [preview availability for Tectonic on Microsoft Azure](https://github.com/coreos/tectonic-installer)?

**Comment by OguzPastirmaci** [comment]
Hi @mfburnett, yes I've seen it and it's great :)

**Comment by mfburnett** [comment]
@OguzPastirmaci awesome! Going to close this issue, as we are developing support for Tectonic on Azure.
