### ISSUE TITLE
bare-metal

### ISSUE THREAD

**Issue by aiwuzhang** [coreos/tectonic-forum#92]
## Issue Report Template
I install tectonic on vms created by virtaulbox. 
### Environment
host:ubuntu 
virtualbox:5.1.18
use VM(virtual machine) as  bare-metal machine
VM: ubuntu-server 14.04
What hardware/cloud provider/hypervisor is being used with Tectonic?
on VM.
### Expected Behavior
start VM by ipxe.
I followed the handbook of https://github.com/coreos/matchbox/blob/master/Documentation/network-setup.md
The DNS ,DHCP used dnsmasq, all seem OK.

But the matchbox confused me. I downloaded the undionly.kpxe,  but where to download the "boot.ipxe " which shows in "dhcp-boot=tag:ipxe,http://matchbox.foo:8080/boot.ipxe"

Sincerely look forward to your reply

### Reproduction Steps

  1. ...
  2. ...

### Environment

What hardware/cloud provider/hypervisor is being used with Tectonic?

**Comment by dghubble** [comment]
Tectonic clusters are made up of CoreOS Container Linux nodes. Ubuntu is not supported by Tectonic or the associated tooling.
